### PR TITLE
Integration of Aliyun OCR Tool

### LINKED ISSUE #10700: Integration of Aliyun OCR Tool in Dify
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

**Is this request related to a challenge you are facing?**
Yes, in my work, I deal with a large number of posters that require extracting the names of artists and music groups from poster images. This is a repetitive task that could be automated.

**What is the feature you'd like to see?**
I propose the integration of the Aliyun OCR tool into Dify. Users should be able to input their AccessKey and AccessSecret to use this tool. The tool should accept an image address as input and return the text information in the image.

**How will this feature improve your workflow / experience?**
This feature will save a lot of time and effort by automating the extraction of text from images, which is a task I frequently need to perform.

### 2. Additional context or comments

None

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by liujichengs**
# Summary

1、I deal with a large number of posters that require extracting the names of artists and music groups from poster images. This is a repetitive task that could be automated.
2、I integration of the Aliyun OCR tool into Dify. Users should be able to input their AccessKey and AccessSecret to use this tool. The tool should accept an image address as input and return the text information in the image.
This feature will save a lot of time and effort by automating the extraction of text from images, which is a task I frequently need to perform.

3、My issue: [https://github.com/langgenius/dify/issues/10700](https://github.com/langgenius/dify/issues/10700)
Resolves #10700

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

<table>
  <tr>
  <td>Before:  </td>
  <td>After: 
</td>
  </tr>
  <tr>
  <td></td>
  <td></td>
  </tr>
</table>

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by liujichengs** [comment]
merged master again, there are no conflicts now

**Review by crazywoola — DISMISSED** [review]

**Comment by crazywoola** [comment]
Please fix the lint errors by running `./dev/reformat` in root dir.

**Comment by liujichengs** [comment]
done thks

**Comment by liujichengs** [comment]
It has been resolved.
The reason is that my version is smaller than the main version
thks and have a good day

**Comment by crazywoola** [comment]
Hi there,
We plan to test v1.0 around  Dec 5 in our staging environment. Currently, we do not accept tools and model providers anymore until the v1.0 is released. 

However,  if you are interested in testing it out, and make tools & llms to that version.

Please fill this form https://forms.gle/8sQWmqPWCo5GEn8w7.
We only collect emails for accessing our staging environment by this whitelist. You can use this email to login into our system then. No spam  📧

Here is the discord channel https://discord.gg/H6zB7zAW, wechat: crazyphage
I will list the docs and other necessary information in 👆 channel until I get updates from our dev team.

Thanks again for your unwavering support.❤️

**Pull request closed without merging**
