### PR TITLE
fix: Revert "feat: initial support for Milvus 2.4.x (#3795)" downgrading to 2.3.x for Linux arm64 installation failure

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- This reverts commit bb33ffc3327c0a8aca72e2e347ac63de949b3396 from PR #3795
- It's reported from the CI runs in #5105 for building dockerfile for Linux for x86 and arm architecture. It succeed on Linux on x86, but failed on arm64.
- `pymilvus`, the Python SDK for Milvus, requires `milvus-lite` package since 2.4.x. However `milvus-lite` does not provide whl prebuite packages for Linux on arm64 (only providing MacOS on arm64). This blocks the `pymilvus` installation. referring to https://pypi.org/project/milvus-lite/2.4.7/#files
- `milvus-lite` plans to support Linux on arm64 in future versions, https://github.com/milvus-io/milvus-lite/issues/137#issuecomment-2126153503

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @takatost @JohnJyong @crazywoola

**Review by takatost — APPROVED** [review]
LGTM

**Comment by junjiejiangjjj** [comment]
Milvus-lite 2.4.8 now supports poetry and arm64

**Comment by bowenliang123** [comment]
Yes, I have noticed this change yesterday. Will raise a PR for it soon.

**Pull request merged**
