### PR TITLE
fix: suggested questions language

### PR DESCRIPTION
**Pull request by YidaHu**
# Description

This PR introduces the ability to specify the language for generating suggested questions based on the app settings. Previously, the language was not specified. Now, the language can be set according to the app's settings, providing a more personalized and accurate generation of suggested questions for different language users.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leslie2046** [comment]
Maybe sometimes the suggested questions language should follow the language from user inputs in multilingal?
Sometimes we cannot set a language to a certain fixed  language i think。

**Comment by YidaHu** [comment]
> Maybe sometimes the suggested questions language should follow the language from user inputs in multilingal? Sometimes we cannot set a language to a certain fixed language i think。

@leslie2046 You're right. Then I think prompt should be modified so that the LLM can give the corresponding language suggestions based on the context language. Not according to the set language.

**Comment by takatost** [comment]
Since the default strategy is not specifically for English, but for all languages, sometimes there may be some issues with language understanding. 
I suggest reverting the default strategy back to its original state here, and if a specific language is passed in, then add the corresponding prompt.

**Comment by takatost** [comment]
> Since the default strategy is not specifically for English, but for all languages, sometimes there may be some issues with language understanding. I suggest reverting the default strategy back to its original state here, and if a specific language is passed in, then add the corresponding prompt.

Any progress?

**Comment by YidaHu** [comment]
> > Since the default strategy is not specifically for English, but for all languages, sometimes there may be some issues with language understanding. I suggest reverting the default strategy back to its original state here, and if a specific language is passed in, then add the corresponding prompt.
> 
> Any progress?

I found that it is the LLM effect problem, and the service does not need to be modified. I close

**Pull request closed without merging**
