### PR TITLE
feat: support pinning, including, and excluding for Model Providers and Tools

### LINKED ISSUE #7282: Support customization of model provider and tool lists via environment variables
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, the application does not offer the ability to customize the Model Provider and Tool lists.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by GareArc**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

This pull request implements a new feature that allows Model Providers and Tools to support custom lists. Users can now pin, include, and exclude specific models and tools through environment variables.

Fixes #7282 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by GareArc** [comment]
The test failures were caused by a typo (soloar-1-mini-chat instead of solar-1-mini-chat). I've submitted a separate PR #7286 to fix this issue. Once that PR is merged, I'll update this one to ensure the tests pass.

**Comment by crazywoola** [comment]
#7286 Merged

**Review by crazywoola — CHANGES_REQUESTED** [review]
You need to update `docker/.env.example` as well. Please make make sure update the [Official Docs](https://docs.dify.ai/getting-started/install-self-hosted/environments) accordingly.

**Review by crazywoola — APPROVED** [review]

**Comment by WangLiRu** [comment]
This merge  will lost many of builtin tools, please check.

**Comment by wlrnet** [comment]
This merge will lost many of builtin tools, please check.

after pull this merge code, such as Terllo or Twilio etc.. will lost:
Screenshot 2024-08-15 at 2 35 29 PM


if rollback this merge, tools backed:
Screenshot 2024-08-15 at 2 35 56 PM

**Comment by wlrnet** [comment]
@GareArc  Do you have this issue?

**Comment by GareArc** [comment]
> @GareArc Do you have this issue?

Apologies for the issue. Yes, it unintentionally ignores tools that are not defined in the _position.yaml file. I've already applied a revert commit to address this. I'm actively working on a fix to resolve the issue completely.

**Pull request merged**
