### PR TITLE
feat: return page number of pdf documents upon retrieval

### LINKED ISSUE #7738: Include Original Document Page Numbers in Retrieval Results
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When adding a pdf document into `kwnowledge`, it saved the page_number with metadata
```python
# api/core/rag/extrator/pdf_extractor.py
...
for page_number, page in enumerate(pdf_reader):
    text_page = page.get_textpage()
    content = text_page.get_text_range()
    text_page.close()
    page.close()
    metadata = {"source": blob.source, "page": page_number}
    yield Document(page_content=content, metadata=metadata)
...
```

and this `page_number` is saved into a vector store. however, this value is not returned with knowledge retrieval. I believe a simple change in `knowledge_retrieval_node.py` and/or `llm_node.py` would add page_number to the retrieval results. If you guys are willing to accept a PR, I will make one

### 2. Additional context or comments

I would appreciate it if you could provide access to the original documents or sources that the LLM referenced when generating its response. Including the specific page numbers would greatly enhance the credibility of the information.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### LINKED ISSUE #7944: Add page number to the segments
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently the segment do not track which page of the document it is originate from -- this makes it impossible to point users to the exact page to look for or open a pdf/doc to the right page in an app. The proposal is to add to segment a new field `page: int` that will allow to track segment to page.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by jasonkang14**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- Return the original page number of an uploaded pdf file when retrieving knowledge. 
    - the value will be `None` if `page` is not in the knowledge base 
- Closes #7738 
- Closes https://github.com/langgenius/dify/issues/7944

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested on different local files besides pdf and it works
- [x] page number is returned when querying a pdf file
 
Screenshot 2024-08-28 at 4 00 40 PM

### CODE REVIEW

**Comment by crazywoola** [comment]
I tried several PDFs but always get the page number as `null`.

**Comment by jasonkang14** [comment]
@crazywoola i will check again.

**Comment by jasonkang14** [comment]
@crazywoola i think its because not all vector stores save page numbers. can i change those as well?

**Comment by jasonkang14** [comment]
@crazywoola it's a bug with weaviate. i have tried other vector stores and it retrieves page numbers. and i have found a bug with milvus so will be making another PR for each

**Comment by crazywoola** [comment]
> @crazywoola it's a bug with weaviate. i have tried other vector stores and it retrieves page numbers. and i have found a bug with milvus so will be making another PR for each

@jasonkang14 You can fix the weaviate db in this PR, and you can open another one to fix others. :)

**Comment by jasonkang14** [comment]
@crazywoola I have found a better way to resolve this. It turned out that other vector stores were actually returning `page` which was not included in the attributes in `vector_factory.py` now the "weaviate bug" has been fixed

Screenshot 2024-09-05 at 2 52 42 PM

**Review by crazywoola — APPROVED** [review]
Cool, I got the page number from the doc. :)

**Comment by ifsheldon** [comment]
@crazywoola @jasonkang14 This silently breaks my existing Dify that is built from the older source code. My Dify was in use prior to this commit, so the existing weaviate DB does not have `page` field. 

When I updated the source code which includes this commit and built and run it again, I got a weird error stating something like `Vector index xxxxx does not have "page" field`. The error is caught high up in the stack, so it took me a day to locate the exception. 

I think this is actually a breaking change. Probably you should advise on how to do a DB migration?

**Comment by jasonkang14** [comment]
@ifsheldon On my end, a database migration was not necessary. Dify automatically stores the extracted text from PDFs into the vector store. The recent update simply ensures that the page is now included in the retrieval process. check out the source code below

https://github.com/langgenius/dify/blob/af92f19291cc407ae6b70c3fc0b73276d5edbd47/api/core/rag/extractor/pdf_extractor.py#L69

**Comment by ifsheldon** [comment]
@jasonkang14 The problem, I guess, is if the content of a knowledgebase comes from pure text, then the metadata will not contain `page` field. However, you changed the default attributes to search, adding `page` into `attributes`. Then, the knowledgebase backed by weaviate will throw an exception. You can try simply creating a knowledgebase from a txt file and making a hit test.

**Pull request merged**
