### PR TITLE
chore: refactor the http executor node

### PR DESCRIPTION
**Pull request by hjlarry**
# Description

Change List:

1. remove the `requests` of ssrf_proxy. In the past, we use both `httpx` and `requests` because it support body of DELETE method. Now we can use httpx to achieve it too. [more details here](https://www.python-httpx.org/compatibility/#request-body-on-http-methods)
2. remove the `OPTION` method of backend, and make the `GET` / `DELETE` / `HEAD` also support http body. This maintains the consistency between the front-end and back-end. In the past , we implicit drop the body of `GET`.
3. upgrade httpx from 0.24.1 to 0.27.0.  the [release note](https://github.com/encode/httpx/releases) seems not to affect our usage scenarios. It support Python3.12 which maybe we will support later, and the `proxies` parameter will be deprecate later, use a single`proxy` for all request maybe more commonly used. 
4. drop `*args` of ssrf_proxy request methods, cause httpx only support `**kwargs`.
5. refactor the `_to_dict` method which convert params/headers/body from frontend to python dict, and add test for it.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [x] Dependency upgrade

# How Has This Been Tested?

Integration test and local test.

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hjlarry** [comment]
@Yeuoly @bowenliang123 please review it, thanks

**Comment by Yeuoly** [comment]
Hi, thanks a lot for the refactoring! but there are still some parts that need improvement. Specifically, in the core.tools.tool.api_tool, the `do_http_request` and `validate_and_parse_response` methods also use `ssrf_proxy`. I intend to refactor these as well. how to you think of it?

**Comment by bowenliang123** [comment]
+1 for refactoring the HTTP requesting both in HTTP executor node and in API tools, unifying into using `httpx`.

**Comment by bowenliang123** [comment]
BTW, please rebase the changes onto the latest commits. Update the poetry dependencies in pyproject.yml and poetry lockfile as well (running `dev/update-poetry`).

**Review by ghost — APPROVED** [review]

**Comment by crazywoola** [comment]
Please fix the CI

**Comment by hjlarry** [comment]
> Please fix the CI

as this PR(https://github.com/langgenius/dify/pull/5319) merged will fix the CI

**Comment by bowenliang123** [comment]
Wait for #5319 fixing the problem merged, and then rebase onto it.

**Comment by crazywoola** [comment]
Fixed @hjlarry

**Comment by hjlarry** [comment]
> Hi, thanks a lot for the refactoring! but there are still some parts that need improvement. Specifically, in the core.tools.tool.api_tool, the `do_http_request` and `validate_and_parse_response` methods also use `ssrf_proxy`. I intend to refactor these as well. how to you think of it?

done! please review again. @Yeuoly @bowenliang123

**Comment by bowenliang123** [comment]
LGTM overall.

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by Yeuoly** [comment]
Thanks for your great job!

**Pull request merged**
