### PR TITLE
feat(document_extractor): integrate unstructured API for PPTX extraction

### PR DESCRIPTION
**Pull request by laipz8200**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- Added support for using the unstructured API for PPTX text extraction when available.
- Falls back to existing method if API credentials are not configured.
- Ensures flexibility and potentially enhanced performance or accuracy in text extraction.

#9995

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Comment by laipz8200** [comment]
> Could you advise me how to use this? I have set the env variables in docker .env but it didn't work. image image image

Thank you for the report, link to #10886

**Comment by fdb02983rhy** [comment]
Please note this feature isn't functioning as expected even the env var are configured.

```
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
api-1         |     for item in respiter:
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
api-1         |     return self._next()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
api-1         |     for item in iterable:
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
api-1         |     yield from gen
api-1         |   File "/app/api/libs/helper.py", line 186, in generate
api-1         |     yield from response
api-1         |   File "/app/api/core/app/features/rate_limiting/rate_limit.py", line 115, in __next__
api-1         |     return next(self.generator)
api-1         |   File "/app/api/core/app/apps/base_app_generate_response_converter.py", line 25, in _generate_full_response
api-1         |     for chunk in cls.convert_stream_full_response(response):
api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_response_converter.py", line 67, in convert_stream_full_response
api-1         |     for chunk in stream_response:
api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 187, in _to_stream_response
api-1         |     for stream_response in generator:
api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 218, in _wrapper_process_stream_response
api-1         |     for response in self._process_stream_response(tts_publisher=tts_publisher, trace_manager=trace_manager):
api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 319, in _process_stream_response
api-1         |     workflow_node_execution = self._handle_workflow_node_execution_failed(event)
api-1         |   File "/app/api/core/app/task_pipeline/workflow_cycle_manage.py", line 339, in _handle_workflow_node_execution_failed
api-1         |     WorkflowNodeExecution.process_data: json.dumps(event.process_data) if event.process_data else None,
api-1         |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
api-1         |     return _default_encoder.encode(obj)
api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
api-1         |     chunks = self.iterencode(o, _one_shot=True)
api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
api-1         |     return _iterencode(o, 0)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/frozendict/__init__.py", line 32, in default
api-1         |     return BaseJsonEncoder.default(
api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
api-1         |     raise TypeError(f'Object of type {o.__class__.__name__} '
api-1         | TypeError: Object of type File is not JSON serializable
```

**Comment by laipz8200** [comment]
> ## 1
> 
> The knowledge chunking works fine after the fix. [fix10953](https://github.com/langgenius/dify/pull/10953) image
> ## 2
> 
> However, it isn't functioning as expected for pptx extraction.
> 
> ```
> api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
> api-1         |     for item in respiter:
> api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
> api-1         |     return self._next()
> api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
> api-1         |     for item in iterable:
> api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
> api-1         |     yield from gen
> api-1         |   File "/app/api/libs/helper.py", line 186, in generate
> api-1         |     yield from response
> api-1         |   File "/app/api/core/app/features/rate_limiting/rate_limit.py", line 115, in __next__
> api-1         |     return next(self.generator)
> api-1         |   File "/app/api/core/app/apps/base_app_generate_response_converter.py", line 25, in _generate_full_response
> api-1         |     for chunk in cls.convert_stream_full_response(response):
> api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_response_converter.py", line 67, in convert_stream_full_response
> api-1         |     for chunk in stream_response:
> api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 187, in _to_stream_response
> api-1         |     for stream_response in generator:
> api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 218, in _wrapper_process_stream_response
> api-1         |     for response in self._process_stream_response(tts_publisher=tts_publisher, trace_manager=trace_manager):
> api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 319, in _process_stream_response
> api-1         |     workflow_node_execution = self._handle_workflow_node_execution_failed(event)
> api-1         |   File "/app/api/core/app/task_pipeline/workflow_cycle_manage.py", line 339, in _handle_workflow_node_execution_failed
> api-1         |     WorkflowNodeExecution.process_data: json.dumps(event.process_data) if event.process_data else None,
> api-1         |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
> api-1         |     return _default_encoder.encode(obj)
> api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
> api-1         |     chunks = self.iterencode(o, _one_shot=True)
> api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
> api-1         |     return _iterencode(o, 0)
> api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/frozendict/__init__.py", line 32, in default
> api-1         |     return BaseJsonEncoder.default(
> api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
> api-1         |     raise TypeError(f'Object of type {o.__class__.__name__} '
> api-1         | TypeError: Object of type File is not JSON serializable
> ```

Could you please open an issue for this and share your version, dsl for us to reproduce this problem?

**Comment by fdb02983rhy** [comment]
> > ## 1
> > The knowledge chunking works fine after the fix. [fix10953](https://github.com/langgenius/dify/pull/10953) image
> > ## 2
> > However, it isn't functioning as expected for pptx extraction.
> > ```
> > api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
> > api-1         |     for item in respiter:
> > api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
> > api-1         |     return self._next()
> > api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
> > api-1         |     for item in iterable:
> > api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
> > api-1         |     yield from gen
> > api-1         |   File "/app/api/libs/helper.py", line 186, in generate
> > api-1         |     yield from response
> > api-1         |   File "/app/api/core/app/features/rate_limiting/rate_limit.py", line 115, in __next__
> > api-1         |     return next(self.generator)
> > api-1         |   File "/app/api/core/app/apps/base_app_generate_response_converter.py", line 25, in _generate_full_response
> > api-1         |     for chunk in cls.convert_stream_full_response(response):
> > api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_response_converter.py", line 67, in convert_stream_full_response
> > api-1         |     for chunk in stream_response:
> > api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 187, in _to_stream_response
> > api-1         |     for stream_response in generator:
> > api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 218, in _wrapper_process_stream_response
> > api-1         |     for response in self._process_stream_response(tts_publisher=tts_publisher, trace_manager=trace_manager):
> > api-1         |   File "/app/api/core/app/apps/advanced_chat/generate_task_pipeline.py", line 319, in _process_stream_response
> > api-1         |     workflow_node_execution = self._handle_workflow_node_execution_failed(event)
> > api-1         |   File "/app/api/core/app/task_pipeline/workflow_cycle_manage.py", line 339, in _handle_workflow_node_execution_failed
> > api-1         |     WorkflowNodeExecution.process_data: json.dumps(event.process_data) if event.process_data else None,
> > api-1         |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
> > api-1         |     return _default_encoder.encode(obj)
> > api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
> > api-1         |     chunks = self.iterencode(o, _one_shot=True)
> > api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
> > api-1         |     return _iterencode(o, 0)
> > api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/frozendict/__init__.py", line 32, in default
> > api-1         |     return BaseJsonEncoder.default(
> > api-1         |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
> > api-1         |     raise TypeError(f'Object of type {o.__class__.__name__} '
> > api-1         | TypeError: Object of type File is not JSON serializable
> > ```
> 
> Could you please open an issue for this and share your version, dsl for us to reproduce this problem?

Sure https://github.com/langgenius/dify/issues/10956

**Pull request merged**
