### PR TITLE
support xinference tts

### LINKED ISSUE #5118: Add support for Xinference ChatTTS
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Add support for Xinference ChatTTS 

### 2. Describe the feature you'd like to see

Add support for Xinference ChatTTS 

### 3. How will this feature improve your workflow or experience?

Add support for Xinference ChatTTS 

### 4. Additional context or comments

_No response_

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #6138: Please add support for Xinference's TTS models.
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Please add support for Xinference's TTS models.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #6497: Add custom tts voices
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Well specific scenario is that i am using private llms with Dify in order to ensure privacy and security of my data. However if i want to add a voice i have only the option to OpenAI voices which means that i will need to send text to OpenAI and get the response with a voice.

### 2. Additional context or comments

Now there are a lot of private tts projects on Huggingface. One i used and is really cool is AlwaysReddy. Is there a way to add such functionality in Dify?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by Weaxs**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- support add xinference `tts` mode
- support tts invoke (no streaming)
- xinfernce-client v0.13.3
- support xinference [chattts](https://inference.readthedocs.io/en/latest/models/builtin/audio/chattts.html)

> ⚠️ Maybe should support custom voice for xinference tts ? Not supported now.

image
image
image

Close https://github.com/langgenius/dify/issues/6497
Close https://github.com/langgenius/dify/issues/6497
Close https://github.com/langgenius/dify/issues/6138
Close https://github.com/langgenius/dify/issues/5118

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

image
image
image

### CODE REVIEW

**Comment by Weaxs** [comment]
https://github.com/langgenius/dify/issues/6138

https://github.com/langgenius/dify/issues/5118

**Comment by Weaxs** [comment]
I test `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer` with Xinference ChatTTS, here is audio files.
[voices.zip](https://github.com/user-attachments/files/16415865/voices.zip)

**Comment by leslie2046** [comment]
cosyvoice的那些发音人不加上么
中文女
中文男
英文女
英文男
日语男
粤语女
韩语女

**Comment by Weaxs** [comment]
> cosyvoice的那些发音人不加上么 中文女 中文男 英文女 英文男 日语男 粤语女 韩语女

哦哦  我晚点加下，ChatTTS 用这几个效果不太好，还得区分下

**Review by laipz8200 — APPROVED** [review]

**Pull request merged**
