### PR TITLE
feat: add aliyun oss storage

### PR DESCRIPTION
**Pull request by henrybit**
# Description

Use Aliyun oss to store files, need oss2>=2.15.0 library.

## Type of Change
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

1. use my Aliyun ram account's token(AK/SK), create a private read/write bucket, grant full control permission to my ram account; 
2. start API & Web server locally, use Milvus/Redis/Postgresql in My Environment;
3. create a knowledge repository, and upload some PDFs.

results: Upload success/Content vector successfully obtained/Chat success in RAG.

### CODE REVIEW

**Comment by JohnJyong** [comment]
aliyun OSS is compatible with the standard s3 protocolseems , it can be covered in the S3 storage setting @henrybit

**Comment by takatost** [comment]
There is a lint issue that did not pass, please fix it.

**Comment by JohnJyong** [comment]
@henrybit

**Comment by henrybit** [comment]
> There is a lint issue that did not pass, please fix it.

image

fix this lint issue.

**Comment by henrybit** [comment]
> @henrybit

finished.

**Comment by JohnJyong** [comment]
thanks for your contribution~

**Review by JohnJyong — APPROVED** [review]

**Pull request merged**
