### PR TITLE
improve: exract Code Node provider for each supported scripting language

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- extract common CodeNodeProvider for Javascript and Python, to increase the cohesion for each supported programming language code node

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

- no feature introduced, and all changes covered in exited intgration tests for CodeExecutor

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @Yeuoly @takatost

**Comment by Yeuoly** [comment]
Please wait for #4231 to be merged into main, thx!

**Comment by bowenliang123** [comment]
As #4231 was merged and this PR has been rebased,  it is ready for review. Please have a check. @Yeuoly

**Comment by bowenliang123** [comment]
Hi @Yeuoly , I have fixed the JSON serialization problem and added proper tests for it. Please have a look.

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by bowenliang123** [comment]
Thanks~

**Pull request merged**
