### PR TITLE
allow to config max segmentation tokens length for RAG document using environment variable

### LINKED ISSUE #2438: Chunk Size
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

How reproduce ?

Use a Embedding with <1000 dimensions.

### ✔️ Expected Behavior

Working ?

### ❌ Actual Behavior

Error chunk size 0 - 1000
Problem chunk size

How upgrade chunk size limite ? 0-1000 to 0-4096 or higher ?

### PR DESCRIPTION
**Pull request by rainchen**
# Description

allow to config max segmentation tokens length for RAG document using environment variable

Fixes # (issue)

Fix #2438 #3290 
also #4071

## Type of Change

Please delete options that are not relevant.

- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?

manually tested

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JohnJyong** [comment]
pls add the default value for the new variable  in the file : `config.py`  , thanks @rainchen

**Comment by rainchen** [comment]
> pls add the default value for the new variable in the file : `config.py` , thanks @rainchen

refactored, please review again

**Comment by JohnJyong** [comment]
LGTM

**Review by JohnJyong — APPROVED** [review]

**Comment by rennokki** [comment]
@rainchen AMAZING PR! I was wondering if something like this is possible because I was having some texts that were > 1k and they got broke down.

**Pull request merged**
