### PR TITLE
chore: update docker env close #11703

### LINKED ISSUE #11703: AttributeError: 'DifyConfig' object has no attribute 'MAX_SUBMIT_COUNT'
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce
When I upgrade to v 0.14.0, but docker for api server can not up
when i upgrade new version, it turn out this error

### ✔️ Expected Behavior

no any error

### ❌ Actual Behavior

```
Traceback (most recent call last):
  File "/app/api/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
    cli.main()
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 631, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 9, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/app/api/app_factory.py", line 35, in create_app
    initialize_extensions(app)
  File "/app/api/app_factory.py", line 97, in initialize_extensions
    ext.init_app(app)
  File "/app/api/extensions/ext_blueprints.py", line 10, in init_app
    from controllers.console import bp as console_app_bp
  File "/app/api/controllers/console/__init__.py", line 5, in <module>
    from .app.app_import import AppImportApi, AppImportConfirmApi
  File "/app/api/controllers/console/app/app_import.py", line 16, in <module>
    from services.app_dsl_service import AppDslService, ImportStatus
  File "/app/api/services/app_dsl_service.py", line 19, in <module>
    from services.workflow_service import WorkflowService
  File "/app/api/services/workflow_service.py", line 19, in <module>
    from core.workflow.workflow_entry import WorkflowEntry
  File "/app/api/core/workflow/workflow_entry.py", line 18, in <module>
    from core.workflow.graph_engine.graph_engine import GraphEngine
  File "/app/api/core/workflow/graph_engine/graph_engine.py", line 54, in <module>
    class GraphEngineThreadPool(ThreadPoolExecutor):
  File "/app/api/core/workflow/graph_engine/graph_engine.py", line 61, in GraphEngineThreadPool
    max_submit_count=dify_config.MAX_SUBMIT_COUNT,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'DifyConfig' object has no attribute 'MAX_SUBMIT_COUNT'
```

### PR DESCRIPTION
**Pull request by yihong0618**
# Summary

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.
close #11703

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by yihong0618** [comment]
should we add actions for this kind of check?

**Review by crazywoola — APPROVED** [review]

**Comment by crazywoola** [comment]
> should we add actions for this kind of check?

I guess we should.

**Comment by dadastory** [comment]
@crazywoola @yihong0618 

I've set this environment variable, but it still gets an error; this should be a code problem. Is there a new version of Docker released?

image

**Comment by yihong0618** [comment]
> @crazywoola @yihong0618
> 
> I've set this environment variable, but it still gets an error; this should be a code problem. Is there a new version of Docker released?
> 
> image

you can build it in your local?

**Comment by dadastory** [comment]
> > @crazywoola @yihong0618
> > I've set this environment variable, but it still gets an error; this should be a code problem. Is there a new version of Docker released?
> > image
> 
> you can build it in your local?

i pull it again, it works, thks

**Pull request merged**
