### PR TITLE
feat: support minimax abab6.5, abab6.5s

### PR DESCRIPTION
**Pull request by Weaxs**
# Description

support Minimax llm
- abab6.5-chat
- abab6.5s-chat

API doc: https://www.minimaxi.com/document/guides/chat-model/V2
Pricing doc: https://www.minimaxi.com/document/price

Fixes # (issue)
https://github.com/langgenius/dify/issues/3979
## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by takatost — APPROVED** [review]
LGTM

**Comment by ifsheldon** [comment]
image

Have you check if it works? @Weaxs I tried abab-6.5 and abab-6.5s. Both models didn't work due to bad requests. I tried other MiniMax models and they worked as expected.

**Comment by Weaxs** [comment]
> image
> Have you check if it works? @Weaxs I tried abab-6.5 and abab-6.5s. Both models didn't work due to bad requests. I tried other MiniMax models and they worked as expected.

sorry, I forgot to update `model_apis` for minimax , I fix it at this pr https://github.com/langgenius/dify/pull/4116

I have checked it locally
image

**Comment by ifsheldon** [comment]
@Weaxs Thanks a lot for the implementation and fix ❤️

**Pull request merged**
