### PR TITLE
Feat/support to invite multiple users

### PR DESCRIPTION
**Pull request by MatriQ**
* Support to invite multiple users

QA Screenshots:

- Invitation popup:

- Succeed to invite one user:

- Failed to Invite one user:

- Invite multiple users:

### CODE REVIEW

**Review by takatost — CHANGES_REQUESTED** [review]
Thank you very much! 😊
However, there are two areas that need improvement:

1. The link after inviting members is quite long, and it's difficult to distinguish which email the link belongs to. It might be helpful to add a label indicating the corresponding email.
  
    image

3. It might be better to change the default permission for invited members to "normal" (an optimization suggestion). The role can be included in the frontend request parameters.

**Comment by MatriQ** [comment]
> Thank you very much! 😊 However, there are two areas that need improvement:
> 
> 1. The link after inviting members is quite long, and it's difficult to distinguish which email the link belongs to. It might be helpful to add a label indicating the corresponding email.
>     image
> 2. It might be better to change the default permission for invited members to "normal" (an optimization suggestion). The role can be included in the frontend request parameters.

 For the bullet point 1:
The invitation URL is so long that there is nowhere can show it completely. How about showing the email instead of the link?

For the bullet point 2:
It makes more sense.

**Comment by SuperevanZ** [comment]
Hi, based on the points you discussed, I have made adjustments to the UI. 😊
CleanShot 2023-08-29 at 12 02 57@2x


> > Thank you very much! 😊 However, there are two areas that need improvement:
> > 
> > 1. The link after inviting members is quite long, and it's difficult to distinguish which email the link belongs to. It might be helpful to add a label indicating the corresponding email.
> >    image
> > 2. It might be better to change the default permission for invited members to "normal" (an optimization suggestion). The role can be included in the frontend request parameters.
> 
> For the bullet point 1: The invitation URL is so long that there is nowhere can show it completely. How about showing the email instead of the link?
> 
> For the bullet point 2: It makes more sense.

**Comment by MatriQ** [comment]
image
image
image
image

**Review by takatost — APPROVED** [review]
great job!

**Pull request merged**
