### PR TITLE
fix(api/core/tools/entities/tool_entities.py): Fix type define.

### LINKED ISSUE #7217: dify and VANNA.AI
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Node Vanna.AI run failed: Failed to invoke tool: 3 validation errors for ToolInvokeMessage message.str Input should be a valid string [type=string_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/string_type    message.bytes Input should be a valid bytes [type=bytes_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/bytes_type    message.dict[any,any] Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/dict_type
4015f96d3c0eafe36661d07db905c3a
[新建 Text Document.txt](https://github.com/user-attachments/files/16595131/Text.Document.txt)

### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

_No response_

### PR DESCRIPTION
**Pull request by laipz8200**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue #7217
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #7217 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Review by crazywoola — APPROVED** [review]

**Comment by renjiarui021020** [comment]
Thank you for your help. But I made the modifications according to your code, and still got the same error.

**Comment by renjiarui021020** [comment]
639656b2882c6c172ef60be6f9fbe2d
68386e3fafdd342c9dfe17d0dedf694
I ensured that my database can be connected and the firewall was turned off.  Look forward to your help again.

**Comment by laipz8200** [comment]
@renjiarui021020 Thanks for your reply. This PR only aims to fix the type error, let's trace the problem in the issue.

**Comment by renjiarui021020** [comment]
@laipz8200 Could I possibly inquire whether there might be some minor flaws in the source code?

**Comment by renjiarui021020** [comment]
@laipz8200 Hello. I updated my version to 0.7 and the database was successfully connected, but my output value has always been none, no matter what I filled in. Could you help me take a look?

**Comment by renjiarui021020** [comment]
@laipz8200 Hello. I updated my version to 0.7 and the database was successfully connected, but my output value has always been none, no matter what I filled in. Could you help me take a look?  
1bd8f39d392328f27d31cda687bc929

**Pull request merged**
