### PR TITLE
feat: use a specific version of model config

### PR DESCRIPTION
**Pull request by wlbksy**
Make the backend API use an `app_model` specified by `app_config_model_id`, so that a specific version of the model config can be called without worrying about the config being changed afterward.

### CODE REVIEW

**Comment by crazywoola** [comment]
Please add my wechat: crazyphage I will invite you to our contributors' group

**Comment by takatost** [comment]
Thank you so much for your contribution! 😊
I have questions:

What is the purpose of this change and I'm not sure if it's appropriate to add this logic to all APIs.

**Comment by wlbksy** [comment]
> What is the purpose of this change

This is a pr towarding https://github.com/langgenius/dify/issues/2352. A studio app may have been modified several times, however sometimes we need a API call for a fixed version of configuration such that no further modification would interfere with this version.

User case: After I pushed a app, I would like provide a way for external service to call the API of this dify app, and I want to make sure that the configuration does not change even if I made some change to the app. As long as the version is given, the external service is expecting a steady response.


> I'm not sure if it's appropriate to add this logic to all APIs.

I made it default to latest configuration, so all the API would see no diff for now. However, discussions and suggestions on this are welcomed.

**Comment by takatost** [comment]
> > What is the purpose of this change
> 
> This is a pr towarding #2352. A studio app may have been modified several times, however sometimes we need a API call for a fixed version of configuration such that no further modification would interfere with this version.
> 
> User case: After I pushed a app, I would like provide a way for external service to call the API of this dify app, and I want to make sure that the configuration does not change even if I made some change to the app. As long as the version is given, the external service is expecting a steady response.
> 
> > I'm not sure if it's appropriate to add this logic to all APIs.
> 
> I made it default to latest configuration, so all the API would see no diff for now. However, discussions and suggestions on this are welcomed.

BTW, next month we will unify the design of the app version. This logic will be incompatible with the current design(by app_model_config_id). My suggestion is to keep this logic locally first, not merge it into main. When our version management goes online, we can replace it with our unified solution.

**Comment by wlbksy** [comment]
> > > What is the purpose of this change
> > 
> > 
> > This is a pr towarding #2352. A studio app may have been modified several times, however sometimes we need a API call for a fixed version of configuration such that no further modification would interfere with this version.
> > User case: After I pushed a app, I would like provide a way for external service to call the API of this dify app, and I want to make sure that the configuration does not change even if I made some change to the app. As long as the version is given, the external service is expecting a steady response.
> > > I'm not sure if it's appropriate to add this logic to all APIs.
> > 
> > 
> > I made it default to latest configuration, so all the API would see no diff for now. However, discussions and suggestions on this are welcomed.
> 
> BTW, next month we will unify the design of the app version. This logic will be incompatible with the current design(by app_model_config_id). My suggestion is to keep this logic locally first, not merge it into main. When our version management goes online, we can replace it with our unified solution.

Good to here that. Any roadmap or updates that I could get more info on this design. I'm quite keen on this feature.

**Comment by VincePotato** [comment]
Thanks for your feedback! In April, we will introduce support for app version control, which will include saving app drafts and restoring published versions. We hope this solves your problem.

**Comment by takatost** [comment]
This feature will be replaced by the forthcoming release publish management, so we're closing it here. Thanks a lot!

**Pull request closed without merging**
