### PR TITLE
feat: implement forgot password feature

### LINKED ISSUE #5307: Password Recovery Issue for Local Deployment Edition Members
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

If members of the local deployment edition have forgotten their passwords, what should they do? I can't find the "Forgot Password" option. Even after I delete a member and re-invite them, they are only redirected to the sign-in path.

I have reviewed the documentation, but I couldn't find any relevant information.

### 2. Describe the feature you'd like to see

I would like to request the addition of a Password Reset feature for users who have forgotten their login credentials in the local deployment edition, or perhaps an easier method to delete and re-invite members.

### 3. How will this feature improve your workflow or experience?

It will enhance user experience by providing a straightforward method to regain access to their accounts.

### 4. Additional context or comments

_No response_

### 5. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by xielong**
# Description

Implement forgot password feature.

Fixes #5307

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Here are some feature screenshots:
截屏2024-06-30 21 45 22

截屏2024-06-30 21 47 24

截屏2024-07-01 10 35 22

截屏2024-07-01 11 57 13

截屏2024-07-01 11 58 15

截屏2024-07-01 10 44 28

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by xielong** [comment]
Todo List

Frontend: Add a reset password link on the login page, create a reset password page
Reset Password Emails: Request email, success notification email
Reset Password Logic: Generate token, set expiration time, security checks, update password
Multilingual Support: Add multilingual support, translate all pages and email templates

**Comment by takatost** [comment]
Hey @crazywoola, could you help set up a connection? It'd be great if we can align better by chatting with our product manager and designer.

**Review by VincePotato — DISMISSED** [review]

**Review by crazywoola — DISMISSED** [review]
FE LGTM

**Review by takatost — CHANGES_REQUESTED** [review]
Nice job! 👍 Got a couple of suggestions:

1. On the login page, if the "Forgot Password" link is sent twice, both reset links can be used. It should only allow the last one to be usable.
2. If possible, add a rate limit so that password resets can only be requested a certain number of times within an hour to prevent email spam.

**Review by crazywoola — APPROVED** [review]

**Review by takatost — APPROVED** [review]
Thanks!!

**Pull request merged**
