### PR TITLE
feat: add check for key matching on decryption failure

### PR DESCRIPTION
**Pull request by shisaru292**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

When decryption fails due to a key mismatch, it should report an internal server error 500, similar to the loss of a Private Key, to allow users to quickly identify the issue, rather than providing an incorrect API Key for subsequent requests.

Related to: #10047, #9877

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by shisaru292** [comment]
The incorrect execution of `dev/reformat` led me to make two additional commits with `git push -f`. Fix a bug in #10226.

**Review by laipz8200 — COMMENTED** [review]
I believe our goal should be to fix the faulty decryption, rather than introducing slow and unnecessary checks for situations that occur very rarely.

**Comment by laipz8200** [comment]
Therefore, I will close this PR. If you have any solutions that optimize the exception messages without performing database queries, you are welcome to submit another PR.

**Comment by shisaru292** [comment]
> I believe our goal should be to fix the faulty decryption, rather than introducing slow and unnecessary checks for situations that occur very rarely.

> Therefore, I will close this PR. If you have any solutions that optimize the exception messages without performing database queries, you are welcome to submit another PR.

I understand your decision, and thank for your review. @laipz8200 

I was unable to find a way to reproduce the issue, so I didn't address the root cause: why a new private key is generated in storage for the tenant, and why the public key is not updated simultaneously. The encryption and decryption processes themselves are functioning correctly.

The private key will always be read from storage, disregarding caching, while the public key has been present in the database from the start. Due to these design of the security mechanism, the current mismatch checking solution must query the database. 😓 

I don't think it's a good approach to simply pass when a ValueError occurs after attempting to decrypt with the wrong private key, allowing users to proceed with requests using an incorrect API key without any indication of an issue. If you have any alternative solutions, please share them promptly. I'm willing to give them a try to save debugging time for other developers who encounter this problem.

**Pull request closed without merging**
