### PR TITLE
feat: rewrite Elasticsearch index and search code to achieve Elasticsearch vector and full-text search

### PR DESCRIPTION
**Pull request by KennFalcon**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by crazywoola** [comment]
Please fix the errors in CI

**Comment by KennFalcon** [comment]
I think there is a problem with the ES volume mount in the docker-compose.yml file, which is causing the ES containers in the workflow process to go down. So I changed the mounting method of the ES data directory to opensearch.

**Comment by KennFalcon** [comment]
Can retry the workflow? I can't reproduce the test issue on my own ES service. @crazywoola

**Review by JohnJyong — DISMISSED** [review]

**Comment by KennFalcon** [comment]
Still has error, I will try to fix it.

**Comment by bowenliang123** [comment]
👍🏻 Glad to have this refactoring.

**Comment by KennFalcon** [comment]
Need rollback some commit. So close the pr, and create new. #7641

**Pull request closed without merging**
