### PR TITLE
Add New Tool: DevDocs

### PR DESCRIPTION
**Pull request by richards199999**
# Description

I add a new tool for Dify - DevDocs. This tool enables the model to search for official developer documentation from DevDocs. Here is the link to their project: [Link!](https://github.com/freeCodeCamp/devdocs)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] The tool can be evoked correctly.
- [x] Since this tool doesn't require any authentication, there is no error related to this.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by crazywoola** [comment]
@richards199999 Please fix the lint error in the pr.

**Comment by bowenliang123** [comment]
@crazywoola Maybe we could automate adding the linting hints to PR comments with this action (https://github.com/marketplace/actions/add-pr-comment) when style checks fail.

**Comment by richards199999** [comment]
Sure, I have fix the error.🤗 Should be ok now. @crazywoola

**Comment by richards199999** [comment]
New fix has arrived.🤗

**Review by crazywoola — DISMISSED** [review]

**Comment by richards199999** [comment]
Fix the typo of the tool in Tool Provider.🤗 Hope there is no error anymore.

**Comment by Yeuoly** [comment]
Thanks, but I'm a little confused, I see you have written some few shots on the `llm_description` so that the model could understand which doc and topic to use such as vuex, however, there are lots of others not mentioned here, how could the model refer to those? Otherwise, user will always get 403 pages.

**Comment by richards199999** [comment]
> how could the model refer to those

well, I have tested this tool on gpt-4, gpt-3.5, claude-3, and several other model. and there is few cases that the model use wrong query. so, it's ok to just put one example, but yes, I should give two or three more. thx for advice!🤗

**Comment by richards199999** [comment]
Just update some description for llm.🫡

**Comment by Yeuoly** [comment]
Good jobs! Another suggestion: Why not adding a tooltip on human descriptions to advice developers write some few shots in system prompts so that they can build a more stable and precise app?

**Comment by richards199999** [comment]
Sure, I have rewrite some part of the YAML.🫡 @Yeuoly

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by Clubiy** [comment]
How to use it, I was uesd thouse given examples, but all return null.

**Pull request merged**
