### PR TITLE
feat: support siliconflow

### PR DESCRIPTION
**Pull request by orangeclk**
# Description

SiliconFlow is a MaaS platform. [Their documentation says](https://docs.siliconflow.cn/docs/use-siliconcloud-in-dify) they are in contact with Dify to integrate with Dify, but the example repo I see does not seem to comply with Dify's recommended approach.

That's why I made this one.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

image
image
image
image
image

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by orangeclk** [comment]
Pytest failed. However, it seems that the failure is caused by tencent hunyuan provider.

> api/core/model_runtime/model_providers/hunyuan/llm/llm.py:5: in <module>
    from tencentcloud.common import credential
E   ModuleNotFoundError: No module named 'tencentcloud'

**Comment by takatost** [comment]
> Pytest failed. However, it seems that the failure is caused by tencent hunyuan provider.
> 
> > api/core/model_runtime/model_providers/hunyuan/llm/llm.py:5: in 
> > from tencentcloud.common import credential
> > E   ModuleNotFoundError: No module named 'tencentcloud'

Fixed in #5130, you can merge from main branch.

**Review by takatost — APPROVED** [review]
LGTM

**Comment by nadirvishun** [comment]
Thanks a lot for being able to introduce it, but this one is missing the vision modeling support.

**Pull request merged**
