### PR TITLE
fix: api doc example error

### PR DESCRIPTION
**Pull request by StudyingLover**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by takatost — APPROVED** [review]
LGTM

**Comment by StudyingLover** [comment]
emmmm, I am a fresh man for this project, what should I do , because I find pytets failed

**Review by takatost — CHANGES_REQUESTED** [review]
Oops...the branch you submitted is deploy/dev, please branch out from the main branch before submitting. 👀

**Comment by takatost** [comment]
I've closed it for you, please resubmit.

**Comment by StudyingLover** [comment]
ooo! thanks, I resubmit https://github.com/langgenius/dify/pull/3925

**Pull request closed without merging**
