### PR TITLE
feat: support HTTP response compression in api server

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- Support response compression in api module on demand, if `Accept-Encoding` header in request is set to `gzip` or `br`
- content compression helps to reduce the traffic impact when the browser accessing API modules, considering ~100KB response content respond for pulling model providers, tool providers and etc, will be shrinked down to ~20KB
- The reverse proxy like nginx will bypass the content from API module if they are properly compressed avoiding repeated compression
- `flask-compress` module is used, docs and available options refer to : https://github.com/colour-science/flask-compress
- Introduce `API_COMPRESSION_ENABLED` env to control whether enable response compresson
- Compress the following MIME types by default:
  -  'application/json'
  - 'application/javascript',  
  - 'text/css'
  - 'text/html'
  - 'text/javascript'
  - 'text/xml'
- taking `/console/api/workspaces/current/model-providers` for example, transferred size gets down from 112KB to 7.6KB
image

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
This feature won't affect the SSE (server sent events) for steaming chatting API, which is in `text-stream` MIME type.

**Comment by takatost** [comment]
Hey, what's this for? I assume it's for production use, so there must be a reverse proxy like nginx on the outer layer, which comes with built-in gzip compression capability.

**Comment by bowenliang123** [comment]
It mainly benefits two scenarios, 1. deployed with source code, especially without reverse proxy by default, and 2. for debugging in the local environment, which helps to reduce e2e time cost and increase productivity.

 Considering that this feature is disabled by default, it will not have any negative impact on the main program and will not incur additional loading time for Python dependencies.

**Review by takatost — APPROVED** [review]
LGTM

**Comment by bowenliang123** [comment]
Thanks for the review and merging. 
Every time you send professional opinions and concerns on the community's PR, I have more respect and admiration for the Dify team and the community. Professionism makes it success and perfect.

**Pull request merged**
