### PR TITLE
feat: add support for smtp when send email

### PR DESCRIPTION
**Pull request by jonahcui**
虽然 resend 很好用，但是 smtp 还是要支持一下的，支持使用 smtp 发送邀请邮件

### CODE REVIEW

**Comment by crazywoola** [comment]
Please add my wechat: crazyphage, I will invite to you our developers group.

**Review by crazywoola — DISMISSED** [review]

**Review by takatost — CHANGES_REQUESTED** [review]
So here we're using `app.config.get('xxx')` to get configuration variables, but it seems like there's no logic declared in `config.py` to fetch the environment variables?

**Comment by jonahcui** [comment]
> So here we're using `app.config.get('xxx')` to get configuration variables, but it seems like there's no logic declared in `config.py` to fetch the environment variables?

Thank u, I changed the config.py and submitted it.

**Review by takatost — APPROVED** [review]
Thank you so much! 😊
BTW, would it be possible for you to help us add some explanations about these environment variables in the documentation (both in English and Chinese)? We would really appreciate it. 🙏
https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/environments.md#mail-related-configuration
https://github.com/langgenius/dify-docs/blob/main/zh_CN/getting-started/install-self-hosted/environments.md#%E9%82%AE%E4%BB%B6%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE

**Pull request merged**
