### PR TITLE
fix(openai_api_compatible): fixing the error when converting chunk to json

### PR DESCRIPTION
**Pull request by aniaan**
# Description
fixing the error when converting chunk to json

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
-1 for this.

As far as I know, the spaces at the front or the end of the string would not fail the json parsing.
Any further explanation or evidence for the issue you're fixing?

**Comment by aniaan** [comment]
chunk is not always a space. In some cases, it may be `\r`. When `chunk='\r'`, an error will occur when executing the corresponding code.

This is the minimal simple reproducing case.
```python
import json

chunk = '\r'
decoded_chunk = chunk.strip().lstrip('data: ').lstrip()
chunk_json = json.loads(decoded_chunk)
```
provide more explanation as to why sometimes the chunk will be `\r`. The reason is actually because the default delimiter for `dify` is `\n\n`, but I am using the library `LLaMA-Factory`, which uses the delimiter `\r\n`. When I first used `dify`, I configured it according to its default value `\n\n`, but there was no corresponding response from `dify` (actually, the program code has already thrown an error, but there was also a lack of logs), which made debugging difficult for me. So, I had to try changing some delimiters and added some code logs. When I tried using '\n' as the delimiter, although there were still errors, they could be resolved by adding one line of code `chunk=chunk.strip()`. That's why this pr exists.

There is no problem with using OpenAI's SDK by default to call `LLaMA-Factory`, so initially it made me suspect that the issue was with `dify`.

Regarding the use of `\r\n` in `LLaMA-Factory`, I discovered this today when looking at the underlying dependency library code. If we had known from the beginning that it uses `\r\n`, maybe we wouldn't have encountered this issue.


As for this specific problem, personally, I think this line of code may still be meaningful as it adds robustness to the program. However, ultimately it depends on your opinion.

ps:

Some key error locations in the code may still benefit from adding some logs, for example.

https://github.com/langgenius/dify/blob/80e390b906b848eae41e185c97acb83fd22cc4fa/api/core/model_runtime/model_providers/openai_api_compatible/llm/llm.py#L437-L443

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by bowenliang123** [comment]
Thanks for the explanation. SGTM.

**Pull request merged**
