### PR TITLE
fix: bypass admin users to use dataset api with API key

### PR DESCRIPTION
**Pull request by bowenliang123**
- Before: only owner users successfully use datasetapi, for the admin users, it failes with `Unauthorized("Tenant is not exist.")`
- After: both owner and admin users passes

### CODE REVIEW

**Comment by JohnJyong** [comment]
The logic here is only used to obtain owner information, not to verify permissions. @bowenliang123

**Comment by bowenliang123** [comment]
> The logic here is only used to obtain owner information, not to verify permissions. @bowenliang123

Yes, but without this change, the request by admin users will fall to the failure "Unauthorized("Tenant is not exist.")".

**Review by crazywoola — APPROVED** [review]

**Comment by takatost** [comment]
Just a reminder: 
Currently, the knowledge base API key is not tied to individual account identity. So, when you make calls to the knowledge base API, you'll be using the workspace owner's identity.

**Comment by bowenliang123** [comment]
OK. How about changing the word from `allow` to `bypass` in the title?

**Review by takatost — APPROVED** [review]

**Comment by bowenliang123** [comment]
Updated the title and description, if you check.

**Pull request merged**
