### PR TITLE
dep: support for Python 3.12

### PR DESCRIPTION
**Pull request by bowenliang123**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- update `gmpy2` to 2.2.0+, which is a release with support for Cpython 3.12 and 3.13, which is built and tested on multiple OS(including ubuntu-22.04, macos-12, macos-14, windows-2022) https://github.com/aleaxit/gmpy/releases/tag/gmpy2_2_2_0
- update `grpcio` >= 1.59.0 for Python 3.12 support
  - Python 3.12 support since 1.59.0 : https://github.com/grpc/grpc/releases/tag/v1.59.0
- run api tests on Python 3.12

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [x] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @takatost @JohnJyong

**Review by crazywoola — DISMISSED** [review]

**Comment by takatost** [comment]
@Yeuoly Pls make sure that the dependencies on gmpy2 are functioning correctly.
@JohnJyong Pls make sure that the dependencies on grpcio are functioning correctly.

**Review by Yeuoly — DISMISSED** [review]
LGTM

**Review by crazywoola — DISMISSED** [review]

**Comment by bowenliang123** [comment]
Conflicts resolved. cc @crazywoola

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
