### PR TITLE
fix: properly respond when no tenant linked to current account

### PR DESCRIPTION
**Pull request by MatriQ**
Fix 500 response when no tenant is linked to the current account.

### CODE REVIEW

**Review by takatost — CHANGES_REQUESTED** [review]
This idea seems off. There shouldn't be a situation where `current_tenant` is `None`. That would be considered dirty data.
btw, when do you usually encounter this issue?

**Comment by MatriQ** [comment]
> This idea seems off. There shouldn't be a situation where `current_tenant` is `None`. That would be considered dirty data.
> btw, when do you usually encounter this issue?

You can reproduce the corresponding issue with the following steps:
1.  Invite a new user: xxx@xxx.com.
2.  Signup with xxx@xxx.com.
3.  Remove xxx@xxx.com from your workspace.
4.  Then you can reproduce it with login xxx@xxx.com.

I also considered creating a tenant and setting it as the default workspace if a user just removed it from all tenants, but it shouldn't have happened in the SELF_HOSTED mode, right?

However, I think these changes can make the code to be more strong.

**Comment by takatost** [comment]
Maybe the problem lies in the logic of retrieving the team/tenant after logging in: api.app.load_user.
According to the normal logic:

If a user logs in and the team corresponding to the workspace_id retrieved from the session does not exist, they should switch to their own team.
If a user does not belong to any team and is in a detached state, they should register a team of their own.
What do you think? 😊

**Comment by MatriQ** [comment]
> > This idea seems off. There shouldn't be a situation where `current_tenant` is `None`. That would be considered dirty data.
> > btw, when do you usually encounter this issue?
> 
> You can reproduce the corresponding issue with the following steps:
> 
> 1. Invite a new user: [xxx@xxx.com](mailto:xxx@xxx.com).
> 2. Signup with [xxx@xxx.com](mailto:xxx@xxx.com).
> 3. Remove [xxx@xxx.com](mailto:xxx@xxx.com) from your workspace.
> 4. Then you can reproduce it with login [xxx@xxx.com](mailto:xxx@xxx.com).
> 
> I also considered creating a tenant and setting it as the default workspace if a user just removed it from all tenants, but it shouldn't have happened in the SELF_HOSTED mode, right?
> 
> However, I think these changes can make the code to be more strong.

It's a good idea. but I still think this PR is necessary, else the issue still can be triggered when the user xxx@xxx.com never sign out.

BTW, Can it have more tenants in `SELF_HOSTED` mode?

**Comment by takatost** [comment]
Indeed, your code can avoid some issues, but these interfaces are not all. There are still many interfaces that need to query the current user's workspace. It may increase in the future.

What I mean is, if we fix this logic vulnerability at `@login_manager.user_loader`, then these interfaces will not have a situation where `current_user.current_tenant` is empty when retrieving it.

As I mentioned above, if the user's workspace does not exist, switch to an existing workspace. If there is no workspace at all, create a workspace with the owner being the current user.

**Comment by MatriQ** [comment]
> Indeed, your code can avoid some issues, but these interfaces are not all. There are still many interfaces that need to query the current user's workspace. It may increase in the future.
> 
> What I mean is, if we fix this logic vulnerability at `@login_manager.user_loader`, then these interfaces will not have a situation where `current_user.current_tenant` is empty when retrieving it.
> 
> As I mentioned above, if the user's workspace does not exist, switch to an existing workspace. If there is no workspace at all, create a workspace with the owner being the current user.

It's a simpler and more useful approach. I can implement it here, and if it works I'll remove these redundant changes.

**Comment by MatriQ** [comment]
The `workspace_id ` will be incorrect if the user does not re-signin in this case.

**Comment by takatost** [comment]
Or log out before returning None.
```
flask.session.pop('workspace_id', None)
flask_login.logout_user()
```

**Comment by MatriQ** [comment]
I created a new [PR]( https://github.com/langgenius/dify/pull/793) instead of this.

**Pull request closed without merging**
