### PR TITLE
Make max_submit_count configurable via Config

### LINKED ISSUE #11668: Iteration node with input array length>100 always fails saying 'Max submit count 100 of workflow thread pool reached'
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

The error 'ValueError: Max submit count 100 of workflow thread pool reached' easily happens if input to the iteration node is long to some extent. 

Example condition:
 - iteration node has parallel mode with maximum parallelism>= 2
 - input to the iteration node >=101
 - run the workflow, then terminates with error saying Max submit count 100 of workflow thread pool reached.
 
Please see captures.
image
image
image

This never happens for single thread mode.

Although I am not sure the role of max_submit_count, this behavior is obviously wired and should be enhanced so that all the thread is created simultaneously.

Attached is the very easy sample workflow.
[workflow.zip](https://github.com/user-attachments/files/18139742/workflow.zip)

### ✔️ Expected Behavior

Workflows should be successful even if input length is large.

### ❌ Actual Behavior

Input length to iteration node with parallel mode fails 100%.

### PR DESCRIPTION
**Pull request by kazuhisa-wada**
# Summary

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Mage max_submit_count configurable via Config. This is the action closes #11668

# Screenshots

**Before**
please see  screenshots in #11668 

**After**
image
image
image
image 

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

For test code, I haven't added any test code for this as this change is limited to parameter related to limits.
For document, there is no document to be changed.
For dev/reformat, I ran it as follows:
image

### CODE REVIEW

**Comment by crazywoola** [comment]
Please fix the lint :)

**Comment by yihong0618** [comment]
1. seems you need to check ruff version
2. maybe we can add the config to .env too?

**Comment by kazuhisa-wada** [comment]
Apologies. Let me do.

**Comment by yihong0618** [comment]
> 2\. ybe we can add the config to .en

ruff version print in the actions

**Comment by kazuhisa-wada** [comment]
> maybe we can add the config to .env too?

Sorry, I missed this mention. Adding .env.example....

**Comment by kazuhisa-wada** [comment]
I've completed adding it to .env.example.

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
