### PR TITLE
fix localai,baichuan agent chat err #4943

### LINKED ISSUE #4943: Baichuan conversation error
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

屏幕截图 2024-06-05 112652

When the Baichuan model uses tools, errors may occur during the conversation.

### ✔️ Expected Behavior

Answer questions and dialogues normally.

### ❌ Actual Behavior

Unknown message type <class 'core.model_runtime.entities.message_entities.ToolPromptMessage'>

### PR DESCRIPTION
**Pull request by huixiangyang**
# Description

fix localai,baichuan agent chat err `Unknown message type <class 'core.model_runtime.entities.message_entities.ToolPromptMessage'>`

Fixes #4943 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by laipz8200 — DISMISSED** [review]
@takatost It looks like some of the models from baichuan were supporting tool-call. Should we consider adding this feature to the model configuration?

**Comment by crazywoola** [comment]
Please fix the errors in CI

**Review by laipz8200 — DISMISSED** [review]

**Comment by yanghx-git** [comment]
不好意思，我不知道该怎么调整代码样式。提交代码时会自动格式化，能不能帮我调整下，麻烦了

**Comment by laipz8200** [comment]
> 不好意思，我不知道该怎么调整代码样式。提交代码时会自动格式化，能不能帮我调整下，麻烦了

Sure, I'll take care of it. Thanks for your contribution.

By the way, you can simply run the 'dev/reformat' script in your next contribution.

**Review by laipz8200 — APPROVED** [review]

**Pull request merged**
