### PR TITLE
[feat] Add AWS Bedrock rerank

### PR DESCRIPTION
**Pull request by warren830**
# Summary

This pr adds AWS Bedrock rerank.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

we can choose rerank model:
image

And here we can successfully retrieve documents:
image

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — DISMISSED** [review]

**Comment by crazywoola** [comment]
cc @Yeuoly @laipz8200

**Comment by warren830** [comment]
@crazywoola sorry, can you approve again

**Comment by crazywoola** [comment]
Still failed to pass the lint.

**Comment by warren830** [comment]
Sorry man@crazywoola , this time I used ruff to make sure:
image

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
