### PR TITLE
fix: delete tool parameters cache when sync draft workflow for run workflow use new parameter change in draft workflow 

### PR DESCRIPTION
**Pull request by gaoxin-pen**
# Description
在更新draft workflow时增加了删除工具的参数缓存逻辑，不然在实际使用中出现了无法使用最新参数而是使用缓存参数的问题，comments中给出了具体问题截图

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by gaoxin-pen** [comment]
fix the problem like:
1. I change the tool parameter in workflow:
flDCjAd0ux

2. I run the workflow:
ZO8t7Kg1o6

3. the workflow use parameter in cache not the lastest change in draft workflow
(the https://xxxxx is a value in cache)

**Review by Yeuoly — DISMISSED** [review]
LGTM

**Comment by Yeuoly** [comment]
Thx!

**Comment by Yeuoly** [comment]
Pls fix the CI error.

**Comment by gaoxin-pen** [comment]
hello, @Yeuoly already fix the lint error ,thank you review again

**Review by Yeuoly — APPROVED** [review]
LGTM

**Pull request merged**
