### PR TITLE
Feat: add OneBot protocol tool

### PR DESCRIPTION
**Pull request by RockChinQ**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

OneBot is a protocol in IM bot ecology, and be widely used in many protocol ends or applications. With this tool, workflow can send message to IM such as QQ, WeChat, Telegram.

- Intro: [OneBot v11](https://github.com/botuniverse/onebot-11)
- Ecology: [ecosystem](https://onebot.dev/ecosystem)

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Deploy a protocol end (can be found in the ecology page) , enable http port, and fill the `ob11_http_url` in tool credentials, then use it in flow.

## Sending Text to Person

94065dd41b8a78375cd864015933fd41

image

## Sending Image to Group

8a879c0058beb2e690737c17425ca3bd
image

### CODE REVIEW

**Review by Yeuoly — APPROVED** [review]
lgtm

**Comment by yst-one** [comment]
大佬有问题啊 我postman没问题这个插件报错  {
  "text": "",
  "files": [],
  "json": [
    {
      "error": "Failed to send private message: No connection adapters were found for '10.10.115.211:3000/send_private_msg'"
    }
  ]
}

**Comment by RockChinQ** [comment]
> 大佬有问题啊 我postman没问题这个插件报错  {
>   "text": "",
>   "files": [],
>   "json": [
>     {
>       "error": "Failed to send private message: No connection adapters were found for '10.10.115.211:3000/send_private_msg'"
>     }
>   ]
> }

你是自部署吗

**Comment by yst-one** [comment]
> > 大佬有问题啊 我postman没问题这个插件报错 { “text”： “”， “files”： []， “json”： [ { “error”： “发送私人消息失败：未找到'10.10.115.211：3000/send_private_msg'的连接适配器”
> > }
> > ]
> > }
> 
> 你是自部署吗
是的

**Comment by yst-one** [comment]
dify 10.10.115.215  onebot 是 10.10.115.211 ，postman 没问题。还有一个问题就是我第一次设置好了onebot的地址，后面怎么没看到改地址的地方了

**Comment by RockChinQ** [comment]
@yst-one 自部署情况下，需要让dify容器和你的onebot实例处于同一网络下，再从onebot工具指定ob实例的容器作为访问地址。

**Comment by yst-one** [comment]
@RockChinQ 意思是要在同一个ip 同一个机器上对吗 ？要用127.0.0.1？

**Comment by RockChinQ** [comment]
@yst-one 网络问题比较复杂，自行解决一下哈

**Comment by yst-one** [comment]
@RockChinQ 现在就是在简单的同一个局域网下的，

**Comment by yst-one** [comment]
@RockChinQ 我在同一台机器上测试都不可以，发现插件没有把消息发出来，因为我的
image
image

根本没输出日志

**Pull request merged**
