### PR TITLE
feat : add evaluation code for code generator

### PR DESCRIPTION
**Pull request by Kota-Yamaguchi**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

In this PR, I have created the code to run evaluations for the Code Generator. This PR only includes the code to perform the evaluation, with minimal test cases added, and no actual evaluation has been conducted. These aspects will be addressed in a separate PR.

## Background for Adding Evaluation of Code Generator

I want to avoid users choosing not to use the CodeGenerator simply because they’re uncertain about the quality of the generated code. 
By evaluating accuracy as part of the product, I believe we can create a reliable standard that users can trust.

Additionally,  in the future, I want to allow users to freely choose the LLM specifically for the code generator without needing to change the entire system model. There are several reasons for this. A search on platform X shows that some users are still using GPT-3.5 in dify, while others set their system model to GPT-4o-mini to reduce costs. It’s cumbersome for these users to change system settings every time they need a different model just for code generation. Dify is very convenient, so I want to avoid this inconvenience in only this aspect.

Therefore, I aim to enable model selection specifically within the code generator, regardless of the main system model. For this purpose, I want to establish evaluation criteria to determine the best LLM to use for creating code tailored for Dify. That’s why I'm setting up the evaluation process now.

## Requirements for Evaluation
The following will be provided:

- Instructions
- Target language
- Necessary input arguments for the generated code to produce the desired result
- Ground Truth

## Environment for Evaluation
Code execution will take place in the Dify-Sandbox.
Code generation will be performed via the Code Generator API. 
The evaluation itself will be conducted using Golang code.

The reason for choosing Go is to package everything into a single binary, making it easy for anyone to run anywhere.
I included a single binary to allow anyone to run it quickly in any environment, but would it be better to remove it?

## Evaluation Method
The evaluation simply checks whether the output from executing the generated code matches the expected result.

Currently, I am considering presenting the accuracy results categorized by "model" and "task complexity level." 
**This will be addressed in a separate PR.**

## Test Cases
**Test cases will be added in a separate PR.**

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

スクリーンショット 2024-11-10 22 33 31

### CODE REVIEW

**Comment by Kota-Yamaguchi** [comment]
@crazywoolala 
Apologies if I’ve made a mistake in choosing the right person to request a review. Could you please review this for me? 
Also, does the Dify team currently consider it unnecessary to include evaluations for the CodeGenerator in Dify?

**Comment by Kota-Yamaguchi** [comment]
@crazywoola 
Apologies if I’ve made a mistake in choosing the right person to request a review. Could you please review this for me? Also, does the Dify team currently consider it unnecessary to include evaluations for the CodeGenerator in Dify?

**Comment by Kota-Yamaguchi** [comment]
Thanks for your response！！！

**Comment by laipz8200** [comment]
Thank you for your thoughtful contribution.

This evaluation seems to be focused on the LLM's capabilities, and I think it might be more suitable to place it in a repository outside of dify.

However, allowing the specification of the model during code generation sounds like a great idea.

**Comment by Kota-Yamaguchi** [comment]
@laipz8200 
Thank you for the review!
I’m planning to put this in a repository somewhere. Do you think it would be better to place it in my personal repository, or should it go under the Langgeinus organization? I’ll mainly use it to improve the CodeGenerator, so either option works for me.

> However, allowing the specification of the model during code generation sounds like a great idea.
Thank you! I’ll submit a PR for this somewhere as well!

**Comment by laipz8200** [comment]
> Do you think it would be better to place it in my personal repository, or should it go under the Langgeinus organization?

This is your work, and it should be stored in your repository. Please let me know once you’ve set up the repository!

**Comment by Kota-Yamaguchi** [comment]
Thank you! I've created the repository!
https://github.com/Kota-Yamaguchi/dify-codegenerator-evaluator

**Comment by laipz8200** [comment]
Thank you, our team will review your repository. You can now close this PR.

**Comment by Kota-Yamaguchi** [comment]
Okay, I'll close this PR!

**Pull request closed without merging**
