### PR TITLE
feat(llm/models): add gemini-1.5-pro

### PR DESCRIPTION
**Pull request by lroolle**
# Description

Add model Gemini 1.5 Pro.

- Documentation available at: [Google AI Docs/models/gemini](https://ai.google.dev/models/gemini).

## Type of Change

- [x] New feature (adds functionality)

### Screenshots

Screenshot 2024-04-10 at 14 15 48

Screenshot 2024-04-10 at 14 16 05

Screenshot 2024-04-10 at 14 16 55

Screenshot 2024-04-10 at 14 36 48

# How Has This Been Tested?

- [x] Manually in local development environment.

### CODE REVIEW

**Comment by Yeuoly** [comment]
Hello, thanks for contributing, but for a further test, I would like to know to get an API key supports Gemini Pro 1.5, or should I change to another API endpoint? I got an error below. It seems that Gemini Pro 1.5 is not supported by this API endpoint yet.

image

**Comment by lroolle** [comment]
> Hello, thanks for contributing, but for a further test, I would like to know to get an API key supports Gemini Pro 1.5, or should I change to another API endpoint? I got an error below. It seems that Gemini Pro 1.5 is not supported by this API endpoint yet.

API support for Gemini Pro 1.5 is currently being phased in. 

image

**Comment by Yeuoly** [comment]
hello, have you successfully tested invoke the model once? if so, could you pls add my WeChat: Yeuoly

**Comment by lroolle** [comment]
> hello, have you successfully tested invoke the model once? if so, could you pls add my WeChat: Yeuoly

Not yet, I've converted this PR to draft due to the current state of the`gemini-1.5-pro` API.

**Comment by lroolle** [comment]
@Yeuoly has been updated and tested.

**Review by takatost — APPROVED** [review]
LGTM

**Review by Yeuoly — APPROVED** [review]
LGTM

**Pull request merged**
