### PR TITLE
feat: Add Vanna.AI as a builtin tool

### LINKED ISSUE #4877: Integration of Vanna.AI for Text-to-SQL Feature in Dify
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

Yes, I am looking for a way to automate SQL writing and running in Dify.

### 2. Describe the feature you'd like to see

I would like to see an integration of Vanna.AI into Dify. Specifically, I am interested in a feature where I can input text and have Vanna.AI generate SQL queries for me.

### 3. How will this feature improve your workflow or experience?

This feature would significantly speed up the process of extracting insights from my database. Instead of manually writing SQL queries, I could simply ask questions in natural language and have Vanna.AI generate the queries for me.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by luxmus**
# Description

Close [#4877](https://github.com/langgenius/dify/issues/4877)

Add Vanna.AI as a builtin tool

This feature would significantly speed up the process of extracting insights from my database. Instead of manually writing SQL queries, just simply ask questions in natural language and have Vanna.AI generate the SQL for you.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [X] Dependency upgrade

# How Has This Been Tested?
截屏2024-06-03 11 09 48
截屏2024-06-03 11 10 41

- [ ] TODO
none

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Yeuoly** [comment]
LGTM

**Review by Yeuoly — APPROVED** [review]

**Comment by Yeuoly** [comment]
btw, would you mind write a more detailed document about how to use it and submit a PR to https://github.com/langgenius/dify-docs like StableDiffusion

**Comment by LucisBaoshg** [comment]
One suggestion, I hope this feature can support training parameter passing. If it can be supported, this tool can be used not only for database query, but also for training

image

**Comment by crazywoola** [comment]
Hello @luxmus it seems there is something wrong with parameter validations here https://github.com/langgenius/dify/issues/7217

**Comment by renjiarui021020** [comment]
Thank you for your help, but I carefully read the article and did not find any mistakes on my part

**Comment by renjiarui021020** [comment]
> Hello @luxmus it seems there is something wrong with parameter validations here #7217

Could you please help me take a look when you have time, sir? Thank you very much

**Pull request merged**
