### PR TITLE
fix: issue #10596 by making the iteration node outputs right

### PR DESCRIPTION
**Pull request by yihong0618**
# Summary

fix: issue #10596 by making iteration node outputs right

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

<table>
  <tr>
  <td>Before: </td>
  <td>After: </td>
  </tr>
  <tr>
  <td>...</td>
  <td>...</td>
  </tr>
</table>

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by laipz8200** [comment]
This issue occurs by the Iteration node, let's fix it in the Iteration node.

**Review by laipz8200 — DISMISSED** [review]

**Comment by laipz8200** [comment]
The tests seem to be stuck in an infinite loop, will check it later

**Comment by yihong0618** [comment]
> The tests seem to be stuck in an infinite loop, will check it later

nice tests to avoid this~

**Review by laipz8200 — APPROVED** [review]
A huge thanks to you!

**Pull request merged**
