### PR TITLE
Feat/customizable file upload config

### PR DESCRIPTION
**Pull request by MatriQ**
* Move `UPLOAD_FILE_SIZE_LIMIT` and `UPLOAD_FILE_BATCH_LIMIT` into env
* Refactor file type file upload  in frontend

image

### CODE REVIEW

**Review by takatost — APPROVED** [review]
thx!

**Comment by shaxiaozz** [comment]
I added these two environment variables, UPLOAD_FILE_SIZE_LIMIT and UPLOAD_FILE_BATCH_LIMIT, under langgenius/dify-api container orchestration in docker-compose.yaml as follows:
```
version: '3.1'
services:
  # API service
  api:
    image: langgenius/dify-api:0.3.17
    restart: always
    environment:
      # Startup mode, 'api' starts the API server.
      MODE: api
      # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
      LOG_LEVEL: INFO
      UPLOAD_FILE_SIZE_LIMIT: 150
```
And re-execute: "docker-compose up -d", found that the upload file size limit is still 15M

**Comment by MatriQ** [comment]
> I added these two environment variables, UPLOAD_FILE_SIZE_LIMIT and UPLOAD_FILE_BATCH_LIMIT, under langgenius/dify-api container orchestration in docker-compose.yaml as follows:
> 
> ```
> version: '3.1'
> services:
>   # API service
>   api:
>     image: langgenius/dify-api:0.3.17
>     restart: always
>     environment:
>       # Startup mode, 'api' starts the API server.
>       MODE: api
>       # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
>       LOG_LEVEL: INFO
>       UPLOAD_FILE_SIZE_LIMIT: 150
> ```
> 
> And re-execute: "docker-compose up -d", found that the upload file size limit is still 15M

Weird, It works in my k8s.

**Comment by shaxiaozz** [comment]
@MatriQ 
I am also very surprised that the increase of environment variables still cannot lift the 15M file size limit. I don't know if there is a problem with my configuration

**Comment by shaxiaozz** [comment]
@MatriQ 
Should variables be added to this container: "langgenius/dify-api:0.3.17"

**Comment by MatriQ** [comment]
> I am also very surprised that the increase of environment variables still cannot lift the 15M file size limit. I don't know if there is a problem with my configuration

I think it should be working for 0.3.17. Have you ever entered the container to check the env value?

**Comment by shaxiaozz** [comment]
@MatriQ I'm very sorry, but my mirror is still using 0.3.14. I replaced it with 0.3.18 to be able to change the file max, thanks~

**Pull request merged**
