### PR TITLE
fix issues #10055

### LINKED ISSUE #10055: Add an environment variable for developers to choose whether to update the inputs value in the same conversation
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

In a multi-round conversation, the current design of dify is that when the user passes the conversation_id parameter to the interface, the value of inputs can only be the value of inputs when the conversation is created. 
Can a switch be made or an environment variable be designed so that developers can choose whether to update the value of inputs in the same conversation? 
sometimes custom variables need to be updated in in actual use, such as some parameters of the environment, but currently if I want to update the inputs, I can only create a new conversation.

### 2. Additional context or comments

image

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by liuhaoran1212**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

fix the following issues: In a multi-round conversation, the current design of dify is that when the user passes the conversation_id parameter to the interface, the value of inputs can only be the value of inputs when the conversation is created.

Fixes #10055 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by crazywoola** [comment]
See this as well https://github.com/langgenius/dify/pull/7955

**Comment by liuzixiao666** [comment]
Does this version take effect on 0.11.0？

**Comment by liuzixiao666** [comment]
> Does this version take effect on 0.11.0？

It didn't take effect, I just tried it

**Comment by crazywoola** [comment]
> > Does this version take effect on 0.11.0？
> 
> It didn't take effect, I just tried it

No I mean, this is still under discussion, we haven't decided it yet.

**Pull request closed without merging**
