### PR TITLE
:wrench: Add env variable for time signature

### PR DESCRIPTION
**Pull request by patryk20120**
# Description

Adding the env variable to specify hard coded signature time on files.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Locally with docker build and the rest of the system on 0.6.8

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
`FILES_ACCESS_TIMEOUT` may be a better name for the env variable than `FILES_ACCESS_TIME`.

**Comment by patryk20120** [comment]
> `FILES_ACCESS_TIMEOUT` may be a better name for the env variable than `FILES_ACCESS_TIME`.

Sure, why not.

**Review by bowenliang123 — APPROVED** [review]
LGTM overall.

**Review by takatost — APPROVED** [review]
LGTM

**Pull request merged**
