### PR TITLE
add new provider Solar

### LINKED ISSUE #6219: Integration of Upstage Layout Analysis as an LLM Provider in Dify
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Is this request related to a challenge you are facing?
Currently, to use the Upstage API with Dify, I need to write custom clients. This process can be time-consuming and may limit the number of projects that can choose Dify.

What is the feature you'd like to see?
I propose the integration of Upstage as another LLM provider in Dify, similar to OpenAI and Mistral. Upstage is a leading LLM provider in the APAC region and its inclusion in Dify would cater to a wider user base.

How will this feature improve your workflow / experience?
The integration of Upstage Layout Analysis would make Dify more versatile and attractive for a wider range of projects, especially those already using Upstage. This would potentially increase the number of projects choosing Dify.

Additional Context or Comments
For more information about Upstage APIs, please refer to the following resources:

[Introducing Layout Analysis](https://en.content.upstage.ai/blog/business/introducing-layout-analysis)
[Solar LLM](https://www.upstage.ai/solar-llm)
Can you help with this feature?
Yes, I have experience integrating Upstage APIs in Langchain and Llama Index and am willing to contribute to the development of this feature.

Thank you for considering this feature suggestion. I believe that the integration of Upstage as an LLM provider will significantly enhance Dify's capabilities and appeal to a wider range of users.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by JuHyung-Son**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

close #6219

Added Solar to the Model provider. Solar is an LLM that has many users in Korea and Japan. We have received many requests from Korean users to integrate solar into dify, so we are making this PR.

This PR includes the Solar LLM and Embedding.

I'm also thinking about integrating Layout Analysis (already mentioned a few times in discord), which is developed by Solar developer upstage and has an overwhelming performance in parsing pdf, html, etc. Many customers are already using layout analysis in Korea and Japan.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

I`ve tested on local deployment environment.
I didn't find it, but maybe there is a test for individual model providers?

### CODE REVIEW

**Comment by crazywoola** [comment]
Please add the tests to this provider as well :) Thanks.

**Comment by JuHyung-Son** [comment]
@crazywoola Thanks, I added model provider tests

**Comment by JuHyung-Son** [comment]
lint fixed

**Review by crazywoola — APPROVED** [review]

**Comment by JuHyung-Son** [comment]
@crazywoola 

I'm also thinking about integrating Layout Analysis (already mentioned a few times in discord), which is developed by Solar developer upstage and has an overwhelming performance in parsing pdf, html, etc. Many customers are already using layout analysis in Korea and Japan. Do you agree to implement this and put it in?

**Pull request merged**
