### PR TITLE
FIX: Retrieval top n bug

### LINKED ISSUE #11068: The Rerank model in RAG needs to support independent score_threshold and top_k
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Currently, the retrieval model and the re-ranking stage share the score_threshold and top_k parameters, which currently have the following problems:
1. The retrieval model and the re-ranking model have different score distributions and need to use different thresholds, which cannot be supported under the current solution;
2. In order to ensure the integrity of the information, as much text as possible is generally recalled during the retrieval stage, and compressed to a relatively small number after the re-ranking is completed to match the input context of the large model. Currently, when top_k is shared, if top_k is set too small, the retrieval stage cannot recall enough content, affecting the recall rate, or if top_k is set too large, it exceeds the context of the large model;

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #11300: knowledge error  RETRIEVAL_TOP_N
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、hitTesting
2、input content to test
3、show error

### ✔️ Expected Behavior

show embedding content

### ❌ Actual Behavior

image
image

### PR DESCRIPTION
**Pull request by ProseGuys**
# Summary

Sorry, I made a stupid mistake and caused a bad impact on your, this is  the revised submission

Close #11300 
Close #11068 

# Screenshots

<table>
  <tr>
  <td>Before: </td>
  <td>After: </td>
  </tr>
  <tr>
  <td>...</td>
  <td>...</td>
  </tr>
</table>

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by laipz8200** [comment]
Actually, I think we should find a better way to implement this feature.

In the implementation of this PR, if we set the environment variable, the settings we set in the web view will not work.

**Comment by nadirvishun** [comment]
> Actually, I think we should find a better way to implement this feature.
> 
> In the implementation of this PR, if we set the environment variable, the settings we set in the web view will not work.

I think this design would be better：
image

**Comment by ProseGuys** [comment]
> > Actually, I think we should find a better way to implement this feature.
> > In the implementation of this PR, if we set the environment variable, the settings we set in the web view will not work.
> 
> I think this design would be better： image
I agree with your point of setting on the page side, but there seems to be a problem with the design in the picture. If I choose the other two retrieval methods besides hybrid retrieval, top_n and top_k seem to be unable to be set.

**Comment by ProseGuys** [comment]
> Actually, I think we should find a better way to implement this feature.
> 
> In the implementation of this PR, if we set the environment variable, the settings we set in the web view will not work.

First of all, I apologize to your team for my mistake, but this temporary solution seems to work in my project, and I also agree with @nadirvishun ‘s opinion of view. Does diffy have any plans to introduce the top_n parameter on the page side?

**Comment by laipz8200** [comment]
I've pinged our team to review this feature request, let's discuss #11068.

**Pull request closed without merging**
