### PR TITLE
Added tools for Azure Bing Search API v7

### PR DESCRIPTION
**Pull request by keita69**
# Description
Created tools for Azure Bing Search API v7.

## Related Motivation and Background
I created this tool because I didn't want to call external services from Dify on Azure. (I don't want to use external services such as SerpAPI for security reasons)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

# How was this tested?
I used a tool added locally (WSL) and confirmed its operation with a chat flow.

- [ ] Tool certification
- [ ] Change the settings of each tool parameter randomly and check the operation (not all patterns have been tried)

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by crazywoola** [comment]
Please fix the errors in ci

**Comment by keita69** [comment]
@crazywoola 
Fixed the errors in ci

**Comment by laipz8200** [comment]
Our Bing search tool uses the same URL and supports custom. What's the difference between those two tools?

**Comment by sawada-fjadk** [comment]
@laipz8200 
sorry. . . .Same functionality.
Please close this pull request.

I mistakenly thought that the Bing Search tool you provided was a tool that called Serpapi's Bing Search.
(https://serpapi.com/bing-search-api)

However, the Bing Search tool you guys provide is not authenticated in my Azure environment.
I'll look into it separately from this pull request.


1. Azure Bing Search
image
2. Bing Search Tool
image
3. Set Up Authorization ※ This key is no longer available.
 image
4. Error Message
image

**Pull request closed without merging**
