### PR TITLE
feat: add French fr-FR

### PR DESCRIPTION
**Pull request by lmagnien**
# Description

Add french language

Fixes # (issue)

## Type of Change

[X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

build and explore the app in french locally

### CODE REVIEW

**Comment by lmagnien** [comment]
Hello, I wanted to discuss this pull request in the discord channel but the invite link in the readme.md is expired or broken. 
I bootstraped the translation with GPT4 and did a quick review. I plan to review the text with others native french speaker in the near future.

**Review by crazywoola — APPROVED** [review]

**Comment by crazywoola** [comment]
Thank you very much for the contribution. :)

**Comment by lmagnien** [comment]
You're welcome. Here is the script I used to start the translation : 

https://gist.github.com/lmagnien/6ec35013a7194bd590cb0dd24f0ee409

It could be adapt for other languages.

**Comment by crazywoola** [comment]
Please head to https://discord.com/channels/1082486657678311454/1180843562829615174 if you are interested. :)

**Pull request merged**
