### PR TITLE
feat: support tencent cos storage

### PR DESCRIPTION
**Pull request by quicksandznzn**
# Description

Support tencent cos storage 

add cos-python-sdk-v5==1.9.30

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?
```
TENCENT_COS_BUCKET_NAME=dify
TENCENT_COS_SECRET_KEY=secret-key
TENCENT_COS_SECRET_ID=secret-id
TENCENT_COS_REGION=ap-beijing
TENCENT_COS_SCHEME=https

```

image

image

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JohnJyong** [comment]
@quicksandznzn pls add the tecent cos env setting to the `docker-compose.yaml` file , thanks

**Comment by quicksandznzn** [comment]
> @quicksandznzn pls add the tecent cos env setting to the `docker-compose.yaml` file , thanks

done~

**Review by ghost — APPROVED** [review]
Fix for me

**Review by ghost — APPROVED** [review]

**Comment by JohnJyong** [comment]
something wrong with Pytest

**Review by JohnJyong — APPROVED** [review]

**Pull request merged**
