### PR TITLE
Update docker-compose files version

### PR DESCRIPTION
**Pull request by Kennytian**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

```
WARN[0000] /root/dify/docker/docker-compose.yaml: `version` is obsolete
```

This update resolved a WARN, please accept it.

## Type of Change
- [x] Improvement，including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?
- [x] Manual Test

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Kennytian** [comment]
Here is my Docker and Docker Compose version:

```
Docker version 25.0.5, build 5dc9bcc
Docker Compose version v2.25.0
```

**Comment by bowenliang123** [comment]
Furthermore, why `3` is better than `3.1` while the latter one is warned as obsolete one. Any Docker's official docs for supported value for the version field?

**Comment by takatost** [comment]
My understanding of this warn is that the version has already been deprecated, docker compose is backward compatible. I think we can delete this version, right?

**Comment by bowenliang123** [comment]
OK, I found the compatibility matrix docs here: https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

**Comment by bowenliang123** [comment]
According to [Versioning](https://docs.docker.com/compose/compose-file/compose-versioning/#versioning), it's alright to use '3' here, better than '3.x' which could be deprecated on certain docker engine versions.

**Comment by Kennytian** [comment]
If only the major version is given (version: '3'), the latest minor version is used by default.

**Review by bowenliang123 — APPROVED** [review]
LGTM.

**Review by crazywoola — APPROVED** [review]

**Comment by Kennytian** [comment]
@takatost Please review my commit code.

**Review by takatost — APPROVED** [review]

**Pull request merged**
