### PR TITLE
fix the error of unable to retrieve url from file

### LINKED ISSUE #10514: fix the error of unable to retrieve url from file
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

fix the error of unable to retrieve url from file

### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

_No response_

### LINKED ISSUE #10590: fix: The url output by the list_operator is null
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Cloud

### I want to use the list operation module to extract the URL of the file file, including the dify cloud and local deployment operations, and the workflow shows that it can be completed. As shown below:
image

### However, on the dify cloud, the output is null, and in the local deployment, the output is path, but it does not contain parameters and cannot be used. As shown below:
image

### ✔️ Expected Behavior

image_url,As shown below:
image

### ❌ Actual Behavior

"url": null

### PR DESCRIPTION
**Pull request by XiaoLey**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #10514
Close https://github.com/langgenius/dify/issues/10590

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by XiaoLey** [comment]
cc @laipz8200 @crazywoola

**Comment by XiaoLey** [comment]
Are you saying the generated signature URL isn't working? I'll take a look at it later.
________________________________
发件人: skywalkerfmc ***@***.***>
发送时间: 2024年11月12日 9:17
收件人: langgenius/dify ***@***.***>
抄送: Xiao Ley ***@***.***>; Author ***@***.***>
主题: Re: [langgenius/dify] fix the error of unable to retrieve url from file (PR #10513)


cc @laipz8200<https://github.com/laipz8200> @crazywoola<https://github.com/crazywoola>

这样只能获取到那个签名url吧，通过这个url获取不到原始数据

―

**Comment by XiaoLey** [comment]
> 这样只能获取到那个签名url吧，通过这个url获取不到原始数据

I just conducted a thorough test, and both user-uploaded files and tool-generated files can be accessed normally. Even using curl, the file data can be retrieved successfully. The image is shown below:

Snipaste_2024-11-12_17-50-12

Snipaste_2024-11-12_17-51-52

Snipaste_2024-11-12_17-52-43

Snipaste_2024-11-12_17-52-54

---

> Yes, I think the signature URL is invalid

You can take a look at this environment variable: FILES_URL

image

---

In case there are any issues, please feel free to point them out! 😊

**Comment by skywalkerfmc** [comment]
> > 这样只能获取到那个签名url吧，通过这个url获取不到原始数据
> 
> I just conducted a thorough test, and both user-uploaded files and tool-generated files can be accessed normally. Even using curl, the file data can be retrieved successfully. The image is shown below:我刚刚进行了一次彻底的测试，用户上传的文件和工具生成的文件都可以正常访问。即使使用 curl，也可以成功检索文件数据。该图如下所示：
> 
> Snipaste_2024-11-12_17-50-12
> 
> Snipaste_2024-11-12_17-51-52
> 
> Snipaste_2024-11-12_17-52-43
> 
> Snipaste_2024-11-12_17-52-54
> 
> > Yes, I think the signature URL is invalid
> 
> You can take a look at this environment variable: FILES_URL
> 
> image
> 
> In case there are any issues, please feel free to point them out! 😊如果有任何问题，请随时指出来！😊


Does FILES_URL have to be set to "http://127.0.0.1:5001" . When I set to "http://127.0.0.1:5001", is don't work

**Comment by XiaoLey** [comment]
@skywalkerfmc is it working now?

**Comment by skywalkerfmc** [comment]
> @skywalkerfmc is it working now?

no, I deployed dify using docker. How should I set the FILES_URL

**Comment by xs818818** [comment]
how time merging

**Comment by laipz8200** [comment]
Let's have a discussion in #9567

**Comment by 1807426002** [comment]
f98bdb674ed83e61ad73a8a63e174e9
83a4adb38330aa2c610b10d0667978c
您好，我在工作室编辑是可以正常运行的，但是发布以后就显示图片无法找到，请问这是什么原因呢

**Comment by laipz8200** [comment]
Hi @XiaoLey! Sorry, we do not plan to support the signed URL, will close this PR.

**Pull request closed without merging**
