### PR TITLE
fix: an issue of keyword search feature in application log list

### LINKED ISSUE #7815: wrong pagination in application log list when using keyword search
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When using keyword search in the application log list, if a conversation has multiple messages containing the target keyword, the list display incorrect pagination and an inaccurate total data count.
Pasted Graphic

### ✔️ Expected Behavior

true pagination

### ❌ Actual Behavior

_No response_

### PR DESCRIPTION
**Pull request by realethanhsu**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
If there are multiple records in the Message table associated with the same Conversation, and some of these records contain target keywords, it can lead to duplicate Conversation records in the final query results. This results in wrong data counts and pagination issues. The revised code employs `Conversation.id.in_(message_subquery)` as a filter condition to ensure that only unique Conversations with related Messages are returned. This approach prevents duplicate Conversation records from appearing in the query results, thereby ensuring the accuracy of the log list and the proper functioning of the pagination feature.
Pasted Graphic
Pasted Graphic 1

Fixes #7815 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by crazywoola** [comment]
Please fix the errors in the CI.

**Comment by realethanhsu** [comment]
OK, I will finish this work today.

**Comment by realethanhsu** [comment]
@crazywoola done.

**Review by crazywoola — APPROVED** [review]

**Comment by takatost** [comment]
@realethanhsu This PR being modified to a full table scan statement, which resulted in a slow query, it could cause the database to go down.

The specific SQL that caused the full table scan is as follows:
```
...
conversations.id IN 
  (
    SELECT anon_2.conversation_id 
    FROM 
      (
	    SELECT messages.conversation_id AS conversation_id 
	    FROM messages 
	    WHERE messages.app_id = 'xxxx-xxxx-xxxx-xxxx-xxxx'::UUID
	    AND messages.query ILIKE '%abc%' OR messages.answer ILIKE '%abc%'
	  ) AS anon_2
  ) 
...
```

Due to the significant impact, we have rolled back for now.
Could you please check out the main branch again and optimize the SQL query based on it? Thank you very much.

**Comment by realethanhsu** [comment]
@crazywoola Sure, I will fix it soon.

**Pull request merged**
