### PR TITLE
Rewrite the firecrawl custom API url

### PR DESCRIPTION
**Pull request by ahasasjeb**
# Description

Rewrite the firecrawl custom API endpoint
Upgrade firecrawl-py to version 0.0.16 and remove a Python file, implementing the functionality more succinctly and efficiently, as the original code had issues.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [x] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by laipz8200** [comment]
Thanks for your contribution, please open an issue first, then link it to this PR. It will be helpful for us to manage our community. 😇

**Comment by ahasasjeb** [comment]
ok
---- Replied Message ----
From ***@***.***> Date 07/02/2024 08:57 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Rewrite the firecrawl custom API url (PR #5839) 
Thanks for your contribution, please open an issue first, then link it to this PR. It will be helpful for us to manage our community. 😇

**Comment by ahasasjeb** [comment]
I have already opened an issue

**Comment by crazywoola** [comment]
Please fix the errors in CI pipeline as well.

**Comment by laipz8200** [comment]
There's a matter about the license that we'd like to discuss. Let's address it in the referred issue.

**Comment by ahasasjeb** [comment]
Let's discuss it later today.
---- Replied Message ----
From ***@***.***> Date 07/02/2024 14:17 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [langgenius/dify] Rewrite the firecrawl custom API url (PR #5839) 
There's a matter about the license that we'd like to discuss. Let's address it in the referred issue.

**Comment by laipz8200** [comment]
Due to the related issue, I'll be closing this PR. Thank you.

**Pull request closed without merging**
