### PR TITLE
fix: add ffmpeg to docker image for api close #11714 #11631

### LINKED ISSUE #11714: Podcast audio generator fails, can't find "ffprobe"
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am use the example chatbot workflow `Notebook LLM by Dify.AI` and I have configured all the LLM and OpenAI TTS services. The generation of scripts works fine, but `Podcast audio generator` fails with the following error:
```
Error generating audio: [Errno 2] No such file or directory: 'ffprobe'
```
P.S.: sandbox version: 0.2.10

image

### ✔️ Expected Behavior

Generate audio files

### ❌ Actual Behavior

No file generated

### PR DESCRIPTION
**Pull request by yihong0618**
# Summary

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by yihong0618** [comment]
just search and found  https://github.com/langgenius/dify/pull/6971
not sure these CVE still exists in the latest ffmpeg

**Comment by laipz8200** [comment]
The podcast generator only generate wav file, and doesn't need ffmepg.

**Comment by yihong0618** [comment]
> The podcast generator only generate wav file, and doesn't need ffmepg.

but...#11714 #11631

**Comment by yihong0618** [comment]
close as disscuss

**Pull request closed without merging**
