### PR TITLE
chore: cleanup and rearrange unclassified configs into feature config groups

### PR DESCRIPTION
**Pull request by bowenliang123**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
- rearrange unclassified configs of DifyConfig in proper feature groups
- make configs configurable in code execution details and HTTP requesting, with data type checks
- avoid abused usage of `@computed_field` for display messages,  which is week in reliability and misuse of configs:
  - HTTP_REQUEST_NODE_READABLE_MAX_BINARY_SIZE
  - HTTP_REQUEST_NODE_MAX_TEXT_SIZE
- removing unused config:
   -  OUTPUT_MODERATION_BUFFER_SIZE

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @laipz8200 @takatost

**Review by laipz8200 — APPROVED** [review]
LGTM

**Comment by laipz8200** [comment]
Hi @bowenliang123. This would be a great opportunity to apply the Ruff Formatter within the config/ directory. Would you be interested in implementing this change?

**Comment by bowenliang123** [comment]
Sure. That goes with #7590.

**Comment by laipz8200** [comment]
> > Hi @bowenliang123. This would be a great opportunity to apply the Ruff Formatter within the config/ directory. Would you be interested in implementing this change?
> 
> Sure. That goes with #7590 for the configs, #7591 for the tests and #7592 for the db migrations.

Awesome! Thank you for doing these!

**Pull request merged**
