### PR TITLE
chore: refurish python code by applying Pylint linter rules

### PR DESCRIPTION
**Pull request by bowenliang123**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
- apply auto-fixable rules from PyLint by ruff: https://docs.astral.sh/ruff/rules/#pylint-pl
- no behaviour changes, some notable improvement:
  - avoid using from {module} import {name} in lieu of alias
  - use a set literal when testing for membership
  - avoid unnecessary dunder call to {method}. {replacement}.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @laipz8200

**Comment by bowenliang123** [comment]
With this PR merged, there are no more Ruff's linter rules required to apply from my prospective.

**Comment by laipz8200** [comment]
I think it would be best to exclude the migrations directory from the linter, since it mostly contains code generated by Alembic.

**Comment by bowenliang123** [comment]
> I think it would be best to exclude the migrations directory from the linter, since it mostly contains code generated by Alembic.

Have prevented changes in migrations. Now the `migration` path has been added to Ruff setting's `[tool.ruff]` section for exclusion in both linting and reformatting, which is more easy to maintain.

**Review by laipz8200 — APPROVED** [review]

**Pull request merged**
