### PR TITLE
fix: issue Multiple Paths Between IF/ELSE Branches

### LINKED ISSUE #11542: Multiple Paths Between IF/ELSE Branches Invalidate Conditions and Execute All Paths
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have searched for existing issues, and this problem is similar to #10638 and #10564, but the trigger method is more concise.

I want to control the progress branches of a multi-turn dialogue by using IF/ELSE to judge the content of the variable.  
But if there are multiple paths connecting two IF/ELSE branches (with one being a direct connection), it will cause the condition of the second branch to become invalid and execute all subsequent paths.

# Steps 
## Situation 1
Here is an example with two conditional branches, one of which has a direct connection path.

image

## Temporary solution
Adding an empty component in all paths, such as assigning a value to an empty variable, can temporarily circumvent this issue.

image

## Situation 2 
If multiple paths leading out of the IF/ELSE connect to the same problem classifier, an error indicating no results will also occur.
image
image

Once this issue occurs, the problem classifier can no longer function properly and can only be deleted and rebuilt.

### ✔️ Expected Behavior

Execute according to the correct multi-level branching logic structure.

### ❌ Actual Behavior

The failure of the IF/ELSE condition resulted in all child branches being triggered.

### PR DESCRIPTION
**Pull request by yihong0618**
# Summary

The logic steam answer is wrong we can not make sure which is the right answer.

close #11542 #9560 https://github.com/langgenius/dify/issues/10638 https://github.com/langgenius/dify/issues/10564,

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by laipz8200** [comment]
image

Hi, I tested this change in a simple chat flow and got a strange answer.

Here is the chat flow I used: [Basic Chatflow.txt](https://github.com/user-attachments/files/18135567/Basic.Chatflow.txt), you can copy its address and import it from the URL.

**Comment by yihong0618** [comment]
let me fix it

**Comment by yihong0618** [comment]
> image
> Hi, I tested this change in a simple chat flow and got a strange answer.
> 
> Here is the chat flow I used: [Basic Chatflow.txt](https://github.com/user-attachments/files/18135567/Basic.Chatflow.txt), you can copy its address and import it from the URL.

try to fix it, can you test again

**Comment by laipz8200** [comment]
I just changed the content in the Answer node, and the problem is still present.

image

**Comment by yihong0618** [comment]
not quite the root cause its hard, so draft it for now

**Comment by yihong0618** [comment]
> not quite the root cause its hard, so draft it for now

root cause found

**Comment by laipz8200** [comment]
After a few tests, it works well!

**Comment by yihong0618** [comment]
> After a few tests, it works well!

niubi a！

**Comment by laipz8200** [comment]
Try this App: [test_case.txt](https://github.com/user-attachments/files/18205864/test_case.txt)

test_case_screenshot

message:

> hello, what's your name and what can you do for me?

Now the streaming output not work in Answer 2

**Comment by yihong0618** [comment]
cool will test

**Comment by yihong0618** [comment]
> Try this App: [test_case.txt](https://github.com/user-attachments/files/18205864/test_case.txt)
> 
> test_case_screenshot
> message:
> 
> > hello, what's your name and what can you do for me?
> 
> Now the streaming output not work in Answer 2

it worked the same behavior as cloud

**Review by laipz8200 — APPROVED** [review]

**Pull request merged**
