### PR TITLE
feat: fe mobile responsive next

### PR DESCRIPTION
**Pull request by yuhao1118**
# Enhances Dify's Mobile Appearance
## The preceding MR was #1599, which was closed due to certain bugs. For comprehensive details, please refer to this MR.

I have made as many style adjustments as possible to optimize Dify for mobile usage, while striving to keep everything unchanged on desktop devices. The modifications are primarily CSS changes, which ideally should not disrupt any existing code logic. If any changes do not adhere to Dify's design guidelines, please feel free to modify them.

image
image
image

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]
@iamjoel Please take a further look at this pull request, I have tested, seems ok to me.

**Review by crazywoola — CHANGES_REQUESTED** [review]
The previous header was 56px on desktop but the new pr show it's 42 px.

**Comment by yuhao1118** [comment]
Hi, all bugs have been fixed! Please could you review again?

**Review by crazywoola — APPROVED** [review]

**Comment by crazywoola** [comment]
> Hi, all bugs have been fixed! Please could you review again?

I have approved this PR, will merge it into main later next week.

**Pull request merged**
