### PR TITLE
feat: update model_provider jina to support custom url and model

### PR DESCRIPTION
**Pull request by VoidIsVoid**
# Description

add jina_api_compatible to provide a method that user can add their rerank model

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by takatost** [comment]
I think we can just add the base URL and context size parameters directly on Jina Rerank, right? We can also add a switch for the context size, whether we need to customize it or not.

**Comment by VoidIsVoid** [comment]
> I think we can just add the base URL and context size parameters directly on Jina Rerank, right? We can also add a switch for the context size, whether we need to customize it or not.

It's a good suggues to add on jina rerank. 
I think it's no need to add a switch for the context size, each model needs context size setting

**Comment by VoidIsVoid** [comment]
@takatost  I have update the code, please check again, thank you

**Comment by takatost** [comment]
> > I think we can just add the base URL and context size parameters directly on Jina Rerank, right? We can also add a switch for the context size, whether we need to customize it or not.
> 
> It's a good suggues to add on jina rerank. I think it's no need to add a switch for the context size, each model needs context size setting

You're right, I mixed up the built-in models. 😅

**Comment by takatost** [comment]
> @takatost I have update the code, please check again, thank you

Thanks, I'll test it later.

**Comment by takatost** [comment]
image

Looks like the parameter `api_key` is missing here.

**Comment by VoidIsVoid** [comment]
> image
> Looks like the parameter `api_key` is missing here.

sorry, it's forgot, I will add it later.

**Comment by VoidIsVoid** [comment]
> image
> Looks like the parameter `api_key` is missing here.

sorry, it's forgot, I will add it later.
I find another issue, I only want to add rerank model by jina compatible api, but when i add customizable-model, text-embedding shows up, I didn't want it, cause i can add embedding model by compatible api.
Is there some how I can hide text text-embedding? Or I should revert code to first version to add rerank only. 
@takatost

**Comment by takatost** [comment]
> > image
> > Looks like the parameter `api_key` is missing here.
> 
> sorry, it's forgot, I will add it later. I find another issue, I only want to add rerank model by jina compatible api, but when i add customizable-model, text-embedding shows up, I didn't want it, cause i can add embedding model by compatible api. Is there some how I can hide text text-embedding? Or I should revert code to first version to add rerank only. @takatost

I fixed it for you and also added custom model configuration for Embedding. 😉

**Review by takatost — APPROVED** [review]
LGTM

**Comment by VoidIsVoid** [comment]
> > > image
> > > Looks like the parameter `api_key` is missing here.
> > 
> > 
> > sorry, it's forgot, I will add it later. I find another issue, I only want to add rerank model by jina compatible api, but when i add customizable-model, text-embedding shows up, I didn't want it, cause i can add embedding model by compatible api. Is there some how I can hide text text-embedding? Or I should revert code to first version to add rerank only. @takatost
> 
> I fixed it for you and also added custom model configuration for Embedding. 😉

Thank you so much.

**Pull request merged**
