### PR TITLE
fix: volcengine_maas and baichuan message error

### PR DESCRIPTION
**Pull request by zhongliliu-butterfly**
# Summary

fix volcengine_maas model message support type:"text" and baichuan model message error

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

image

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by zhongliliu-butterfly** [comment]
image
volcengine_maas message support type:"text"

**Comment by crazywoola** [comment]
Please fix the lint errors

**Comment by zhongliliu-butterfly** [comment]
> Please fix the lint errors

lint error fixed

**Comment by shenzhoushumaliuzhongli** [comment]
lint error has been fixed

**Comment by shenzhoushumaliuzhongli** [comment]
> Please fix the lint errors
lint error has been fixed

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
