### PR TITLE
chore: upgrade cohere && tidb-vector version

### LINKED ISSUE #7743: need to upgrade cohere sdk version
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I tested a large pdf file with cohere embedding.

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

cohere server error (500)

So, I ask to the Cohere development team and was advised to use the latest SDK version. 
However, since the current Dify source cannot accommodate the latest version, modifications are needed on the provider side.

### PR DESCRIPTION
**Pull request by Weaxs**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- cohere: 5.2.4 -> 5.8.1 Close https://github.com/langgenius/dify/issues/7743

- tidb-vector: 0.0.9 -> 0.0.12

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [x] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by Weaxs** [comment]
https://github.com/langgenius/dify/issues/7743

**Comment by crazywoola** [comment]
Tests are failed.

**Comment by Weaxs** [comment]
@laipz8200 can you pls review this upgrade, thx

**Comment by laipz8200** [comment]
We are planning an upgrade to the RAG system and will test this PR once the upgrade is complete. Thank you for your patience!

**Pull request closed without merging**
