### PR TITLE
Enhancement: add model provider - Amazon Sagemaker

### PR DESCRIPTION
**Pull request by ybalbert001**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

### CODE REVIEW

**Comment by ybalbert001** [comment]
Screenshot 2024-07-13 at 17 17 07

**Review by crazywoola — CHANGES_REQUESTED** [review]
Thanks for your contribution, please add the required tests as well. If you are not sure about how to add tests, please take a look at this file below.

https://github.com/langgenius/dify/blob/d9b821ceccc5b84de10b73ed74c65a00e83d3d78/api/tests/integration_tests/model_runtime/bedrock/test_provider.py

**Comment by ybalbert001** [comment]
###  Testing Result
Screenshot 2024-07-14 at 09 14 36

Screenshot 2024-07-14 at 09 15 07

Screenshot 2024-07-14 at 09 15 18

**Comment by ybalbert001** [comment]
Add integration_tests for Sagemaker model provider in another commit

**Review by crazywoola — DISMISSED** [review]

**Comment by crazywoola** [comment]
Please fix the lint errors. I will merge it asap.

**Comment by ybalbert001** [comment]
> Please fix the lint errors. I will merge it asap.

Done

**Review by crazywoola — DISMISSED** [review]

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
