### PR TITLE
Added diagram picture file for docker-compose yaml file visualization.

### PR DESCRIPTION
**Pull request by yangboz**
added diagram picture file for docker-compose yaml file visualization.

### CODE REVIEW

**Comment by takatost** [comment]
Can we add a README file in this directory to explain this image?

**Review by crazywoola — APPROVED** [review]

**Comment by crazywoola** [comment]
> Can we add a README file in this directory to explain this image?

@yangboz

**Review by crazywoola — CHANGES_REQUESTED** [review]
Can we add a README.md file to explain it a little.

**Comment by yangboz** [comment]
> > Can we add a README file in this directory to explain this image?
> 
> @yangboz

sure thing

**Comment by crazywoola** [comment]
> > > Can we add a README file in this directory to explain this image?
> > 
> > 
> > @yangboz
> 
> sure thing

Also can you add my wechat: crazyphage, we are very appreciate your contribution, I will invite you to our developer group.

**Comment by yangboz** [comment]
> crazyphage

friend request sent, please accept

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
