### PR TITLE
fix(env): docker compose variable interpolation issue for COMPOSE_PRO…

### LINKED ISSUE #12081: Invalid interpolation format for x-shared-env.COMPOSE_PROFILES
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Clone the latest source from `https://github.com/langgenius/dify.git` and follow the docker steps as outlined in the documentation page: [https://docs.dify.ai/getting-started/install-self-hosted/docker-compose#starting-dify](url)

### ✔️ Expected Behavior

Expected output of the containers, layers, images to be pulled smoothly and exiting successfully.

### ❌ Actual Behavior

image

Instead, the interpolated environment variable, in particular, the `COMPOSE_PROFILES` is causing a problem due to a missing extra `$` such that the correct version of the line should like this: 
`COMPOSE_PROFILES=$${VECTOR_STORE:-weaviate}`

### PR DESCRIPTION
**Pull request by hanktrizz**
Updated files
- `generate-docker-compose`
- `docker-compose.yml`

# Summary

Added condition to ignore the environment variable `COMPOSE_PROFILES`. Otherwise, it will fail upon running `docker compose up -d` with the current interpolation setup.

Fixes #12081

# Screenshots

| Before | After |
|--------|-------|
| image| Screenshot 2024-12-25 at 8 33 07 PM|

# Checklist

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/e88ea71aefd2adca64683ce0cca836df015d0f4f/docker/docker-compose-template.yaml#L1

You should modify this file instead of modify the `.env.example` directly.
The new `.env.example` is generated by this command 
https://github.com/langgenius/dify/blob/1885d3df9968d778664bacdde4ea7a4d9448070f/docker/generate_docker_compose

**Comment by hanktrizz** [comment]
Oops, my bad. I’ll fix that up. Yeah I did change the template in my local
and then got excited after getting it to work that I directly changed the
env.example 😂

**Comment by hanktrizz** [comment]
> https://github.com/langgenius/dify/blob/e88ea71aefd2adca64683ce0cca836df015d0f4f/docker/docker-compose-template.yaml#L1
> 
> You should modify this file instead of modify the `.env.example` directly. The new `.env.example` is generated by this command https://github.com/langgenius/dify/blob/1885d3df9968d778664bacdde4ea7a4d9448070f/docker/generate_docker_compose

Correct me if I'm wrong @crazywoola but it seems the sequence of generation goes like this (as per `main()` inside `generate-docker-compose` file:

Reads `.env.example` -> creates the shared env variables block -> substitutes the anchor with the shared block -> generate the template.yaml -> re-generate the final `docker-compose.yaml`. 

There is nowhere in the `docker-compose-template.yaml` that is dealing with the env variables `COMPOSE_PROFILES` or `VECTOR_STORE` directly. 
As I am relatively new to this codebase, I am happy to stand corrected and keen to learn if you can help clarify this.

**Comment by laipz8200** [comment]
It seems that COMPOSE_PROFILES shouldn’t appear in the docker-compose.yaml file. You should modify the generate-docker-compose script to ignore this key.

**Comment by hanktrizz** [comment]
Okay. I'll try and ignore that specific key. Will commit soon-ish due to the fact it's Xmas season 😄

**Comment by hanktrizz** [comment]
@laipz8200 Hi, can you please have another look? I believe it's as straightforward as it gets in terms of ignoring that key as per your advice. I have regenerated the `docker-compose.yml` file and also checked it in. Verified that `docker compose up -d` still run smoothly after the changes as well. 

Sorry for the delay due to holidays hhh.

**Comment by laipz8200** [comment]
Looks good to me. Now, the `.env.example` should be changed back.

**Comment by hanktrizz** [comment]
> Looks good to me. Now, the `.env.example` should be changed back.

All done, mate. Please help to approve and merge at will 🙏

**Review by laipz8200 — APPROVED** [review]
LGTM. Thank you for your contribution!

**Pull request merged**
