### PR TITLE
improve: extract method for safe loading yaml file and avoid using PyYaml's FullLoader

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- extract a general method for loading YAML file into object, in following step
  - check the file path existence and properly open / close the IO stream in place
  - use `yaml`'s `safe_load` method
- enable ruff's S506 rule (https://docs.astral.sh/ruff/rules/unsafe-yaml-load/) to avoid possible unsafe yaml loading
- benefits:
  - avoid using `yaml.load` directly , according to Yaml's docs for deprecation: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
  - skip repeated opening file stream or checking file existence
  - prevent hanging code indent for opening file
  - unified method for handling errors
  - properly covered by unit tests

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

- [x] add unit tests

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
This PR is ready for review. Please have a check. cc @takatost

**Comment by bowenliang123** [comment]
cc @Yeuoly

**Comment by Yeuoly** [comment]
hi, while testing this PR, I found that there are lots of unnecessary warnings appeared, as _position.yaml is not required to each provider, we should ignore them I think.
image

**Comment by bowenliang123** [comment]
> hi, while testing this PR, I found that there are lots of unnecessary warnings appeared, as _position.yaml is not required to each provider, we should ignore them I think.
Shall I change it to the `debug` logging level?

**Review by Yeuoly — APPROVED** [review]
LGTM

**Pull request merged**
