### PR TITLE
Workflow TTS playback node filtering issue.

### PR DESCRIPTION
**Pull request by ic-xu**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

In the workflow chat, if a workflow contains multiple LLM nodes and the TTS auto-play feature is enabled, then the output of each LLM node will play the LLM. This may not be what the user needs. This fix is to ensure that TTS only plays the text content of the output from the end node, so that whatever the user sees, TTS will play.
eg.

image

In such cases, TTS should only play the output of the LLM2 node, because the final output of the Answer is the data from LLM2, and what the user sees is also the data output by LLM2. Therefore, TTS should only play the data output by LLM2.

Fixes 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by laipz8200** [comment]
What will happen if this workflow has multiple branches and `answer` nodes?

**Comment by ic-xu** [comment]
> What will happen if this workflow has multiple branches and `answer` nodes?

Regardless of whether there are multiple workflows or multiple answer nodes, the final output of the program is definitely a single answer node. At this point, the TTS should play the output content of this answer node, which is considered reasonable. This way, what the user hears should match what they see.

**Comment by ic-xu** [comment]
I am currently working on improving in this direction, and I have already tested it. If you have any new issues, I hope we can communicate more.

**Review by laipz8200 — APPROVED** [review]
Thanks!

**Pull request merged**
