### PR TITLE
feat: add Database Operation tool

### LINKED ISSUE #5526: add Database Operation tool that allows execution of SQL statements and returns corresponding results
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need a tool that can access the database, hence this requirement.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by XiaoLey**
# Description

Introduced a new Database Operation tool that allows execution of SQL `SELECT` statements and returns corresponding results. This enhancement improves the convenience of database operations. Considering the rigorousness of database operations, currently only `SELECT` statements are supported. Support for other types of SQL statements will be added in future updates.

Currently supported ORDBMS include **PostgreSQL** and **MySQL**.

https://github.com/langgenius/dify/assets/46273173/6e295e13-d2c2-4b89-8d8c-830bb4ad796f

Fixes #5526 (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by XiaoLey** [comment]
CC @bowenliang123

**Comment by lukefan** [comment]
Your idea to add user-defined tables to Dify's PostgreSQL database is interesting and could enhance its functionality. For a simpler initial implementation, we could consider the following:

Basic table structure: Allow users to create simple tables with basic data types (e.g., text, number, date).
CRUD operations: Provide APIs for users to perform basic Create, Read, Update, and Delete operations on their custom tables.
Simple querying: Enable basic querying capabilities, such as filtering and sorting.
User-level isolation: Ensure each user can only access their own custom tables.
Straightforward API: Design a simple, intuitive API for table creation and data manipulation.
Basic data export: Allow users to export their table data in common formats like CSV.
This simplified approach avoids complex data structures, performance optimizations, and multi-table relationships initially. It provides a foundation that can be expanded upon in the future if needed.

What are your thoughts on this simplified approach? Do you have any specific use cases in mind for these custom tables?

**Comment by XiaoLey** [comment]
> Your idea to add user-defined tables to Dify's PostgreSQL database is interesting and could enhance its functionality. For a simpler initial implementation, we could consider the following:
> 
> Basic table structure: Allow users to create simple tables with basic data types (e.g., text, number, date). CRUD operations: Provide APIs for users to perform basic Create, Read, Update, and Delete operations on their custom tables. Simple querying: Enable basic querying capabilities, such as filtering and sorting. User-level isolation: Ensure each user can only access their own custom tables. Straightforward API: Design a simple, intuitive API for table creation and data manipulation. Basic data export: Allow users to export their table data in common formats like CSV. This simplified approach avoids complex data structures, performance optimizations, and multi-table relationships initially. It provides a foundation that can be expanded upon in the future if needed.
> 
> What are your thoughts on this simplified approach? Do you have any specific use cases in mind for these custom tables?

Your suggestion is excellent and aligns with what I hope to achieve. However, Dify currently supports only a limited set of data types (string, number, boolean, and select). To implement more advanced features, I believe the "array" type is essential. While it's possible to simulate an array using the string type, it's neither intuitive nor easy to maintain.

At present, I feel that directly using SQL statements is just a temporary solution and can be quite risky. If we can support more diverse data types in the future, we might even be able to avoid SQL statements altogether.

Thank you for your understanding and support. Looking forward to further discussions on this topic.

**Comment by Vince-Lau** [comment]
I think database operation tool is very necessary to dialog state tracking (DST). I was struggling with how to operate the database, and then I tried to connect to PostgreSQL in Sandbox using Python, but failed because Sandbox cannot make network requests (https://docs.dify.ai/v/zh-hans/guides/workflow/node/code#ben-di-bu-shu).

I hope dify can add this tool, it will be very helpful.

**Comment by XiaoLey** [comment]
Hi @Vince-Lau , I'm currently designing this database operation tool, mainly considering various database security issues, and thus thinking about an optimized design to minimize the direct use of SQL statements. However, SQL statements might be available as an optional feature. We also highly value and welcome user suggestions! Thank you for your support and attention!

**Comment by lvweicong** [comment]
Does it support SQL Server and Oracle?

**Comment by hwzhuhao** [comment]
@Vince-Lau you can modify the docker-compose.yaml, update the value of networks.ssrf_proxy_network.internal, as follows:
networks:
  # create a network between sandbox, api and ssrf_proxy, and can not access outside.
  ssrf_proxy_network:
    driver: bridge
    internal: false

**Comment by hjlarry** [comment]
Hi @XiaoLey ,  is there some corner sql statements can bypass the `SELECT` limit ?  can we find another way to defense it?

**Comment by XiaoLey** [comment]
Hi @hwzhuhao. Currently, I can't think of a method that would fully replicate the flexibility of using `SELECT` statements directly when relying solely on **ORM**. It seems clear that achieving the same level of flexibility is quite difficult, at least with the current input tools which do not support arrays and objects.
Perhaps you have a better idea? We can discuss it together!

**Comment by bingbing6** [comment]
We want this feature

**Comment by zlm0001** [comment]
> 我们想要这个功能

您好，这个功能您找到方式引用了吗？我们也想用这个功能

**Pull request closed without merging**
