### PR TITLE
feat: Output custom parameters at the message_end node #11078

### LINKED ISSUE #11078: Output custom parameters at the message_end node
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I need to customize the output of some parameters in the streaming interface and non-streaming interface. For example: customized knowledge sources, recommended questions, some flags, etc.

I modified the meesage_end node to output the specified session variable.If allowed I will submit it.

image
image
image

image

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by dajianguo**
# Summary

You can customize the output of some parameters in the streaming interface and non-streaming interface. For example: customized knowledge sources, recommended questions, some flags, etc.

I modified the meesage_end node to output the specified session variable.

Resolves #11078 

# Screenshots

image
image
image
image

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by laipz8200** [comment]
This is not the intended responsibility of Conversation Variables as we envisioned them, and I believe it is not suitable for merging.

**Comment by flyhighzy** [comment]
> This is not the intended responsibility of Conversation Variables as we envisioned them, and I believe it is not suitable for merging.

We're facing the same problem here since we want to get more info from LLM calls. So what's the better solution here?

**Comment by laipz8200** [comment]
> So what's the better solution here?

@flyhighzy I'm not sure, could you please describe your scenario in detail in #11078? We can have a discussion there.

**Comment by flyhighzy** [comment]
> > So what's the better solution here?
> 
> @flyhighzy I'm not sure, could you please describe your scenario in detail in #11078? We can have a discussion there.

OK~ already reply  https://github.com/langgenius/dify/issues/11078#issuecomment-2513719033

**Pull request closed without merging**
