### PR TITLE
Add llama3.3 70b because llama-3.2-90b-text-preview has been decommissioned and is no longer supported

### LINKED ISSUE #11455: Support newer Groq Models and remove the deprecated ones
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Groq has added Llama3.3 and Llama3.3 Spec Decode to list of its models. Adding those models to Dify

### 2. Additional context or comments

https://console.groq.com/docs/models

image
image

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by aaaAlexanderaaa**
# Summary

Added Groq Models llama-3.3

> [!Tip]
> Close issue syntax: `Resolves #11455`

# Screenshots

| Before | After |
|--------|-------|
| ...    | image  |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]
Please mark the old yaml file as deprecated as well.

**Comment by alokas** [comment]
I have added this in my PR # 11456

**Comment by aaaAlexanderaaa** [comment]
> Please mark the old yaml file as deprecated as well.

I‘ll raise another PR to mark the old yaml as deprecated.

**Comment by aaaAlexanderaaa** [comment]
> Duplicate of PR # 11456

emm, Yes, I just found this out. I saw that his content is exactly the same as mine and has added a deprecated message, I will close my PR.

**Pull request closed without merging**
