### PR TITLE
chore: update package versions to 0.7.0

### PR DESCRIPTION
**Pull request by laipz8200**
## ✨ What’s New in v0.7.0? ✨

Hey everyone, we’ve got a fresh update for you! Version 0.7.0 is here, and it’s packed with new features, model support, tools, and enhancements. Let’s dive in:

### 🚀 New Features

- **Conversation Variable & Variable Assigner Node** by @JzoNgKVO, @iamjoel and @laipz8200 in #7222

  conversation-variable

  Learn more: 

  - [Enhancing LLM Memory with Conversation Variables and Variable Assigners](https://dify.ai/blog/enhancing-llm-memory-with-conversation-variables-and-variable-assigners)
  - [Conversation Variables](https://docs.dify.ai/guides/workflow/key_concepts#conversation-variables)
  - [Variable Assigner](https://docs.dify.ai/guides/workflow/node/variable-assignment)

### 🧠 Models

- **GPT-4o-2024-08-06 Model** by @majian159 in #7046
- **GLM-4-Long Model** by @ox01024 in #7070
- **Zhipu Embedding-3 Model** by @orangeclk in #7100
- **Wenxin Yi-34b-Chat Model** by @sulgweb in #7117
- **HuggingFace TEI Text Embedding and Rerank Model** by @liuyanyi in #7132
- **Siliconflow LLM and Text Embedding Models** by @alfredcai in #7090
- **360-Zhinao Provider** by @sulgweb in #7069

### 🛠️ Tools

- **D-ID Tool** by @MatriQ in #6278
- **GitLab Tool** by @wlrnet in #7179

### ⚙️ Enhancements

- **Elasticsearch Vector Database Support** by @miendinh in #3558
- **Support for drawing with ECharts in output** by @zhujinle in #6961
- **Workflow Interaction Improvements** by @zxhlyh in #4214
- **Workflow Logs with Run ID Filter** by @majian159 in #6833
- **Hyperlink Parsing in DOCX Documents** by @ic-xu in #7017
- **Vector Field for Other VectorDB** by @JohnJyong in #7051
- **Poetry Requests Timeout** by @ZuzooVn in #7086
- **Update Dataset Embedding Model** by @JohnJyong in #7145
- **Add Decode Option to JSON Process Tools** by @laojianzi in #7138
- **Support for Non-English Characters in Exported DSL Files** by @gijigae in #7042
- **Support for NEXT_TELEMETRY_DISABLED** by @ZuzooVn in #7181

That’s a wrap for v0.7.0! We hope you enjoy the new features and improvements. As always, your feedback is invaluable to us. Happy coding! 🚀

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Comment by knight-y-j** [comment]
`docker compose up -d` Error message

```
Error response from daemon: manifest for langgenius/dify-api:0.7.0 not found: manifest unknown: manifest unknown
```

**Comment by tonykcn** [comment]
there is no 0.7.0 docker images in docker hub yet.

**Comment by laipz8200** [comment]
> `docker compose up -d` Error message
> 
> ```
> Error response from daemon: manifest for langgenius/dify-api:0.7.0 not found: manifest unknown: manifest unknown
> ```
> 
>     * [Docker hub dify-web](https://hub.docker.com/r/langgenius/dify-web/tags?page=&page_size=&ordering=&name=0.7)

We've not released 0.7.0, you can run `git checkout 0.6.16` to get the current docker compose file now.

**Comment by Joir-Jio** [comment]
> Docker Hub 中还没有 0.7.0 docker 镜像。

what should i do

**Pull request merged**
