### PR TITLE
fix (#8322 followup): resolve the violation of pylint rules

### PR DESCRIPTION
**Pull request by bowenliang123**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- #8322 is merged after the #8372, which contains violation of PLR6201 rule and blocks style checks.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @laipz8200

**Review by laipz8200 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks for the quick review and merging. Have a nice weekend~

**Comment by Caiws** [comment]
This merge cause some issues when the value is a dict, it can lead to unhashable problems.

**Comment by bowenliang123** [comment]
Hi, may I have your concern in which line of the changes or which PyLint rule causing the problem?

**Comment by Caiws** [comment]
图片
图片
Like this, because the 'extract' is dict, not in will be judged using hash, and dict type is not hashable, which causes an exception

**Pull request merged**
