### PR TITLE
Add the ability to parse PDF tables, pictures, and cross-page tables

### PR DESCRIPTION
**Pull request by ic-xu**
# Description

Using the enhanced open parsing library to parse PDF documents, you can maintain the table style of the PDF document, and also extract image content, table content, cross-page tables, etc. in the PDF, while trying to ensure that it meets the user's reading order.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

To test the PDF parsing function individually, use the following code, Use pdfmimer algorithm
`from core.rag.extractor.pdf.openparse import DocumentParser, processing
from core.rag.extractor.pdf.openparse.schemas import ImageElement

if __name__ == '__main__':
    """Lazy load given path as pages."""
    # blob = Blob.from_path(self._file_path)
    # yield from self.parse(blob)
    file_path = "pdf file path here"
    documents = []
    parser = DocumentParser(
        processing_pipeline=processing.BasicIngestionPipeline(),
        table_args={
            "parsing_algorithm": "pdfmimer",
            "table_output_format": "markdown"
        }
    )
    parsed_basic_doc = parser.parse(file_path)
    documentContent = ''
    for _index, node in enumerate(parsed_basic_doc.nodes):
        metadata = {"source": file_path, "page": _index}
        for element in node.elements:
            if isinstance(element, ImageElement):
                # pdf images a
                pass
            else:
                print(element.text)`

there is ImageElement\ TableElement\TextElement
If you parse the image, the focus is ImageElement， which has the following attributes that can be used
block: dict
text: str
image: bytes
ext: str
bbox: Bbox

### CODE REVIEW

**Comment by bowenliang123** [comment]
The feature is interesting and attractive, while the suggested approach should be clarified during evaluation.

1. Copied and modified the source code from `open-parse` (https://github.com/Filimoa/open-parse), it may make Dify burden in maintaining the outdated code(0.5.2 used in this PR and the latest is 0.5.6) and risk the licence viloations（without proper declaimer）
2. Also some copied souces from `pdfmind`
3. introduced new package `pdfplumber`'s purpose is not clear

**Comment by ic-xu** [comment]
In https://github.com/Filimoa/open-parse, I have also contributed some code. His main branch code is very different from ours. The main differences are as follows: 1. The official has not eliminated third-party commercial dependency packages, but we have already eliminated them. 2. The official does not have the ability to extract images, but we do. 3. The official does not handle cross-page forms, we do. 4. Our local code supports multiple table output formats




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langgenius/dify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月1日(星期六) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langgenius/dify] Add the ability to parse PDF tables, pictures, and cross-page tables (PR #4832)





 
The feature is interesting and attractive, while the suggested approach should be clarified during evaluation.
  
Copied and modified the source code from open-parse (https://github.com/Filimoa/open-parse), it may make Dify burden in maintaining the outdated code(0.5.2 used in this PR and the latest is 0.5.6) and risk the licence viloations（without proper declaimer）
 
Also some copied souces from pdfmind
 
introduced new package pdfplumber's purpose is not clear

**Comment by takatost** [comment]
Thank you so much for your contribution! As @bowenliang123 mentioned, directly copying code from other projects is not acceptable. Plus, pymupdf is under an AGPL license, which cannot be used with our Apache license.

**Comment by ZuzooVn** [comment]
@ic-xu does your pull request include PDF OCR capability?

**Comment by taowang1993** [comment]
> # Description
> Using the enhanced open parsing library to parse PDF documents, you can maintain the table style of the PDF document, and also extract image content, table content, cross-page tables, etc. in the PDF, while trying to ensure that it meets the user's reading order.
> 
> # How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> 
> To test the PDF parsing function individually, use the following code, Use pdfmimer algorithm `from core.rag.extractor.pdf.openparse import DocumentParser, processing from core.rag.extractor.pdf.openparse.schemas import ImageElement
> 
> if **name** == '**main**': """Lazy load given path as pages.""" # blob = Blob.from_path(self._file_path) # yield from self.parse(blob) file_path = "pdf file path here" documents = [] parser = DocumentParser( processing_pipeline=processing.BasicIngestionPipeline(), table_args={ "parsing_algorithm": "pdfmimer", "table_output_format": "markdown" } ) parsed_basic_doc = parser.parse(file_path) documentContent = '' for _index, node in enumerate(parsed_basic_doc.nodes): metadata = {"source": file_path, "page": _index} for element in node.elements: if isinstance(element, ImageElement): # pdf images a pass else: print(element.text)`
> 
> there is ImageElement\ TableElement\TextElement If you parse the image, the focus is ImageElement， which has the following attributes that can be used block: dict text: str image: bytes ext: str bbox: Bbox

Can we embed images into vector database currently? 

I really need this embedding feature. My PDFs have some images in it.

**Pull request closed without merging**
