### PR TITLE
fix: tool params null value cover default value

### LINKED ISSUE #6948: Function calling null param
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

V0.6.15

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I created an Custom Agent Tool to call a third-party API. In this third-party API parameters, default values will be set for some fields which not passed. However, null values are set for this field currently. As a result, an error occurs when the default field value are overwritten.

### ✔️ Expected Behavior

In the logdetail dialog, it show that LLM only pass one param to the third-party API.

图片

### ❌ Actual Behavior

When I debug into the soure code, the acture request body contain lot of null param.

图片

### PR DESCRIPTION
**Pull request by Sumkor**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

I created an Custom Agent Tool to call a third-party API. In this third-party API parameters, default values will be set for some fields which not passed. However, null values are set for this field currently. As a result, an error occurs when the default field value are overwritten.

✔️ Expected Behavior

21BC4D7A-8345-48cc-AF59-4FF88032BD6A

❌ Actual Behavior

E311C86E-BBC2-43dd-87F4-60718C809EDE

✔️ Repair Behavior

545294B8-BCE1-41ed-9852-E0A745C6CB41

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

Fixes #6948

### CODE REVIEW

**Comment by laipz8200** [comment]
We have a way to use the default value; it is just above the code you modified. Couldn't this solve your problem?

**Comment by Sumkor** [comment]
> We have a way to use the default value; it is just above the code you modified. Couldn't this solve your problem?

@laipz8200 Hi there, Adding a 'default' attribute does work, but it doesn't seem to be a standard practice in Swagger Request Body API. Seeing https://swagger.io/docs/specification/describing-request-body/

Also, in my case, the third-party API generate swagger json by springfox-swagger automatically and it doesn't has a 'default' attribute in request body. It's a lot of work for me to modify the swagger json one by one.

**Comment by laipz8200** [comment]
> > We have a way to use the default value; it is just above the code you modified. Couldn't this solve your problem?
> 
> @laipz8200 Hi there. Adding a 'default' attribute in swagger json does work, but it doesn't seem to be a standard practice in Swagger Request Body API. Seeing https://swagger.io/docs/specification/describing-request-body/
> 
> Also, in my case, the third-party API generate swagger json by springfox-swagger automatically and it doesn't has a 'default' attribute in request body. It's a lot of work for me to modify the swagger json one by one.

The `default` keyword is supported by [JSON Schema](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00#rfc.section.9.2), which OpenAPI uses, and you can see more information in [Supported JSON Schema Keywords](https://swagger.io/docs/specification/data-models/keywords/).

We'd better keep its behaviors the same as the specifications. You can keep this special feature in your local version if you need to add it.

**Comment by Sumkor** [comment]
> The `default` keyword is supported by [JSON Schema](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00#rfc.section.9.2), which OpenAPI uses, and you can see more information in [Supported JSON Schema Keywords](https://swagger.io/docs/specification/data-models/keywords/).
> 
> We'd better keep its behaviors the same as the specifications. You can keep this special feature in your local version if you need to add it.

I know that the [Parameters](https://swagger.io/docs/specification/describing-parameters/) has the `default` keyword, but the `Request Body` doesn't has it. I do not think this is a special feature :)

**Pull request closed without merging**
