### PR TITLE
feat: support doubao llm function calling

### PR DESCRIPTION
**Pull request by sinomoe**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] manual test

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by laipz8200 — APPROVED** [review]
Great!
Thanks for your work.

**Comment by hulijiashaonian** [comment]
感谢你的努力！我试了一圈还是不知道怎么启用，我用doubao-pro-32k，依然只能是ReAct模式

**Comment by laipz8200** [comment]
> 感谢你的努力！我试了一圈还是不知道怎么启用，我用doubao-pro-32k，依然只能是ReAct模式

We just released this new feature. Make sure to update your Dify to version 0.6.11.

**Comment by qdaoming** [comment]
@sinomoe I have tried Doubao-pro-32K in v0.6.11, but it failed with message:
"FunctionCallPostProcessError message: model generated content is invalid."
Have you met such issue.

**Comment by sinomoe** [comment]
> @sinomoe I have tried Doubao-pro-32K in v0.6.11, but it failed with message: "FunctionCallPostProcessError message: model generated content is invalid." Have you met such issue.

It's an error generated by Ark, indicating that the model-generated content is not in a valid JSON format. Since dify used ark v2 api endpoint, there might be some compatibility issue, i will look into this ASAP

**Pull request merged**
