### PR TITLE
feat: add Vietnamese vi-VN

### PR DESCRIPTION
**Pull request by vigstudio**
# Description

Add Vietnamese language

Fixes # (issue)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
I have built and tested my activity locally

- [ ] TODO
- [x] dify/api/constants/languages.py
- [x] app-annotation.ts
- [x] app-api.ts
- [x] app-debug.ts
- [x] app-log.ts
- [x] app-overview.ts
- [x] app.ts
- [x] billing.ts
- [x] common.ts
- [x] custom.ts
- [x] dataset-creation.ts
- [x] dataset-documents.ts
- [x] dataset-hit-testing.ts
- [x] dataset-settings.ts
- [x] dataset.ts
- [x] explore.ts
- [x] layout.ts
- [x] login.ts
- [x] register.ts
- [x] share-app.ts
- [x] tools.ts

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [x] `optional` I have made corresponding changes to the documentation 
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [x] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by crazywoola** [comment]
@vigstudio FYI, you need to change this file as well.
https://github.com/langgenius/dify/blob/61e4bbabaf2758354db4073cbea09fdd21a5bec1/api/constants/languages.py#L5

**Comment by vigstudio** [comment]
> @vigstudio FYI, you need to change this file as well.
> 
> https://github.com/langgenius/dify/blob/61e4bbabaf2758354db4073cbea09fdd21a5bec1/api/constants/languages.py#L5

Yes! I will add it

**Comment by vigstudio** [comment]
Success @crazywoola

**Review by crazywoola — DISMISSED** [review]

**Comment by crazywoola** [comment]
There are some lint errors. Pls fix them.

```bash
./i18n/vi-VN/dataset-hit-testing.ts
10:24  Error: Missing trailing comma.  @typescript-eslint/comma-dangle
11:6  Error: Missing trailing comma.  @typescript-eslint/comma-dangle
18:24  Error: Missing trailing comma.  @typescript-eslint/comma-dangle
22:60  Error: Missing trailing comma.  @typescript-eslint/comma-dangle
25:34  Error: Missing trailing comma.  @typescript-eslint/comma-dangle
```

**Comment by vigstudio** [comment]
> ```shell
> typescript-eslint/comma-dangle
> ```

I fixed, sorry

**Review by crazywoola — APPROVED** [review]

**Comment by crazywoola** [comment]
Please head to https://discord.com/channels/1082486657678311454/1180843562829615174 if you are interested. :)

**Pull request merged**
