### PR TITLE
fix: z-index

### PR DESCRIPTION
**Pull request by ZuzooVn**
# Description

Fix the z-index bug
Fixes # (issue)

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?

Before:
 
Screenshot 2024-05-03 at 7 16 47 PM

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ZuzooVn** [comment]
@iamjoel is it ok?

**Comment by iamjoel** [comment]
> @iamjoel is it ok?
> 

z-index is ok. Others is not.

**Comment by ZuzooVn** [comment]
> > @iamjoel is it ok?
> 
> z-index is ok. Others is not.

what's other? if you require any modification from me, just let me know. Thanks

**Comment by iamjoel** [comment]
why  add  claasname mt-3.5

**Comment by ZuzooVn** [comment]
> why add claasname mt-3.5

I removed unused resource

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
