### PR TITLE
chore: refactor searXNG tool

### PR DESCRIPTION
**Pull request by hjlarry**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- integrate the searXNG's setting file to the repo, now the user no longer need to install/modify/restart container,  just one line command can start the service
- change the expose port to `8081`, the default weaviate always use the `8080`
- change the search results to json, and make the code more simple
- add more search type supplied by searXNG
- update the tutorial , see this PR https://github.com/langgenius/dify-docs/pull/207

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

test it locally

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by laipz8200 — APPROVED** [review]
LGTM

**Comment by XiaoLey** [comment]
Hi, @hjlarry .

I found that if the output of the searXNG tool is changed into json format, most tools will not be able to be used with the searXNG tool, because currently, the input of the tool cannot input json data.

Could you improve it? Thank you so much!

**Comment by XiaoLey** [comment]
@hjlarry 

I think we can temporarily change it like this:

image

How about it?

**Comment by hjlarry** [comment]
Hi  @XiaoLey   could you add  a `code` node or a `template` node to transform the json to text in your scenario ?

the origin response of searXNG is json,  for most scenarios, the search result will transfer to LLM,  and the LLM node can receive and understand the json format well.
if we transform it to string,  then in the scenario where we want to change the search result  we may need to change json back

**Comment by XiaoLey** [comment]
Yeah, your approach is indeed more reasonable. I'll try alternative solutions first until tools support inputting json 😀

**Pull request merged**
