### PR TITLE
feat: supports quick jump

### PR DESCRIPTION
**Pull request by TinsFox**
# Description

Added jump to specified page number for table

https://github.com/langgenius/dify/assets/33956589/99bed102-7a1b-4edc-b6ef-df19c0f3908e

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Added jump to specified page number for table

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by TinsFox** [comment]
Need to handle the situation of jumping to non-existent pages

**Comment by SuperevanZ** [comment]
Thanks for submitting the PR! This feature is really useful, but it looks a bit off visually. The pagination component itself has a lot of room for improvement, and we'll be designing it more comprehensively.

**Comment by TinsFox** [comment]
> Thanks for submitting the PR! This feature is really useful, but it looks a bit off visually. The pagination component itself has a lot of room for improvement, and we'll be designing it more comprehensively.

Do you mean the functional convenience or the visual aspect? Where can I find the design draft of dify 🤔

**Comment by takatost** [comment]
> Contributor

Hi @TinsFox, our designers are undergoing a major overhaul, and the pagination component is included. Our team will be responsible for developing and implementing it. Thank you very much for your contribution, and we are sorry that your PR conflicts with our design. We are unable to merge it at the moment.

**Pull request closed without merging**
