### PR TITLE
feat: support LLM process document file

### PR DESCRIPTION
**Pull request by hjlarry**
# Summary

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Currently, lots of LLM( gemini, sonnet ...) can directly process document,  and make user's chat context based on these documents. This PR aimed to support this feature in a dify agent app.  For the chatflow app,  maybe this [PR](https://github.com/langgenius/dify/pull/10679) can resolve.

#### Backend
-  add `DocumentPromptMessageContent` and more model features, copied from https://github.com/langgenius/dify/pull/10679
-  support gemini series models receive document
-  add `video` feature to support video models, `document` feature to support document models

#### Frontend
- add a switch button to control whether allow upload document
- for not support video feature's LLM,  open vision config will not allow upload video
- chat page whether display file upload button depends on `file.allowed_file_types` has any value

#### remaining issues
- the vision settings is strange,  `Resolution` only affect Image type files, `Upload Method` and `Upload Limit` affect all type files.

# Screenshots

image

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by laipz8200** [comment]
> the vision settings is strange, Resolution only affect Image type files, Upload Method and Upload Limit affect all type files.

I think this resolution config should be removed in the future.

**Comment by laipz8200** [comment]
Hi @hjlarry! #10679 is merged, could you please sync the code with the main branch?

**Comment by laipz8200** [comment]
https://github.com/user-attachments/assets/e4c34422-e458-4ddb-9e38-92cd72e1f350

**Comment by hjlarry** [comment]
> Screen.Recording.2024-11-22.at.5.56.05.PM.mov

seems the icon has been overwrite by the merge action, please try again

**Review by laipz8200 — APPROVED** [review]

**Pull request merged**
