### PR TITLE
Add GitHubOAuth and GoogleOAuth third-party logout functionality

### PR DESCRIPTION
**Pull request by LarryPage**
Add GitHubOAuth and GoogleOAuth third-party logout functionality

# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Add GitHubOAuth and GoogleOAuth third-party logout functionality

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

-After entering the dify platform, clicking logout on the page will trigger

### CODE REVIEW

**Comment by LarryPage** [comment]
Add GitHubOAuth and GoogleOAuth third-party logout functionality

**Comment by crazywoola** [comment]
Please fix the lint errors

**Comment by takatost** [comment]
Hi @LarryPage. What is the reason and purpose of developing this feature? Are there any risks to be avoided?

**Comment by LarryPage** [comment]
**Reason and Purpose:**

1.**Enhanced User Experience**: Adding GitHub OAuth and Google OAuth third-party logout functionality allows users to conveniently log out using their existing social accounts, eliminating the need to remember separate login states or perform additional logout steps within the application, thereby enhancing the overall user experience.
2.**Improved Security**: By leveraging the standard protocols provided by OAuth for logout, we can ensure the security of the logout process, reducing the risks associated with improper logout practices.
3.**Meeting Diverse Needs**: Different users may prefer using different social accounts for login and logout. Offering multiple options allows us to better cater to the diverse needs of our users.

**Risks to Avoid:**

1.**Data Leakage Risk**: When implementing third-party logout functionality, it is crucial to ensure that no user personal information or login states are inadvertently disclosed to third parties, especially emphasizing the secure storage and transmission of OAuth tokens.
2.**Reliance on Third-Party Services**: Utilizing third-party OAuth services means that our application becomes partially reliant on the stability and security of these services. Any issues with the third-party services could potentially impact the login and logout functionalities of our application.
3.**User Confusion Risk**: Users may experience confusion when using third-party logout, especially if they are unfamiliar with the OAuth process. Therefore, it is essential to provide clear guidance and instructions within the user interface.

In summary, the primary reason and purpose of developing this feature are to enhance user experience and security, as well as to meet the diverse needs of our users. At the same time, we must be mindful of and mitigate potential risks such as data leakage, reliance on third-party services, and user confusion.

**Comment by takatost** [comment]
> **Reason and Purpose:**
> 
> 1.**Enhanced User Experience**: Adding GitHub OAuth and Google OAuth third-party logout functionality allows users to conveniently log out using their existing social accounts, eliminating the need to remember separate login states or perform additional logout steps within the application, thereby enhancing the overall user experience. 2.**Improved Security**: By leveraging the standard protocols provided by OAuth for logout, we can ensure the security of the logout process, reducing the risks associated with improper logout practices. 3.**Meeting Diverse Needs**: Different users may prefer using different social accounts for login and logout. Offering multiple options allows us to better cater to the diverse needs of our users.
> 
> **Risks to Avoid:**
> 
> 1.**Data Leakage Risk**: When implementing third-party logout functionality, it is crucial to ensure that no user personal information or login states are inadvertently disclosed to third parties, especially emphasizing the secure storage and transmission of OAuth tokens. 2.**Reliance on Third-Party Services**: Utilizing third-party OAuth services means that our application becomes partially reliant on the stability and security of these services. Any issues with the third-party services could potentially impact the login and logout functionalities of our application. 3.**User Confusion Risk**: Users may experience confusion when using third-party logout, especially if they are unfamiliar with the OAuth process. Therefore, it is essential to provide clear guidance and instructions within the user interface.
> 
> In summary, the primary reason and purpose of developing this feature are to enhance user experience and security, as well as to meet the diverse needs of our users. At the same time, we must be mindful of and mitigate potential risks such as data leakage, reliance on third-party services, and user confusion.

Thank you very much for your patience, we will evaluate and test the feasibility of this program and get back to you ASAP!

**Comment by crazywoola** [comment]
Please resolve those conflicts.

**Pull request closed without merging**
