### PR TITLE
Deploy/dev

### PR DESCRIPTION
**Pull request by loks666**
# Description

When I was helping others deploy, I found that none of the services in Docker-compose do specify container_name, which results in docker automatically assigning a container name when Docker-Compose starts the container, which is usually "service name -1". This will misunderstand many people and cause them to misunderstand the problem

Fixes # (issue)

## Type of Change

- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

I add container_name to each service in docker-compose.yaml, whose value is the name of the service it is in, so that the container name will be the same as in the configuration file when started, to prevent misunderstandings for beginners

# How Has This Been Tested?

run "docker-compose up -d && docker ps -a"
You can view the service name without a suffix

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [x] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by loks666** [comment]
This is my first pr，so maybe I don't know some commit pr require，If I do it wrong，please tell me，I will be amend.

**Comment by crazywoola** [comment]
This seems to be a pretty big pull request. Please open a pull request from main branch not our dev branch.

**Comment by loks666** [comment]
I have a question, do I need to pull a new branch from the main branch, submit it to my fork project, fork the new branch of my project, and then submit pr to the main branch of dify? Or do I make changes on the main branch of my fork project and then commit pr to the main branch of my project from main to dify?

**Comment by crazywoola** [comment]
Before you make changes on your main branch, please sync the upstream dify main repo.
Then you can do modifications, after everything's done. Please open a pull request from you branch(maybe dev, maybe main) to our main branch.

**Pull request closed without merging**
