### PR TITLE
feat: add video、audio、abbr href message rendering and optimize image rendering

### PR DESCRIPTION
**Pull request by charli117**
# Checklist:
add video、audio、abbr href message rendering and optimize image rendering

1、Video：
```
<video controls><source src="https://acc.gz.cvte.cn/s3_dify_api/generate_files/ccx/PS&AI%E6%8F%92%E4%BB%B6.mp4" type="video/mp4">Photoshop AI Plus-in.mp4</video>
```
image

2、Audio
```
<audio controls><source src="https://dify.cvte.com/short/6kfQeYDxs12KGZ" type="audio/mp3">2ffdbfc7-d6bd-481a-a064-e9520f86078b.mp3</audio>
```
image

3、abbr href
```
[test](abbr:HelloDify)
```
image

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by charli117** [comment]
image

**Comment by charli117** [comment]
image
image

**Review by crazywoola — APPROVED** [review]

**Comment by bowenliang123** [comment]
It's great to see this feature finally merged~! Congrats, well done!

**Comment by charli117** [comment]
> It's great to see this long-awaited feature finally merged~! Congrats, well done!
@bowenliang123 [机智] Create more good features together to make Dify great

**Comment by AuditAIH** [comment]
@charli117  It's too useful, thank you very much. Then I have a small request: can ABBR be rendered as question options? Keep using the Dify question suggestions or options style uniformly, with each question as an independent small block, in blue hyperlink form for easy user understanding

image

**Pull request merged**
