### PR TITLE
embedded chatbot add reset session button

### LINKED ISSUE #5463: embedded chatbot  Need button to reset session
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

 saw #4054 asking a similar question. In iframe embedded mode. If the header is not displayed on the web page, there is no way to reset the session. You can only delete localstorage manually. Wish there was a button to reset the session.

### status quo
image

### expect
image

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by huixiangyang**
# Description

embedded chatbot add reset session button

before 
image

after 
image

Fixes #5463 

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [x] `optional` I have made corresponding changes to the documentation 
- [x] `optional` I have added tests that prove my fix is effective or that my feature works
- [x] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yanghx-git** [comment]
Is there any problem?

**Comment by crazywoola** [comment]
> Is there any problem? @zxhlyh @JzoNgKVO

This is under UI review. There might be a few changes.

**Comment by yanghx-git** [comment]
Hello, maybe this UI is not suitable, but the chatbot needs a reset button. Can it be optimized?

**Comment by crazywoola** [comment]
Hello, thanks again for this contribution. We have added a new UI for the reset button https://github.com/langgenius/dify/pull/6611
If you have further questions, please reach out to me via wechat: crazyphage

**Pull request closed without merging**
