### PR TITLE
feat: ops trace add llm model

### PR DESCRIPTION
**Pull request by ZhouhaoJiang**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

update workflow trace model name and provider
CleanShot 2024-08-15 at 16 31 40@2x

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by GarfieldDai — DISMISSED** [review]
LGTM

**Review by GarfieldDai — APPROVED** [review]
LGTM

**Comment by luca1024-web** [comment]
@ZhouhaoJiang  
I'm using the latest version but still have this problem. It's basically the same problem as this description, except that the charges just won't show up. Can you help me?
（Langfuse:v2.86.0
Dify:0.10.2）
image
image

**Comment by ZhouhaoJiang** [comment]
> @ZhouhaoJiang I'm using the latest version but still have this problem. It's basically the same problem as this description, except that the charges just won't show up. Can you help me?我使用的是最新版本，但仍然存在此问题。这与此描述基本相同，只是费用不会显示。你可以帮我吗？ （Langfuse:v2.86.0 （朗福斯：v2.86.0 Dify:0.10.2） Dify：0.10.2） image image

You can check the langfuse documentation to see if it supports automatic estimation of the consumption of the model you are using

**Comment by luca1024-web** [comment]
> > @ZhouhaoJiang我正在使用最新版本，但仍然有这个问题。这基本上与此描述的问题相同，只是费用不会显示。你能帮我吗？我使用的是最新版本，但仍然存在此问题。这与此描述基本相同，只是费用不会显示。你可以帮我吗？ （Langfuse:v2.86.0 （朗福斯：v2.0） 86.0 定义：0.10.2） 定义：0.10.2）图像 图像
> 
> 你可以查看 langfuse 文档，看看它是否支持自动估算你正在使用的模型的消耗

Thank you for your reply. I have reopened a [bug](https://github.com/langgenius/dify/issues/10253) with a detailed description, including the integrated 4o-mini, which also has the same problem. I look forward to your reply again.

**Pull request merged**
