### PR TITLE
web: bump Next.js to 14.0 for faster local server startup

### PR DESCRIPTION
**Pull request by bowenliang123**
- release notes of NextJs
  - 13.4: https://nextjs.org/blog/next-13-4
  - 13.5: https://nextjs.org/blog/next-13-5
  - 14.0: https://nextjs.org/blog/next-14
- As `App Router` has become stable since 13.4, the `experimental.appDir` is now removed.
- Noticeable speed improvement for starting local dev server with NextJs 13.5

A code running with `yarn dev`,

Before this PR on NextJs 13.3:
```
wait  - compiling /middleware (client and server)...
event - compiled client and server successfully in 290 ms (341 modules)
wait  - compiling /signin/page (client and server)...
event - compiled client and server successfully in 3.8s (2462 modules)
wait  - compiling...
event - compiled successfully in 458 ms (1278 modules)
wait  - compiling /(commonLayout)/apps/page (client and server)...
event - compiled client and server successfully in 5.3s (5942 modules)
wait  - compiling /(commonLayout)/datasets/page (client and server)...
event - compiled client and server successfully in 2.2s (5993 modules)
```

With this PR on NextJs 14.0:
```
 ✓ Compiled /middleware in 184ms (79 modules)
 ○ Compiling /signin ...
 ✓ Compiled /signin in 4.2s (1180 modules)
 ✓ Compiled in 600ms (571 modules)
 ○ Compiling /apps ...
 ✓ Compiled /apps in 1775ms (2586 modules)
 ○ Compiling /datasets ...
 ✓ Compiled /datasets in 503ms (2657 modules)
 ○ Compiling /explore/apps ...
 ✓ Compiled /explore/apps in 835ms (2760 modules)

```

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @crazywoola

**Comment by zxhlyh** [comment]
This change will cause an error in our dev environment, and some chunks cannot be loaded after the build. We will continue to monitor this issue.

**Comment by bowenliang123** [comment]
Thanks for the review and feedback. Considering 14.x is out, 13.5 should be good for production-ready itself. You may also paste the logs,  issues and screenshots, and let's see where the problem is from usage or from dependency conflicts.

**Comment by zxhlyh** [comment]
image

This problem is difficult to locate. On my computer, npm run build/docker build is normal. However, in our dev environment, it will report that some chunks cannot be loaded and the page cannot be loaded.

**Comment by bowenliang123** [comment]
Which page are you accessing, when this problem occurs?

**Comment by zxhlyh** [comment]
app overview

**Comment by bowenliang123** [comment]
Are you using `yarn install` to prepare packages? If you removed the lock files of npm and yarn, whether it helps?

**Comment by bowenliang123** [comment]
It sounds like you've gone through the CI/CD with `next build` to build production files for your dev environment. Can you check the targeted files ever existed on that machine after deployment?

**Comment by zxhlyh** [comment]
I tried 14.0.4 and everything worked fine.

**Comment by bowenliang123** [comment]
> I tried 14.0.4 and everything worked fine.

Wow, that's much out of my surprise.

First, have tried 14.0.4 locally on my machine, it failed to start local dev server.
Second, according to the official migration guide, these codemodes for v14 should be applied, https://nextjs.org/docs/pages/building-your-application/upgrading/codemods#140, which should impact our existed code.

Have you tried locally and on the dev environment?

**Comment by bowenliang123** [comment]
Shall we change it to 14.0.4? I tried again locally, it works fine.

**Comment by bowenliang123** [comment]
Would you like to try this again ?
1. changed target version to 14.0.4
2. applied codemods of 14, converting viewport in metadata to exporting viewport object, https://nextjs.org/docs/app/api-reference/functions/generate-viewport#viewport-fields
3. rebased on to latest commit of master branch

**Comment by zxhlyh** [comment]
We will test it in the dev environment for a few days to make sure there is no problem before merging it into the main branch.
Thank you.

**Comment by bowenliang123** [comment]
No problem. Thanks.

**Review by zxhlyh — APPROVED** [review]

**Pull request merged**
