### PR TITLE
chore: transform the files from dict to File when draft run single tool node

### PR DESCRIPTION
**Pull request by hjlarry**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

| draft run single tool node | draft run entire workflow |
| --- | --- |
| 96183ada4a4cc1458aadddcb178386c| e1fc46a8988b5a1d750736eda6cfbdf|

this inconsistent behavior should be fixed for debug or develop a tool

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

test locally

- [x] Test local file draft run
- [x] Test remote file draft run

### CODE REVIEW

**Comment by laipz8200** [comment]
Oh... sorry about that. Are you interested in modifying the structure of the front-end request?

**Comment by hjlarry** [comment]
> Oh... sorry about that. Are you interested in modifying the structure of the front-end request?

it doesn't matter.  I think your PR is resolved this problem,  also require to modify the front-end?

**Comment by laipz8200** [comment]
> also require to modify the front-end?

Yes, in the single step run of the tool node, the file structure being passed isn't as expected. It should be the same as the file in the LLM node.

**Comment by laipz8200** [comment]
Sorry, please just ignore it. Our team members will take care of this.

**Comment by hjlarry** [comment]
> Sorry, please just ignore it. Our team members will take care of this.

OK, looking forward to it

**Pull request closed without merging**
