### PR TITLE
feat: install app from remote

### PR DESCRIPTION
**Pull request by perzeuss**
# Description

I am building DifyShare, a platform to share Dify apps. To allow importing them with a button click from DifyShare, this PR introduces the ability to install apps from an url. This functionality can be used for other scenarios too.

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
I tested it locally. To test it manually:
- Configure beta.difyshare.com as allowed host by adding this to the .env for the web app: `APP_IMPORT_FROM_REMOTE_ALLOWED_HOSTS="beta.difyshare.com"`
- Visit the Dify Studio (navigate to /apps)
- Add `?action=installApp&remoteInstallUrl=https://beta.difyshare.com/api/flow/663ffe78002cf37178fa/download` to the URL
- Open the URL
  - A loading spinner should be rendered with a message in the users locale
  - The Chatflow from DifyShare should succeed and you see the workflow editor

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
Has Dify been registered as the trademark? Is it legal and compliant to use it in a third-party sharing platform like DifyShare in this case ?
There is no mentioning of Dify as a trademark or the disclaimer for the irrelevance between Dify and DifyShare on terms of service at https://difyshare.com/terms-of-service.

**Comment by bowenliang123** [comment]
This PR integrates DifyShare into Dify, which violates the Terms of Service of DifyShare (https://difyshare.com/terms-of-service) itself. The `Disclaimer` part of the ToS of DifyShare is weak, only mentioning separated operation for Dify and DifyShare.
Also, this PR leads to a penetration consequence that all the Dify users over SaaS and community users use DifyShare in some way, forcing it to follow the Acceptence of ToS of DifyShare.

**Comment by perzeuss** [comment]
Hello @bowenliang123, thank you for your feedback. I'll remove the DifyShare URL from the `web/.env.example` file.

**Comment by bowenliang123** [comment]
Btw, has `Dify` been registered as a registered trademark or listed as an unregistered trademark by law?

**Pull request closed without merging**
