### PR TITLE
fix: populate app configs to system environment variables

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- set the configs read from `.env` to system env variables, for the packages relies on  env variables rather than reading configs from flask app's config.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by laipz8200** [comment]
Hello, Bowen! We need to know which packages need to read our configurations from the system environment variables. Could you give us a more specific example?

**Comment by bowenliang123** [comment]
Hi, @laipz8200 thanks for your attention to this PR, which is raised for :

1. before the removal the `config.py` in #5507, there's one line to populate all the configs from the .env file to system env vars. see https://github.com/langgenius/dify/pull/5507/files#diff-0e3026d2737181f937735ba5e2023ce7f39a7762c8c2594670f4a944a7e48eafL33
```
dotenv.load_dotenv()
```

This PR helps to leverage the same efforts to the original behaviours.

2. some users may does use the `.env ` file to set some env vars for the package. eg. setting `CO_API_URL` as the base URL for `cohere` package, which is not directly used in Dify.

**Comment by laipz8200** [comment]
@bowenliang123 Since `DifyConfig` is read from the `.env` file, I think we can just use `dotenv.load_dotenv()` here like we did before.

**Comment by bowenliang123** [comment]
I would prefer not to reverse couple with the raw dotenv again. For the following reasons,
1. the configs in DifyConfig is ensured for validation in types and range
2. `dotenv.load_dotenv` method has a implicit file path for `.env`, if we want to change it in future, it's better to make sure it's aligned with `pydantic-settings`.
3. Further more `pydantic-settings` provides various features for arranging the proper order and choices for config sources, like `pyproject.toml`, JSON files, env files and etc.
4. No benefits or contribution from reusing the `dotenv.load_dotenv` , it does replicate the configs into system env vars in `set_as_environment_variables` method by using `os.environ[k] = v`

**Review by laipz8200 — APPROVED** [review]
Sure, let's merge this first.

**Comment by bowenliang123** [comment]
Thanks.

**Pull request merged**
