### PR TITLE
chore: add .env.example and update docker-compose.yaml

### LINKED ISSUE #5249: [Enhancement] Optimization of the docker-compose.yaml file
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I tried to deploy using docker-compose, modifying environment variables in the complex YAML file was a painful task, and it also faced merge issues after git updates.

### 2. Describe the feature you'd like to see

1. Please move the variable values from the YAML file to a .env file. You can provide a .env.template file that contains default values, so we can copy it to create our own .env file. This way, when the repository is updated, we will only pull the .env.template file, and our local deployment won't conflict with its changes.
2. In the same docker-compose.yaml file, try to reduce configuration errors by reusing anchors to minimize repetitive configurations (especially for the current API and worker services, which share many identical variables). [Reference](https://docs.docker.com/compose/compose-file/11-extension/).
```yaml
x-shared-env: &default-env
  environment:
    ENV2: common_value_2
    ENV3: common_value_3

services:
  service_api:
    image: some_image:latest
    environment:
      <<: *default-env
      MODE: api

  service_worker:
    image: some_image:latest
    environment:
      <<: *default-env
      MODE: worker
```
3. In the current deployment architecture, some pre-configured content (such as the nginx configuration and the contents of the two pre-set volumes) needs to be directly operated on the server. Firstly, it's inconvenient to git clone/pull the code on the server. Secondly, it makes it difficult to deploy using container management tools (such as Portainer). I hope these parts can be optimized through some mechanism.

### 3. How will this feature improve your workflow or experience?

Deployment and maintenance should both become more convenient.

### 4. Additional context or comments

_No response_

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by Tian-Hun**
# Description

- Added .env.example file to provide a template for environment variable configuration.
- Modified docker-compose.yaml to streamline configuration management by using environment variables.

Fixes #5249

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

To verify the changes introduced in this pull request, the following tests were performed:

1. **Environment Variable Validation:**
   - **Description:** The updated `docker-compose.yaml` now references environment variables from the new `.env.example` file. These environment variables were set with representative values in a local `.env` file to ensure that the Docker Compose services start up correctly and can access the necessary configuration.
   - **Reproduction:**
     1. Create a `.env` file in the same directory as `docker-compose.yaml`.
     2. Populate the `.env` file with the values for your environment variables (following the structure provided in `.env.example`).
     3. Run `docker-compose up` to start the services.
     4. Verify that the services start without errors and that the environment variables are correctly loaded by checking the logs or accessing the application.

2. **Configuration File Validation:**
   - **Description:** The modified `docker-compose.yaml` file was manually reviewed to ensure that all environment variable references are correct and that the overall configuration structure aligns with the intended changes.
   - **Reproduction:**
     1. Examine the `docker-compose.yaml` file and verify that all environment variable placeholders (e.g., `${VARIABLE}`) are replaced with the correct values from your `.env` file.
     2. Check that the structure of the configuration file (service definitions, volume mounts, etc.) is valid and makes sense for your setup.

**Test Configuration:**

* **Environment:** Local development environment
* **Docker Compose Version:** `v2.15.1`
* **Operating System:** `macOS Sonoma 14.5`

**Additional Notes:**

* Depending on the complexity of your application and its dependencies, you might need to conduct more thorough testing. This could include functional tests, integration tests, or performance tests.
* If the changes involve external services (e.g., cloud storage, databases), ensure those services are available and configured correctly during testing.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by crazywoola — COMMENTED** [review]
This is a good pr, but you need to move the comments to `.env.examaple` as well.

**Comment by crazywoola** [comment]
See this one as well https://github.com/langgenius/dify/pull/4299

**Review by crazywoola — DISMISSED** [review]

**Comment by Tian-Hun** [comment]
Hi @takatost, @guchenhe, and @crazywoola , 👋

I'd really appreciate it if you could take a few minutes to look over this PR. Your feedback is invaluable to me! 🙏

**Comment by perzeuss** [comment]
Hi @Tian-Hun, great to see a new contributor! I have some feedback I want to share.

It is a good idea to de-duplicate entries, but I think moving some variables to a `.env` file while others have to be configured in the `docker-compose.yaml` introduces problems. It creates two different ways to configure Dify and introducing a .env.example file instead of leaving the default values ready to go adds a manual step to the setup process that is not required. I like the effort you invested to add documentation about the .env.example file but why not place a .env instead? Users will have to overwrite defaults in the `docker-compose.yaml` anyways.

It will make it more complicated to help users set up Dify if we need to check whether a variable is in a `.env` file or defined in `docker-compose.yaml`. It will confuse people who read GitHub issues/discussions about how to configure Dify if they follow instructions to configure things in the `docker-compose.yaml` file and then find that the required environment variables for a service are no longer in the service section but at the top of the file, and then realize there also needs to be a `.env` file for it.

I think if we refactor it this way, we should move all variables to `.env` files to only have the .env files as place to configure the services. I discussed this with @guchenhe a month ago, and here is an example I made to show how it could be done: https://github.com/perzeuss/dify/commit/893c9e86beee7f84bfc97a5dba760ad16d2a988c#diff-89fafc265c1fa601cf2364b20be83308031335fda9467fcf3249d5ec1c0c8172

Let me know what you think about my thoughts. By the way, thanks for taking the time to contribute!

**Comment by Tian-Hun** [comment]
Hi @perzeuss,

Thank you for your valuable feedback! I understand your concern about introducing two different ways to configure Dify.

The initial intention of splitting environment variables was to streamline the setup process for new users. By separating frequently changed and personalized variables into a .env file, we aimed to simplify initial deployment and focus their attention on essential configurations.

Additionally, by keeping the .env file out of version control and providing an .env.example template, we enable users to customize their local environments without worrying about conflicts when pulling updates from the repository. This streamlined workflow is crucial for a smooth user experience.

While centralizing all variables in .env files offers consistency, it's important to weigh this benefit against the potential for merge conflicts and the added complexity it might introduce for users who need to manage custom configurations.

I propose we explore a hybrid approach that combines the best of both worlds. We could keep essential, non-sensitive variables in the docker-compose.yaml file for easy reference and move more personalized or sensitive variables to .env files. This would maintain the convenience of a single configuration location for common settings while leveraging the flexibility and conflict resolution benefits of .env files for user-specific customizations.

I'm confident that by collaborating and considering all perspectives, we can find an optimal solution that prioritizes both user-friendliness and maintainability.

Thank you again for your insights and for taking the time to contribute to this discussion!

**Pull request closed without merging**
