### PR TITLE
fix: Azure OpenAI o1 max_completion_token and get_num_token_from_messages error

### LINKED ISSUE #9325: Azure OpenAI o1 max_completion_token and get_num_token_from_messages error
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Add Azure OpenAI o1-preview and o1-mini will shows the error below:
Screenshot 2024-10-14 at 11 22 29 AM

If you change the code to use max_completion_token and updated openai lib version, will get the error below:
Screenshot 2024-10-14 at 4 21 57 PM

### ✔️ Expected Behavior

Able to use Azure o1-preview and o1-mini in Dify

### ❌ Actual Behavior

Error occurs

### LINKED ISSUE #9327: use azure o1-mini o1-preivew model save error and use chat error
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1.add o1-mini o1-preivew model in azure save error 
error msg:Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
 param temperature=0,max_tokens=20 not support

2.use o1-mini o1-preivew error
_num_tokens_from_messages use tiktoken 0.7.0 not support o1 model 0.8.0support

### ✔️ Expected Behavior

azure o1 model use

### ❌ Actual Behavior

error and can't use

### PR DESCRIPTION
**Pull request by somethingwentwell**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes #9325 
Fixes https://github.com/langgenius/dify/issues/9327

- Upgrade openai to at least 1.45.0
- Upgrade tiktoken to at least 0.8.0
- Add validate_credentials for o1 in dify/api/core/model_runtime/model_providers/azure_openai/llm/llm.py

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [x] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Build the api image and run again. Add Azure OpenAI o1-preview and o1-mini and test with an agent
Screenshot 2024-10-14 at 5 55 57 PM

### CODE REVIEW

**Review by laipz8200 — CHANGES_REQUESTED** [review]
Please do not touch the files under `/docker`

**Comment by somethingwentwell** [comment]
> Please do not touch the files under `/docker`

Done

**Comment by crazywoola** [comment]
Please

**Comment by somethingwentwell** [comment]
> Please fix the tests

Done, new version of openai moderations require category_applied_input_types and illicit & illicit/violent, so edited api/tests/integration_tests/model_runtime/__mock/openai_moderation.py

**Review by laipz8200 — APPROVED** [review]
Thank you!

**Comment by yanzu888** [comment]
Hello, if I am deploying using Docker, how can I handle this issue? Thank you for your answer.

**Comment by laipz8200** [comment]
> Hello, if I am deploying using Docker, how can I handle this issue? Thank you for your answer.

Just wait for our next release :)

**Comment by yanzu888** [comment]
> > Hello, if I am deploying using Docker, how can I handle this issue? Thank you for your answer.
> 
> Just wait for our next release :)

okay, thank you

**Comment by somethingwentwell** [comment]
> Hello, if I am deploying using Docker, how can I handle this issue? Thank you for your answer.

You can also build the api and web image and replace your custom image to the docker compose yml and run it

**Pull request merged**
