### PR TITLE
fix: In the output, the order of 'ta' is sometimes reversed as 'at'. #8015

### LINKED ISSUE #8015: In the output, the order of 'ta' is sometimes reversed as 'at'.
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Use an open-source model like Qwen2-70B-Instruct
- Apply agent framework in ReAct mode
Then, in the output, the order of 'ta' is sometimes reversed as 'at'.
image
image

### ✔️ Expected Behavior

Correct order of the output alpabets, especially for 'a' and 't'.

### ❌ Actual Behavior

The order of 'ta' is sometimes reversed as 'at'.
image
image

### PR DESCRIPTION
**Pull request by wsbao**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Close issue syntax: `Fixes #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

Fixes https://github.com/langgenius/dify/issues/8015

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Please refer to the issue #8015

### CODE REVIEW

**Comment by crazywoola** [comment]
Please run fix the lint error in CI and remove unused code.

**Comment by wsbao** [comment]
> Please run fix the lint error in CI and remove unused code.

I ran dev/reformat without installing ruff and dotenv-linter. This time I installed these two missing commands, re-ran dev/format, and committed the code. All ruff checks passed though dotenv-linter identified 96 problems in './web/.env.example' that I did not touch.

**Comment by wsbao** [comment]
How long does it still need to take for the approving review?

**Comment by crazywoola** [comment]
I have DM @laipz8200  to review this one.

**Review by crazywoola — APPROVED** [review]
LGTM

**Comment by wsbao** [comment]
How soon will it be merged to the main branch? In which official version, do you plan to have this bug removed?

**Comment by wsbao** [comment]
How soon will it be merged to the main branch? In which official version do you plan to have this bug removed?

**Comment by laipz8200** [comment]
Sorry for the long wait, this fix will be checked soon.

**Pull request merged**
