### PR TITLE
chore: merge lint-staged script

### PR DESCRIPTION
**Pull request by TinsFox**
# Description

Merge lint-staged script

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by bowenliang123** [comment]
The title and the description emphasize the key change is `merging` eslints options, while `prettier` linter action is introduced for the js scripts as well. Is it the main purpose and what's impact of the PR ? If `prettier`  is introduced for lining, how does it aligned to the automated style checks?

**Comment by TinsFox** [comment]
> prettier

Sorry, I forgot to remove the `prettier` script before submitting.

**Comment by TinsFox** [comment]
> The title and the description emphasize the key change is `merging` eslints options, while `prettier` linter action is introduced for the js scripts as well. Is it the main purpose and what's impact of the PR ? If `prettier` is introduced for lining, how does it aligned to the automated style checks?

Sorry, I forgot to remove the `prettier` script before submitting.

**Comment by bowenliang123** [comment]
> > The title and the description emphasize the key change is `merging` eslints options, while `prettier` linter action is introduced for the js scripts as well. Is it the main purpose and what's impact of the PR ? If `prettier` is introduced for lining, how does it aligned to the automated style checks?
> 
> Sorry, I forgot to remove the `prettier` script before submitting.

Thanks for the reply. Let's know when the changes are ready.

**Comment by takatost** [comment]
This PR includes additional file submissions, so I'm closing it for now. Please resubmit later.

**Pull request closed without merging**
