### PR TITLE
Add ECharts feature ( #6385 )

### LINKED ISSUE #6385: In Chatflow, how to embed custom EchArts JS code to render charts
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I created a chatflow. There is also a defined tool for querying the process that returns some data to me. I'd like to be able to use my custom ECHART js code in the chat window to display this data as a chart. What should I do?

### 2. Additional context or comments

echarts code like : (https://echarts.apache.org/examples/en/editor.html?spm=5176.28103460.0.0.4c4a3da2h42BFW)
import * as echarts from 'echarts';

var chartDom = document.getElementById('main');
var myChart = echarts.init(chartDom);
var option;

option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};

option && myChart.setOption(option);

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by zhujinle**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description
Close #6385 
Added support for drawing with ECharts during output, which can directly output interactive images.
Use Json format for transmission in Markdown, just convert the information in `option` into json format and pass it in.
cd52fde1603be31ce6db8a970a5be56

Example:
<details><summary>Code</summary>
<pre><code>
```echarts
{
  "xAxis": {
    "type": "category",
    "data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  "yAxis": {
    "type": "value"
  },
  "series": [
    {
      "data": [120, 200, 150, 80, 70, 110, 130],
      "type": "bar",
      "showBackground": true,
      "backgroundStyle": {
        "color": "rgba(180, 180, 180, 0.2)"
      }
    }
  ]
}
```
</code></pre>
</details>

For a more complex interactive ECharts chart, you can use the following code to test it:
<details><summary>Code</summary>
<pre><code>
```echarts
{
    "title": {
        "textStyle": {
            "align": "center",
            "color": "#fff",
            "fontSize": 20
        },
        "top": "3%",
        "left": "10%"
    },
    "backgroundColor": "#0B1346",
    "grid": {
        "top": "25%",
        "bottom": "10%"
    },
    "tooltip": {
        "trigger": "axis",
        "axisPointer": {
            "type": "shadow",
            "label": {
                "show": false
            }
        }
    },
    "legend": {
        "data": [
            "库存",
            "需求"
        ],
        "top": "15%",
        "textStyle": {
            "color": "#ffffff"
        }
    },
    "xAxis": {
        "data": [
            "C15喷射",
            "C25组",
            "C36水泵送",
            "C85补偿收缩"
        ],
        "axisLine": {
            "show": true,
            "symbol": [
                "none",
                "arrow"
            ],
            "lineStyle": {
                "color": "#CBDDF4"
            }
        },
        "axisTick": {
            "show": true
        },
        "axisLabel": {
            "show": true,
            "rotate": 0,
            "textStyle": {
                "color": "#CBDDF4"
            }
        }
    },
    "yAxis": [
        {
            "type": "value",
            "splitLine": {
                "show": true
            },
            "axisTick": {
                "show": false
            },
            "axisLine": {
                "show": true,
                "symbol": [
                    "none",
                    "arrow"
                ],
                "lineStyle": {
                    "color": "#CBDDF4"
                }
            },
            "axisLabel": {
                "show": true,
                "textStyle": {
                    "color": "#BADBFB"
                }
            }
        }
    ],
    "series": [
        {
            "name": "库存",
            "type": "bar",
            "barWidth": 15,
            "smooth": true,
            "showAllSymbol": true,
            "symbol": "circle",
            "itemStyle": {
                "normal": {
                    "color": "#6392F4"
                }
            },
            "data": [
                1,
                2,
                3,
                2
            ]
        },
        {
            "name": "需求",
            "type": "line",
            "barWidth": 15,
            "showSymbol": true,
            "symbolSize": 10,
            "itemStyle": {
                "normal": {
                    "color": "#80BD95"
                }
            },
            "data": [
                4,
                4,
                4,
                4
            ]
        }
    ]
}
```
```
</code></pre>
</details>

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
Tested using the above code

- [x] Test B

### CODE REVIEW

**Comment by crazywoola** [comment]
image
It seems not stable to render a proper echarts

**Comment by zhujinle** [comment]
> image It seems not stable to render a proper echarts

Sorry, I made a mistake when copying and gave an incorrect code example. The parameter settings of this example do not meet the ECharts specification requirements so it cannot be rendered.
Can you try the following example or the second example I gave above? I have tested these two locally and they are OK.

<pre><code>
```echarts
{
  "xAxis": {
    "type": "category",
    "data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  "yAxis": {
    "type": "value"
  },
  "series": [
    {
      "data": [120, 200, 150, 80, 70, 110, 130],
      "type": "bar",
      "showBackground": true,
      "backgroundStyle": {
        "color": "rgba(180, 180, 180, 0.2)"
      }
    }
  ]
}
```
</code></pre>
image

**Review by crazywoola — APPROVED** [review]

**Comment by baiyi-os** [comment]
怎样才能百分百的输出echarts图表

**Comment by yuming-L** [comment]
How can we save and download the output echarts chart so that it can be used by subsequent nodes?

**Comment by zhujinle** [comment]
> How can we save and download the output echarts chart so that it can be used by subsequent nodes?

Just use Built-in function  "saveAsImage"

FYI:
<details><summary>Code</summary>
<pre><code>
```echarts
{
	"xAxis": {
		"type": "category",
		"data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
	},
	"yAxis": {
		"type": "value"
	},
	"series": [{
		"data": [120, 200, 150, 80, 70, 110, 130],
		"type": "bar",
		"showBackground": true,
		"backgroundStyle": {
			"color": "rgba(180, 180, 180, 0.2)"
		}
	}],
	"toolbox": {
		"show": true,
		"right": 50,
		"feature": {
			"saveAsImage": {
				"show": true,
				"title": "保存为图片"
			}
		}
	}
}
```
</code></pre>
</details>

**Pull request merged**
