### PR TITLE
Fix mermaid render

### LINKED ISSUE #6087: [mermaid] fix pr #6004
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The pr #6004 had bug for pie type.
Those issue is open for open a new pr to fix it.

For thoose code

```js
```mermaid
%%{init: {"theme":"dark"}}%%
pie
    title "专利类型分布"
    "发明公开" : 1794
    "发明授权" : 325
    "实用新型" : 661
```
```

not working

### ✔️ Expected Behavior

mermaid pie render 

### ❌ Actual Behavior

mermaid pie not render

### PR DESCRIPTION
**Pull request by jqhr**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Close #6087

The bug reason is for check whether svg is empty.
But result in render pie. So I removed thoose code

## Type of Change

- [x] Bug fix (#6087)

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

### CODE REVIEW

**Review by crazywoola — CHANGES_REQUESTED** [review]
Removal of this part will cause the render process flicker. I think there might be a better way to solve it.

**Comment by jqhr** [comment]
Ok. I will try other solutions.

**Comment by jqhr** [comment]
See 085a1463f2fd5ac69ae0de0774f98bc3ff308629.
May helpful

**Review by crazywoola — APPROVED** [review]
Looks great to me.

**Comment by michaelxu1107** [comment]
Hello, i am using dify version 0.6.14
I am using dify to generate mermaid pie chart, but it cannot show pie, i copied pie code to https://mermaid.live/edit, it does show pie chart, the process i do and error output is list as below:
1、input message
9a2888476948460206370bb8d811d42
2、click svg button to check mermaid code
2550a9e44849a762936b601aa657036
3、i added log in web/app/components/base/mermaid/index.tsx, it shown error msg as below
ReferenceError: structuredClone is not defined
c8da1283e00965a23917a1b5697d997

**Comment by jqhr** [comment]
> Hello, i am using dify version 0.6.14 I am using dify to generate mermaid pie chart, but it cannot show pie, i copied pie code to https://mermaid.live/edit, it does show pie chart, the process i do and error output is list as below: 1、input message 9a2888476948460206370bb8d811d42 2、click svg button to check mermaid code 2550a9e44849a762936b601aa657036 3、i added log in web/app/components/base/mermaid/index.tsx, it shown error msg as below ReferenceError: structuredClone is not defined c8da1283e00965a23917a1b5697d997

Your nodejs version is ?

**Comment by michaelxu1107** [comment]
nodejs version is 20.12.2, mermaid version is 10.4.0



---- Replied Message ----
| From | Jinq ***@***.***> |
| Date | 07/26/2024 07:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [langgenius/dify] Fix mermaid render (PR #6088) |

Hello, i am using dify version 0.6.14 I am using dify to generate mermaid pie chart, but it cannot show pie, i copied pie code to https://mermaid.live/edit, it does show pie chart, the process i do and error output is list as below: 1、input message 2、click svg button to check mermaid code 3、i added log in web/app/components/base/mermaid/index.tsx, it shown error msg as below ReferenceError: structuredClone is not defined

Your nodejs version is ?

**Comment by jqhr** [comment]
I cannot reproduce this bug.
Maybe your browser not support structuredClone. See [StructuredClone MDN](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

**Comment by michaelxu1107** [comment]
i upgrade my chrome, and it is solved, thank you for your reply



---- Replied Message ----
| From | Jinq ***@***.***> |
| Date | 07/29/2024 08:59 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [langgenius/dify] Fix mermaid render (PR #6088) |

I cannot reproduce this bug.
Maybe your browser not support structuredClone. See StructuredClone MDN

**Pull request merged**
