### PR TITLE
test: add unit tests for vector stores of Milvus, Qdrant and Weaviate

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- add unit tests for vector stores
  - weaviate
  - qdrant
  - milvus
- downgrade `pymilvus` to `2.3.1` (<2.3.2), reverting `create_collection` to `create_collection_with_schema` usage

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @JohnJyong @takatost

**Comment by takatost** [comment]
If we need to add unit testing, please mock the vdb client interface.
If we really need integration testing, I don't think the test time and resource consumption are suitable to be placed here.

**Comment by bowenliang123** [comment]
If we regard the docker-compose file for middleware (including vector stores) as deliverables and artifacts of the release , the integration tests are strongly suggested. As in recent case, unexpected dropped API in `pymilvus` 2.3.2+ greatly impacts the user running Miluvs 2.3.0 with docker compose file.

I would suggest to do it in a trade-off deal:
1. skip CI tests on Python 3.11, saving approximately 5min execution time
2. adopt the uts on VDBs, costing about 30s for starting the targeted vdbs
3. move the ut on VDBs to CI test before releasing, in the future.

**Review by takatost — APPROVED** [review]
LGTM

**Pull request merged**
