### PR TITLE
fix: Count exception occurs when searching conversations

### LINKED ISSUE #7964: logs list doesn't maintain a consistent count across pages
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.7.3 & cloud version

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. Navigate to the /<app_id>/logs page.
2. Enter a simple keyword, for example, 1.
3. The number of results across different pages will not maintain a consistent count.

### ✔️ Expected Behavior

Should be a consistent count acrocss different pages

### ❌ Actual Behavior

Not a consistent count

### PR DESCRIPTION
**Pull request by Gaocarri**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

count-error

When using keyword to query conversations, multiple messages with unique conversation.id will be queried, resulting in an incorrect number of final query results (less than limit: 10)

Fix: #7964 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by Gaocarri** [comment]
@laipz8200 hey, could u review it ?

**Comment by laipz8200** [comment]
I can confirm that this is a bug. However, adding a group by clause might lead to performance issues, so we need to run some tests.

**Comment by Gaocarri** [comment]
> I can confirm that this is a bug. However, adding a group by clause might lead to performance issues, so we need to run some tests.我可以确认这是一个错误。然而，添加一个 group by 子句可能会导致性能问题，因此我们需要进行一些测试。

ok , if it has performance issues plz let me know the results

**Comment by Gaocarri** [comment]
> I can confirm that this is a bug. However, adding a group by clause might lead to performance issues, so we need to run some tests.

ok, if it has  performance issues plz let me know the results

**Review by laipz8200 — APPROVED** [review]
LGTM

**Comment by laipz8200** [comment]
@Gaocarri Thank you for your contribution!

**Pull request merged**
