### PR TITLE
Add workflow translations for ja-JP

### PR DESCRIPTION
**Pull request by Hirosa0**
# Description

Added `workflow` translations to the `ja-JP` i18n file. This change ensures that workflow-related texts are displayed in Japanese.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

The changes were verified using the following steps:
1. Ran `npm run check-i18n` to check for missing i18n keys.
2. Confirmed that the `ja-JP` translations for `workflow` were correctly added.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Comment by asemandeveloper** [comment]
Dear friend
You added the Japanese language to the project. Please tell me what should I do to add Arabic language to the project?
I want to do it locally on my computer first and then share it if there is no error.
My computer's operating system is Windows 11.

**Comment by Hirosa0** [comment]
I did the translation in ja-JP in the web/i18n directory.
The part to be translated was decided based on the information from the en-US changes of i18n in v0.6.9.

Specific instructions can be found in the CONTRIBUTING file in the Dify repository and in the i18n-contributors section of the official Dify Discord.

**Comment by asemandeveloper** [comment]
Thank you
I did what you said
But by going into web folder and executing docker build, I don't see any changes when running the project in docker desktop!

If possible, tell me step by step what to do.
The operating system is Windows 11.

**Comment by Hirosa0** [comment]
oh,I see.

Actually, I faced such a problem too.

There are solutions to that issue in the community, but I confirmed that the check-i18n command worked correctly (because updating the docker image is a hassle and the image seemed to be reflected once updated if the command worked as per the procedure), so I went straight to the PR I created the PR as it was.

As a result, the change was reflected correctly in 0.6.10, so at least there is no problem if check-i18n does not produce any errors.

**Comment by Hirosa0** [comment]
The reason for the bug that such language changes are not applied when done locally is that the docker-compose.yaml file uses image: langgenius/dify-api:0.6.10 and does not reference the local file.

**Comment by Hirosa0** [comment]
1. fork the repository
2. identify the part to be translated (as per the contents of the first reply)
3. process the translation
Execute the check-i18n command from the CLI after the translation process is complete 4.
5. if there are any omissions, correct them
6. commit -> push -> send PR

I did this process.

**Comment by Hirosa0** [comment]
If you have other questions in the future, we encourage you to use the Discord community.
The other developers and the people responsible for Dify will be happy to answer your questions.

**Comment by crazywoola** [comment]
@asemandeveloper 
I was going to add Arabic language, but there are some limitations, since Arabic language starts from left to right. So it will break the UI somehow, and we haven't got a plan to do this.

**Pull request merged**
