### PR TITLE
fixed: code_node is not compatible with previous versions

### PR DESCRIPTION
**Pull request by luckylhb90**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

0.10.2 
After upgrading to version 0.10.2, the original app did not execute properly, which caused compatibility issues with the historical version.

I am not very clear, at that time to increase the specific scenario of this judgment, theoretically the user should be able to pass None of the data to it, should not limit the user's input.

image

 0.9.1, this app will work.
image

Fixes 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by laipz8200** [comment]
This issue was caused by the overly lenient validation in the old version. In the new version, you'll need to use an aggregator node at the branch convergence points to ensure that subsequent variables are present.

**Comment by luckylhb90** [comment]
This will cause existing apps to be unavailable.

**Comment by laipz8200** [comment]
> This will cause existing apps to be unavailable.

Sure, but we can’t leave this bug in place as it might cause more unexpected behavior. You might want to downgrade to version 0.9.2 until you’re able to adjust your workflow.

**Comment by luckylhb90** [comment]
> > This will cause existing apps to be unavailable.
> 
> Sure, but we can’t leave this bug in place as it might cause more unexpected behavior. You might want to downgrade to version 0.9.2 until you’re able to adjust your workflow.

However, for the configuration like my screenshot, I can obviously solve this problem in the code, but now we need to configure a more complex process, is this not appropriate?

**Pull request closed without merging**
