### PR TITLE
Feat: Workflow Knowledge Retrieval Node Support: Dynamic Dataset ID List Configuration and Document Metadata Filtering

### PR DESCRIPTION
**Pull request by wangiii**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

## Feat
Workflow Knowledge Retrieval Node Support:
1.  Dynamic Dataset ID List Configuration
2. Document Metadata Filtering (Currently only supports qdrant vector database)

# Testing Instructions

## About workflow dynamic datasetIdList configuration instructions
1. In the workflow, obtain the dataset id list that needs to be dynamically passed through the code node or tool node
2. In the knowledge retrieval node, select the dynamic knowledge base drop-down box and specify the parameters of the corresponding datasetid list.
4. This knowledge retrieval node will use the specified knowledge base and the dynamically passed knowledge base to perform recall at the same time.

## About workflow document metadata filter instructions
1. Set the metadata of the document in the knowledge base document, and this metadata will be stored in the payload of the vector database.
2. Configure the corresponding metadata key, corresponding conditions and corresponding parameters in the knowledge retrieval node of the workflow.
4. When executing recall, the metadata conditions will be added to the original basis to recall the knowledge base data (this function currently only supports qdrant).

image

image

### CODE REVIEW

**Comment by wizd** [comment]
Love this feature. Enterprise documents needs this badly.

**Comment by lzzzzzzzzz** [comment]
期待后续发布的release版本

**Comment by TAXID911101087886396267** [comment]
We need this function very much. When can the update be released?

**Comment by teaguexiao** [comment]
This feature is awesome, I have built a docker image and run this on my env, which works well. Hope it will be merged into the official branch.

**Comment by teaguexiao** [comment]
动态数据库的输入的Array应该是怎样的格式呀？我串起来发现识别不了，好像没起作用，不知道为什么。

**Comment by teaguexiao** [comment]
> 动态数据库的输入的Array应该是怎样的格式呀？我串起来发现识别不了，好像没起作用，不知道为什么。

我在前面一个node产生这个数组，然后动态RAG引用老是不成功。但如果手动把知识库加到固定知识库列表，同样的query是可以召回的。是我的数据格式弄错了吗？

{
  "result": [
    "1c6de3c6-9baa-4572-ac4a-ff797d21fa77"
  ]
}

**Comment by weipanux** [comment]
I need this feature too! Please release asap!!

Here is my use case: My app create unique dataset for each user after they registered, then I need to add the dataset to the Knowledge Retrieval Nodes. However, the challenge i have with Dify right now is that it seems I have to manually add the dataset in the Knowledge Retrieval Nodes, there is no way to add the newly created datasets in runtime.

Further more, for the sake of data privacy, I want the Knowledge Retrieval Nodes to use dataset that is unique to each user, which means the dataset needs to be dynamically assigned/added to the Knowledge Retrieval Node, as part of the workflow, in runtime, not manually.

**Comment by teaguexiao** [comment]
> > 动态数据库的输入的Array应该是怎样的格式呀？我串起来发现识别不了，好像没起作用，不知道为什么。
> 
> 我在前面一个node产生这个数组，然后动态RAG引用老是不成功。但如果手动把知识库加到固定知识库列表，同样的query是可以召回的。是我的数据格式弄错了吗？
> 
> { "result": [ "1c6de3c6-9baa-4572-ac4a-ff797d21fa77" ] }

已经解决了

**Comment by teaguexiao** [comment]
> I need this feature too! Please release asap!!
> 
> Here is my use case: My app create unique dataset for each user after they registered, then I need to add the dataset to the Knowledge Retrieval Nodes. However, the challenge i have with Dify right now is that it seems I have to manually add the dataset in the Knowledge Retrieval Nodes, there is no way to add the newly created datasets in runtime.
> 
> Further more, for the sake of data privacy, I want the Knowledge Retrieval Nodes to use dataset that is unique to each user, which means the dataset needs to be dynamically assigned/added to the Knowledge Retrieval Node, as part of the workflow, in runtime, not manually.

I have talked to the developer and co-founder of Dify and this feature might not be merged. However, they will roll out new features on RAG for more specific control on chunking/embedding/retrival/etc. Currenty I would recommend to build your own docker image and run it locally.

**Comment by dnyg** [comment]
It would be very appreciated if someone from the Dify team would either close this pull request, or move it forward 🙏

**Comment by tahitimoon** [comment]
Love this feature. Enterprise documents needs this badly.

**Comment by VincePotato** [comment]
Here are a few considerations after the discussions between the dify team and the contributor team:

1.  Metadata filtering needs to support customization. The current flow is incomplete, and enabling customization requires addressing indexing performance.
2.  Manually entering metadata within nodes is not user-friendly and prone to errors. After selecting a knowledge base, existing metadata should be loaded for easier selection.
3. Different vector databases in the community edition vary in their support for metadata filtering, so adaptations are needed.

Thank you to the contributor for the excellent work. We will incorporate these ideas and include this feature in our development roadmap.

**Comment by hufangdong86** [comment]
It would be very appreciated if someone from the Dify team would either close this pull request, or move it forward 🙏

**Comment by glacierck** [comment]
上面这个方案中知识库文档的元数据参数怎么自定义了？目前的版本元数据字段是内置好的，能自定义吗？比如我想给文档加上任务id这个原数据。
另外，我这有个新的需求，就是支持动态文档id列表内进行向量检索，用来支持多视图管理的文档的检索。因为我的企业场景是同一份文档是可以出现在不同的视图下的，而问答服务为视图提供的，需要在视图范围呢进行知识库问答。

**Comment by glacierck** [comment]
@wangiii Can you try making this feature a standalone component? Even if it is not adopted, it will not affect our use, as there is no code conflict with the original component. Please, this feature is highly needed in enterprise level scenarios. I have a premonition that this new component will completely replace the old one.

**Comment by cleef** [comment]
Please, this feature is highly needed in enterprise level scenarios. ！！！

**Comment by domonless** [comment]
Need this.

**Comment by nicole828** [comment]
怎么获取到这个功能啊

**Comment by kennylbj** [comment]
why is this pr unmerged but closed

**Pull request closed without merging**
