### PR TITLE
feat: permission and security fixes

### PR DESCRIPTION
**Pull request by chazzhou**
# Description
This PR resolves the following issues:
1. The FireCrawl implementation currently lacks generalization in terms of naming. It also returns the API key back to the front end, which is unnecessary and poses a security risk. This PR addresses these issues by improving the naming conventions and removing the API key from the front-end response.
2. This PR adds checking for editor/manager permissions on the front-end UI and hides unnecessary editing options from Viewers and Editors. Specifically:
   - The tag editor is hidden for Viewers.
   - The App Info dropdown panel is hidden for Viewers.
   - The FireCrawl settings are hidden from Viewers and Editors.
3. The app name and icon editing APIs are now secured to require at least Editor permissions.
4. The workflow APIs are now secured to require at least Editor permissions.

These changes enhance the security and user experience of the application by restricting access to sensitive information, providing a more tailored interface based on user roles, and securing critical APIs to prevent unauthorized modifications.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] Tested the FireCrawl implementation to ensure that the API key is no longer returned to the front end.
- [x] Verified that the tag editor, App Info dropdown panel, and FireCrawl settings are correctly hidden for Viewers and Editors based on their permissions.
- [x] Tested the app name and icon editing APIs to ensure that they require at least Editor permissions.
- [x] Tested the workflow APIs to ensure that they require at least Editor permissions.
- [x] Conducted thorough manual testing to ensure that the changes do not introduce any new issues or break existing functionality.

# Checklist:
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I ran `dev/reformat` (backend) and `cd web && npx lint-staged` (frontend) to appease the lint gods.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by JohnJyong** [comment]
LGTM ， pending @iamjoel  review web code

**Review by iamjoel — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
Fix

**Comment by zn9988** [comment]
Anyone please response to my security advisory if security bugs is fixed ?

https://github.com/langgenius/dify/security/advisories/GHSA-gg5w-m2vw-vmmj#advisory-comment-108062

**Comment by zn9988** [comment]
@chazzhou @JohnJyong @iamjoel @tomoyuki28jp Any updates from the above ?

**Comment by zn9988** [comment]
@goocarlos @takatost @Yeuoly @crazywoola @yungler It has been four months since my last update from your side. I believe that the reported vulnerabilities below have been patched in June based on this thread. However, I did not receive any updates for my reported security advisory to proceed to the next step.  Could you kindly provide me with the current status of these updates? This information is crucial for us as it will be our vulnerability research initiative performance review this year that will happen in next month.

- https://github.com/langgenius/dify/security/advisories/GHSA-gg5w-m2vw-vmmj
- https://github.com/langgenius/dify/security/advisories/GHSA-hqcx-598m-pjq4
- https://github.com/langgenius/dify/security/advisories/GHSA-jp6m-v4gw-5vgp
- https://github.com/langgenius/dify/security/advisories/GHSA-6pw4-jqhv-3626

**Comment by zn9988** [comment]
HI @chazzhou @iamjoel @takatost @jonahcui   It is now the year 2025. Can anyone help close the security advisory report above? Since the vulnerabilities have been patched, the report should be finalized and the ticket closed. 我会很感激如果有人能回复我，告诉我该如何整理这个报告.

**Pull request merged**
