### PR TITLE
Add Oracle23ai as a vector datasource

### PR DESCRIPTION
**Pull request by tmuife**
# Description

Add Oracle23ai as a new vector datasource

Oracle23ai Easily bring the power of similarity search to your business data without having to manage and integrate multiple databases. AI Vector Search enables you to search structured and unstructured data based on its semantics or meaning, in addition to its values. Native vector capabilities can help large language models (LLMs) deliver more-accurate and contextually relevant results with retrieval-augmented generation (RAG).

Change/Add List:

api/config.py
api/controllers/console/datasets/datasets.py
api/core/rag/datasource/vdb/vector_factory.py
api/core/rag/datasource/vdb/vector_type.py
api/requirements.txt
api/core/rag/datasource/vdb/oracle/oraclevector.py
docker/startupscripts/create_user.sql
api/tests/integration_tests/vdb/oracle/test_oraclevector.py
docker/docker-compose.yaml

Dependence:

oracledb==2.2.1

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Dependency upgrade

# How Has This Been Tested?

1. run docker build with a test tag, for example 'langgenius/dify-api:test'
2. change the images in docker-compose.yml to use the test image you just build( api and work services)
3. comment Weaviate vector store, and uncomment oracle vector store(don't forget the volumes)
4. change VECTOR_STORE value to oracle

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by takatost** [comment]
there are some conflicts that need to be resolved, thx!

**Comment by tmuife** [comment]
conflicts fixed, thx!

**Review by takatost — CHANGES_REQUESTED** [review]
Due to the current version being in the transition period from pip to poetry, we need to add oracledb = "~2.2.1" to api/pyproject.toml [tool.poetry.dependencies]. Thank you very much.

**Comment by tmuife** [comment]
Yeah, I added the oracledb dependency in pyproject.toml. By the way, I don’t have much experience with pull requests, so if there is anything I can do, please let me know and I will do my best to push this feature. Thanks!

**Comment by tmuife** [comment]
In "API Tests" when goes to "Set Up Vector Store" step, i can't find docker/docker-compose.oracle.yaml, what am i missing?

**Comment by takatost** [comment]
> In "API Tests" when goes to "Set Up Vector Store" step, i can't see docker/docker-compose.oracle.yaml runs, what am i missing?

Oh, starting an oracle DB in GitHub action might be a disaster, don't you think? 😅

Proper unit testing is beneficial for us.

**Comment by tmuife** [comment]
> > In "API Tests" when goes to "Set Up Vector Store" step, i can't see docker/docker-compose.oracle.yaml runs, what am i missing?
> 
> Oh, starting an oracle DB in GitHub action might be a disaster, don't you think? 😅
> 
> Proper unit testing is beneficial for us.

Because the docker image is relatively large, it may require more resources, yeah 😅

**Review by takatost — DISMISSED** [review]
Thanks!

**Comment by takatost** [comment]
Need to fix the issues with lint and testing.

**Comment by tmuife** [comment]
> Need to fix the issues with lint and testing.

Pls check, Thanks.

**Comment by takatost** [comment]
> > Need to fix the issues with lint and testing.
> 
> Pls check, Thanks.

Ops, still having issues.

**Comment by tmuife** [comment]
> > > Need to fix the issues with lint and testing.
> > 
> > 
> > Pls check, Thanks.
> 
> Ops, still having issues.

Sorry, a mistake,  overwritten by conflict file.

**Comment by tmuife** [comment]
> > > > Need to fix the issues with lint and testing.
> > > 
> > > 
> > > Pls check, Thanks.
> > 
> > 
> > Ops, still having issues.
> 
> Sorry, a mistake, overwritten by conflict file.

What can i do for this "Python Style Expected — Waiting for status to be reported"

**Comment by takatost** [comment]
Test failed, maybe you can add some mock logic 😅

**Comment by tmuife** [comment]
> Test failed, maybe you can add some mock logic 😅

Thanks, i went into the details, and i think now i know how to do more test in my local env.

**Review by tmuife — COMMENTED** [review]
add start oracle docker in api-tests.yaml

**Comment by takatost** [comment]
You can use `dev/reformat` under the root directory to fix lint issues. If it can't be fixed, you'll need to manually resolve it based on the error.

```
  Error: /workspace/docker/docker-compose.oracle.yaml:19:1: [error] too many blank lines (1 > 0) (empty-lines)
  Error: /workspace/docker/docker-compose.yaml:589:1: [error] too many blank lines (1 > 0) (empty-lines)
```

**Comment by tmuife** [comment]
> You can use `dev/reformat` under the root directory to fix lint issues. If it can't be fixed, you'll need to manually resolve it based on the error.
> 
> ```
>   Error: /workspace/docker/docker-compose.oracle.yaml:19:1: [error] too many blank lines (1 > 0) (empty-lines)
>   Error: /workspace/docker/docker-compose.yaml:589:1: [error] too many blank lines (1 > 0) (empty-lines)
> ```

Got, do it right now

**Review by takatost — APPROVED** [review]
thanks!

**Comment by tmuife** [comment]
> thanks!

This feature, I mean support for Oracle 23 ai as a vector data source, which version will it be released with?

**Pull request merged**
