### PR TITLE
feat: Copy workspace info

### PR DESCRIPTION
**Pull request by cuckootan**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

add copy button to copy workspace basic information(name and id)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] copy workspace id and name into clipboard

image

image

### CODE REVIEW

**Comment by crazywoola** [comment]
I am not sure that why do you need this button?

**Comment by cuckootan** [comment]
> I am not sure that why do you need this button?

We deploy dify as a llm platform in our corp, and is widely used by many colleagues. So, it is necessary to create multiple workspaces to manage their usages according to difference business teams. In addition, we deploy an online model service that its codes are extracted from dify. It is used to manage model api call to all model providers configured in a certain workspace on dify.  That means users in the workspace have to know workspace info(id, etc.) and specify model name they want to use. Then our service fetch the model credentials according to workspace id and model name, and finally call the model api.

**Comment by crazywoola** [comment]
Ok, I need to forward this to our UI/UX designer to see if this is acceptable.

**Comment by crazywoola** [comment]
Sorry our designer does not agree with this feature.

**Pull request closed without merging**
