### PR TITLE
feat: support export chat app log to csv

### PR DESCRIPTION
**Pull request by Kevin9703**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat` (backend) and `cd web && npx lint-staged` (frontend) to appease the lint gods

# Description

This pull request introduces a new feature that supports the export of chat conversation logs to CSV format. The primary objective is to enable easy export of logs for data analysis to continually optimize the application.

The exported CSV will include the following columns:
  - `end_user_id`
  - `account_id`
  - `app_id`
  - `conversation_id`
  - `query`
  - `answer`
  - `message_tokens`
  - `answer_tokens`
  - `total_price`
  - `currency`
  - `created_at`
  - `message_metadata`
  - `user_rating`
  - `admin_rating`

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

image

### CODE REVIEW

**Comment by laipz8200** [comment]
This might result in heavy database access, and we need to assess it.

**Comment by garyfeng** [comment]
We need this feature in our use case. This could be limited to the admin roles, or there may be other ways to mitigate the performance impact. But the ability to export the logs is needed

**Comment by laipz8200** [comment]
After internal discussions, we believe we should not accept this pull request. We apologize for any inconvenience.

For self-hosted users, you are welcome to keep the code for use in your own environment.

For our Cloud users, we plan to offer more comprehensive data export features in the future.

Thank you once again for your contribution!

**Comment by Kevin9703** [comment]
> After internal discussions, we believe we should not accept this pull request. We apologize for any inconvenience.
> 
> For self-hosted users, you are welcome to keep the code for use in your own environment.
> 
> For our Cloud users, we plan to offer more comprehensive data export features in the future.
> 
> Thank you once again for your contribution!

Thank you very much for your reply and explanation. This will be a very valuable improvement for users. I look forward to seeing this new feature roll out and believe it will bring a better experience to users.

**Pull request closed without merging**
