### PR TITLE
Feat:remove estimation of embedding cost

### PR DESCRIPTION
**Pull request by JzoNgKVO**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

remove estimation of embedding cost.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by JohnJyong — APPROVED** [review]

**Comment by 18075717849** [comment]
Why was this feature removed?

**Comment by ZuzooVn** [comment]
> Why was this feature removed?

same question

**Comment by ZuzooVn** [comment]
@crazywoola can you explain the reason for removing this feature? Thanks

**Comment by crazywoola** [comment]
@JohnJyong

**Comment by JohnJyong** [comment]
The cost of embedding is already very low. Calling the API to calculate the estimated price will affect efficiency. Many embedding models do not even have an API to calculate the price.

**Pull request merged**
