### PR TITLE
feat: support Ernie-lite-pro-128k

### LINKED ISSUE #12130: Please support Ernie-lite-pro-128k
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Ernie-lite-128k-pro is good to use. Please update this into model_provider. 

### 2. Additional context or comments

refer: https://cloud.baidu.com/doc/WENXINWORKSHOP/s/9m0oofifc

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by bigfish49**
# Summary

support Ernie-lite-pro-128k

Resolves #12130

# Screenshots

| Before | After |
|--------|-------|
| ...    |image |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by HugoLian** [comment]
So how could I update this? I don't find this change at https://github.com/langgenius/dify/tree/main/api/core/model_runtime/model_providers/wenxin/llm
I am using a docker version.

**Comment by bigfish49** [comment]
> So how could I update this? I don't find this change at https://github.com/langgenius/dify/tree/main/api/core/model_runtime/model_providers/wenxin/llm I am using a docker version.

just waiting for it to be merged~

**Comment by HugoLian** [comment]
> > So how could I update this? I don't find this change at https://github.com/langgenius/dify/tree/main/api/core/model_runtime/model_providers/wenxin/llm I am using a docker version.
> 
> just waiting for it to be merged~

Thanks, I found your branch.
Because I am using the docker version.
So do I need to change the version here?
image
Or when it is merged, the docker version will be update?

**Review by crazywoola — APPROVED** [review]

**Comment by HugoLian** [comment]
max: 2048

> > So how could I update this? I don't find this change at https://github.com/langgenius/dify/tree/main/api/core/model_runtime/model_providers/wenxin/llm I am using a docker version.
> 
> just waiting for it to be merged~

I think max_output_tokens should be 4096 not 2048.

**Comment by bigfish49** [comment]
> max: 2048
> 
> > > So how could I update this? I don't find this change at https://github.com/langgenius/dify/tree/main/api/core/model_runtime/model_providers/wenxin/llm I am using a docker version.
> > 
> > 
> > just waiting for it to be merged~
> 
> I think max_output_tokens should be 8192 not 2048.

According to the official doc, max_output_tokens is 2048. image

**Comment by HugoLian** [comment]
Thanks for your information. 
But I confirmed with the model provider, they changed the webpage:
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/9m0oofifc
image

max output tokens from 2048 to 4096

**Pull request merged**
