### PR TITLE
feat: option to hide workflow steps

### LINKED ISSUE #4682: Can I hide the workflow directory of the user's question and answer page?
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

yes

### 2. Describe the feature you'd like to see

Hide the workflow directory on the page of user's question and answer.

### 3. How will this feature improve your workflow or experience?

Improve the user experience.

### 4. Additional context or comments

None

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #5411: Option to Hide Workflow Steps for Embedded Application
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

图片

When embedding the Dify application into a website, the workflow steps are also displayed to the user when answering questions. Regular users are not concerned with this and it may cause confusion. Could there be an option to hide the workflow steps and only display the answers?

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by crazywoola**
# Description

feat: option to hide workflow steps.

- Embed Chat
- Shared Chat
- Shared Workflow

⚠️ This is a temporary UI solution, it will be changed in future releases, but the function should remain the same.

Close #5411
Close #4682

image
image
image

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kurokobo** [comment]
Hi, thanks for working on this.
It seems that the workflow process remains hidden in the screen that can be opened via `Explore`, even if I specify `Show` to the chatbot. Is it okay?

image

**Comment by crazywoola** [comment]
> Hi, thanks for working on this. It seems that the workflow process remains hidden in the screen that can be opened via `Explore`, even if I specify `Show` to the chatbot. Is it okay?
> On the left is the shared app screen. The right is the screen opened via Explore.

I will fix that tmr.

**Review by zxhlyh — DISMISSED** [review]

**Review by laipz8200 — APPROVED** [review]
lgtm

**Comment by terrysun1216** [comment]
where is this setup? mine don't show such option.
截屏2025-03-24 17 05 53

**Comment by terrysun1216** [comment]
find the option~ sorry to bother you

**Comment by alx-ppv** [comment]
> find the option~ sorry to bother you
@terrysun1216 Where did you find it?

**Comment by laelhalawani** [comment]
Hi, I also noticed this is closed and all other tickets related but it's not actually fixed and not present in the UI in the latest version.

**Pull request merged**
