### PR TITLE
Fix App in sharing UI error.

### PR DESCRIPTION
**Pull request by BenjaminX**
h-full in sharing mistakes

### CODE REVIEW

**Comment by crazywoola** [comment]
Please see this PR https://github.com/langgenius/dify/pull/1609, it uses the 'h-full' here.

**Comment by BenjaminX** [comment]
> Please see this PR #1609, it uses the 'h-full' here. Can you paste a s
SCR-20231207-tpxj
creenshot or video as well?

**Comment by yuhao1118** [comment]
> > Please see this PR #1609, it uses the 'h-full' here. Can you paste a screenshot or video as well?
> > SCR-20231207-tpxj

Hi, I can't reproduce this problem. It looks good on my chrome and safari. Could you provide more detail about it? 
image

**Comment by BenjaminX** [comment]
SCR-20231211-oxux

@yuhao1118  FYI,

**Pull request closed without merging**
