### PR TITLE
fix: support azure gpt4-vision-preview model

### PR DESCRIPTION
**Pull request by esmeetu**
Currently custom `gpt4-vision-preview` in azure provider doesn't support vision feature. This PR add this.

### CODE REVIEW

**Review by barnett-yuxiang — COMMENTED** [review]
The style of hardcoding is not particularly good

**Comment by crazywoola** [comment]
We are working on new model runtime. I think this part will be deprecated. See this https://github.com/langgenius/dify/tree/feat/model-runtime for details.

**Comment by esmeetu** [comment]
> We are working on new model runtime. I think this part will be deprecated. See this https://github.com/langgenius/dify/tree/feat/model-runtime for details.

ok. 👍

**Comment by esmeetu** [comment]
> The style of hardcoding is not particularly good

Thanks for your review. I didn't consider too much and just followed the old code style.😑

**Pull request closed without merging**
