### PR TITLE
add binding external_user 

### PR DESCRIPTION
**Pull request by lingfengchencn**
use  `{share_url}?external_user_id=${externalUserID}&name=${name}` can binding external user

### CODE REVIEW

**Review by takatost — COMMENTED** [review]
Hey, you should integrate the Service API to implement this feature.

**Comment by lingfengchencn** [comment]
yes,I have add codes for binding `external_user` info in `api/controllers/web/passport.py` .

**Comment by takatost** [comment]
I mean is that you are modifying the web API, not the service API. The web API currently does not accept custom identities.

**Comment by lingfengchencn** [comment]
so, I can't pr the web folder?  Why?

and , Is there any development plan , I'm trying to add some features、docs.

**Comment by lingfengchencn** [comment]
Do you know how to use it ? 

I'm trying to add the app share config with anonymous or not.
if we use non-anonymous, just need a callback URL  to check whether the user info is valid.

**Comment by takatost** [comment]
Using a callback URL is feasible, but it's not our main focus for development at the moment. We provide a service API for secondary development, where you can meet the requirements for non-anonymous users based on it.

**Comment by lingfengchencn** [comment]
Thanks, and where can I see the dev plan?  I'm preparing to add PaLM2.

**Comment by takatost** [comment]
Our model reconstruction is currently under development and testing. You can wait for us to finish developing it and then join.
refreence #799

**Comment by takatost** [comment]
This feature is not in our plans, thank you very much. We will close this PR.

**Pull request closed without merging**
