### PR TITLE
Feat: site code can be explicitly set to a specified value when being reset

### PR DESCRIPTION
**Pull request by lethe3000**
Currently api `AppSiteAccessTokenReset` only supports generate a random `site.code`
So I add this feature that `code` can be explicitly set, this feature brings convenience for generate a more friendly and remember "share url" for end users.

### CODE REVIEW

**Comment by takatost** [comment]
This has been changed to product design, need PM to review it

**Comment by lethe3000** [comment]
Of course. the UI for `generate` button needs to be re-designed if this feature is applied

**Comment by lethe3000** [comment]
any plan on this?
currently I have to modify the `code` field in database to make a wanted share url

**Comment by takatost** [comment]
Still can't decide yet, you can build the code yourself for now. Thx for understanding

**Pull request closed without merging**
