### PR TITLE
Fix:typo  Incorrect Japanese

### PR DESCRIPTION
**Pull request by sasaharukimedes**
I'm native Japanese speaker. I found incorrect Japanese sentence in app.ts.

### CODE REVIEW

**Review by takatost — APPROVED** [review]
ありがとう!

**Comment by takatost** [comment]
Can you please resubmit a PR? The CI test has been failing since the target branch was modified, triggering a bug on GitHub.

**Comment by takatost** [comment]
> I see. I'll recreate PR soon.
> 
> Can I do a PR on the same branch? Please let me know if there are any branch designations. Is it OK to push my modified file again without any changes? Are there any files that you would like me to change?

Sure, np! Just create a new PR targeting the main branch.

**Comment by sasaharukimedes** [comment]
I recreate PR with a few comment in app.ts. Please rewiew it.

**Comment by takatost** [comment]
Closed this PR.

**Pull request closed without merging**
