### PR TITLE
tts models support

### PR DESCRIPTION
**Pull request by charli117**
add tts models, Supports voice reading of generated content

### CODE REVIEW

**Comment by takatost** [comment]
Seems like there's a bit of a conflict going on here 😬

**Comment by charli117** [comment]
> 看来这里发生了一些冲突😬

@takatost 已解决冲突

**Review by crazywoola — DISMISSED** [review]

**Comment by takatost** [comment]
let me check it out later.

**Comment by takatost** [comment]
```
/~/miniconda3/envs/dify/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```

Hey @charli117, I've started a project on macOS from the source code, but it seems that the `ffmpeg` component is missing. I noticed that the Dockerfile installs this component. Do I need to install ffmpeg separately for local source code deployment on macOS/Windows? What are the steps?

**Comment by charli117** [comment]
> ```
> /~/miniconda3/envs/dify/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> ```
> 
> Hey @charli117, I've started a project on macOS from the source code, but it seems that the `ffmpeg` component is missing. I noticed that the Dockerfile installs this component. Do I need to install ffmpeg separately for local source code deployment on macOS/Windows? What are the steps?

@takatost Required, ffmpeg is a must-have component both the local development environment and Dockerfile need to install it。
on macos run “brew install ffmpeg”

**Comment by takatost** [comment]
> > ```
> > /~/miniconda3/envs/dify/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
> >   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hey @charli117, I've started a project on macOS from the source code, but it seems that the `ffmpeg` component is missing. I noticed that the Dockerfile installs this component. Do I need to install ffmpeg separately for local source code deployment on macOS/Windows? What are the steps?
> 
> @takatost Required, ffmpeg is a must-have component both the local development environment and Dockerfile need to install it。 on macos run “brew install ffmpeg”

Can we run a check to see if `ffmpeg` is installed when enabling this feature? If it's not, perhaps we throw an error saying that `ffmpeg` needs to be installed to use this feature?

**Comment by charli117** [comment]
> > > ```
> > > /~/miniconda3/envs/dify/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
> > >   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Hey @charli117, I've started a project on macOS from the source code, but it seems that the `ffmpeg` component is missing. I noticed that the Dockerfile installs this component. Do I need to install ffmpeg separately for local source code deployment on macOS/Windows? What are the steps?
> > 
> > 
> > @takatost Required, ffmpeg is a must-have component both the local development environment and Dockerfile need to install it。 on macos run “brew install ffmpeg”
> 
> Can we run a check to see if `ffmpeg` is installed when enabling this feature? If it's not, perhaps we throw an error saying that `ffmpeg` needs to be installed to use this feature?

@takatost It should be. I'll look into adding an anomaly check

**Review by takatost — DISMISSED** [review]
great!

**Review by takatost — APPROVED** [review]

**Pull request merged**
