### PR TITLE
feat: support json_schema for ollama models

### PR DESCRIPTION
**Pull request by hjlarry**
# Summary

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

offical doc  https://ollama.com/blog/structured-outputs

# Screenshots

8fd967a8670f1b6ed4db69b99e55097

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Comment by bowenliang123** [comment]
Good job, my thumbs up for it !
Could you add this feature for OpenAI-compatible providers as well ?

**Comment by hjlarry** [comment]
> Good job, my thumbs up for it ! Could you add this feature for OpenAI-compatible providers as well ?

sure!  Is there any model for test this feature?

**Comment by bowenliang123** [comment]
Two approaches in mind:
- use ollama's endpoint in OpenAI compatible provider with Qwen 2.5 models
- use SiliconFlow's models in OpenAI compatible provider

**Comment by hjlarry** [comment]
I check the SiliconFlow's doc  https://docs.siliconflow.cn/guides/json-mode
seems it only support `json_object` , not support `json_schema` ?

**Comment by Colstuwjx** [comment]
Hi @hjlarry , could you help to introduce this feature for OpenAI compatible provider, I think vllm based models would also be able to use this feature, see doc: https://docs.vllm.ai/en/latest/features/structured_outputs.html#online-serving-openai-api

**Pull request merged**
