### PR TITLE
bug fix: update minimax model_apis

### PR DESCRIPTION
**Pull request by Weaxs**
# Description

update model_apis for minimax

Fixes # (issue)
https://github.com/langgenius/dify/pull/4012#issuecomment-2095273983
## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jianchaozhuang** [comment]
still report error when some tool is invoked:
```
2024-05-07 02:20:19.562 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:1053] - Starting new HTTPS connection (1): api.minimax.chat:443                   
2024-05-07 02:20:20.695 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:547] - https://api.minimax.chat:443 "POST /v1/text/chatcompletion_pro?GroupId=1781
943183245054127 HTTP/1.1" 200 None                                                                                                                                
2024-05-07 02:20:20.698 ERROR [Thread-20 (_generate_worker)] [app_generator.py:203] - Error when generating                                                       
Traceback (most recent call last):                                                                                                                                
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 394, in _invoke_result_generator                                        
    for chunk in result:                                                                                                                                          
  File "/app/api/core/model_runtime/model_providers/minimax/llm/llm.py", line 172, in _handle_chat_generate_stream_response                                       
    for message in response:                                                                                                                                      
  File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 159, in _handle_stream_chat_generate_response                       
    self._handle_error(code, msg)                                                                                                                                 
  File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 117, in _handle_error                                               
    raise BadRequestError(msg)                                                                                                                                    
core.model_runtime.model_providers.minimax.llm.errors.BadRequestError: invalid params, function的上一条消息必须带function_call                                    
                                                                                                                                                                  
During handling of the above exception, another exception occurred:                                                                                               
                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                
  File "/app/api/core/app/apps/agent_chat/app_generator.py", line 185, in _generate_worker                                                                        
    runner.run(                                                                                                                                                   
  File "/app/api/core/app/apps/agent_chat/app_runner.py", line 247, in run                                                                                        
    self._handle_invoke_result(                                                                                                                                   
  File "/app/api/core/app/apps/base_app_runner.py", line 265, in _handle_invoke_result                                                                            
    self._handle_invoke_result_stream(                                                                                                                            
  File "/app/api/core/app/apps/base_app_runner.py", line 299, in _handle_invoke_result_stream                                                                     
    for result in invoke_result:                                                                                                                                  
  File "/app/api/core/agent/fc_agent_runner.py", line 109, in run                                                                                                 
    for chunk in chunks:                                                                                                                                          
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 418, in _invoke_result_generator                                        
    raise self._transform_invoke_error(e)                                                                                                                         
core.model_runtime.errors.invoke.InvokeBadRequestError: [minimax] Bad Request Error, invalid params, function的上一条消息必须带function_call                      
2024-05-07 02:20:20.701 DEBUG [Thread-19 (process_request_thread)] [based_generate_task_pipeline.py:60] - error: [minimax] Bad Request Error, invalid params, func
tion的上一条消息必须带function_call 
```

**Review by takatost — APPROVED** [review]
LGTM

**Comment by takatost** [comment]
> > @Weaxs After applying your patch, abab6.5 chat model still reports error when some tool is invoked:
> > ```
> > 2024-05-07 02:20:19.562 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:1053] - Starting new HTTPS connection (1): api.minimax.chat:443                   
> > 2024-05-07 02:20:20.695 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:547] - https://api.minimax.chat:443 "POST /v1/text/chatcompletion_pro?GroupId=1781
> > 943183245054127 HTTP/1.1" 200 None                                                                                                                                
> > 2024-05-07 02:20:20.698 ERROR [Thread-20 (_generate_worker)] [app_generator.py:203] - Error when generating                                                       
> > Traceback (most recent call last):                                                                                                                                
> >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 394, in _invoke_result_generator                                        
> >     for chunk in result:                                                                                                                                          
> >   File "/app/api/core/model_runtime/model_providers/minimax/llm/llm.py", line 172, in _handle_chat_generate_stream_response                                       
> >     for message in response:                                                                                                                                      
> >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 159, in _handle_stream_chat_generate_response                       
> >     self._handle_error(code, msg)                                                                                                                                 
> >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 117, in _handle_error                                               
> >     raise BadRequestError(msg)                                                                                                                                    
> > core.model_runtime.model_providers.minimax.llm.errors.BadRequestError: invalid params, function的上一条消息必须带function_call                                    
> >                                                                                                                                                                   
> > During handling of the above exception, another exception occurred:                                                                                               
> >                                                                                                                                                                   
> > Traceback (most recent call last):                                                                                                                                
> >   File "/app/api/core/app/apps/agent_chat/app_generator.py", line 185, in _generate_worker                                                                        
> >     runner.run(                                                                                                                                                   
> >   File "/app/api/core/app/apps/agent_chat/app_runner.py", line 247, in run                                                                                        
> >     self._handle_invoke_result(                                                                                                                                   
> >   File "/app/api/core/app/apps/base_app_runner.py", line 265, in _handle_invoke_result                                                                            
> >     self._handle_invoke_result_stream(                                                                                                                            
> >   File "/app/api/core/app/apps/base_app_runner.py", line 299, in _handle_invoke_result_stream                                                                     
> >     for result in invoke_result:                                                                                                                                  
> >   File "/app/api/core/agent/fc_agent_runner.py", line 109, in run                                                                                                 
> >     for chunk in chunks:                                                                                                                                          
> >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 418, in _invoke_result_generator                                        
> >     raise self._transform_invoke_error(e)                                                                                                                         
> > core.model_runtime.errors.invoke.InvokeBadRequestError: [minimax] Bad Request Error, invalid params, function的上一条消息必须带function_call                      
> > 2024-05-07 02:20:20.701 DEBUG [Thread-19 (process_request_thread)] [based_generate_task_pipeline.py:60] - error: [minimax] Bad Request Error, invalid params, func
> > tion的上一条消息必须带function_call 
> > ```
> 
> abab6-chat and abab5.5-chat also reported error like this. I thought this bug is historical ? image image
> 
> I debug `api/core/model_runtime/model_providers/minimax/llm/llm.py` and I find when try to use these minimax model with tools, api will returns two chunks which both contain the function_call, this will cause the tool to be called several times I guess. image for example, this response will cause dify to execute `duckduckgo_search` twice, and messges will update like this: image
> 
> Finally, will report error like `Bad Request Error, invalid params, function的上一条消息必须带function_call `
> 
> I will fix it later.

Thanks! Can you submit a new PR for the issue you mentioned?

**Comment by Weaxs** [comment]
> > > @Weaxs After applying your patch, abab6.5 chat model still reports error when some tool is invoked:
> > > ```
> > > 2024-05-07 02:20:19.562 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:1053] - Starting new HTTPS connection (1): api.minimax.chat:443                   
> > > 2024-05-07 02:20:20.695 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:547] - https://api.minimax.chat:443 "POST /v1/text/chatcompletion_pro?GroupId=1781
> > > 943183245054127 HTTP/1.1" 200 None                                                                                                                                
> > > 2024-05-07 02:20:20.698 ERROR [Thread-20 (_generate_worker)] [app_generator.py:203] - Error when generating                                                       
> > > Traceback (most recent call last):                                                                                                                                
> > >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 394, in _invoke_result_generator                                        
> > >     for chunk in result:                                                                                                                                          
> > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/llm.py", line 172, in _handle_chat_generate_stream_response                                       
> > >     for message in response:                                                                                                                                      
> > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 159, in _handle_stream_chat_generate_response                       
> > >     self._handle_error(code, msg)                                                                                                                                 
> > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 117, in _handle_error                                               
> > >     raise BadRequestError(msg)                                                                                                                                    
> > > core.model_runtime.model_providers.minimax.llm.errors.BadRequestError: invalid params, function的上一条消息必须带function_call                                    
> > >                                                                                                                                                                   
> > > During handling of the above exception, another exception occurred:                                                                                               
> > >                                                                                                                                                                   
> > > Traceback (most recent call last):                                                                                                                                
> > >   File "/app/api/core/app/apps/agent_chat/app_generator.py", line 185, in _generate_worker                                                                        
> > >     runner.run(                                                                                                                                                   
> > >   File "/app/api/core/app/apps/agent_chat/app_runner.py", line 247, in run                                                                                        
> > >     self._handle_invoke_result(                                                                                                                                   
> > >   File "/app/api/core/app/apps/base_app_runner.py", line 265, in _handle_invoke_result                                                                            
> > >     self._handle_invoke_result_stream(                                                                                                                            
> > >   File "/app/api/core/app/apps/base_app_runner.py", line 299, in _handle_invoke_result_stream                                                                     
> > >     for result in invoke_result:                                                                                                                                  
> > >   File "/app/api/core/agent/fc_agent_runner.py", line 109, in run                                                                                                 
> > >     for chunk in chunks:                                                                                                                                          
> > >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 418, in _invoke_result_generator                                        
> > >     raise self._transform_invoke_error(e)                                                                                                                         
> > > core.model_runtime.errors.invoke.InvokeBadRequestError: [minimax] Bad Request Error, invalid params, function的上一条消息必须带function_call                      
> > > 2024-05-07 02:20:20.701 DEBUG [Thread-19 (process_request_thread)] [based_generate_task_pipeline.py:60] - error: [minimax] Bad Request Error, invalid params, func
> > > tion的上一条消息必须带function_call 
> > > ```
> > 
> > 
> > abab6-chat and abab5.5-chat also reported error like this. I thought this bug is historical ? image image
> > I debug `api/core/model_runtime/model_providers/minimax/llm/llm.py` and I find when try to use these minimax model with tools, api will returns two chunks which both contain the function_call, this will cause the tool to be called several times I guess. image for example, this response will cause dify to execute `duckduckgo_search` twice, and messges will update like this: image
> > Finally, will report error like `Bad Request Error, invalid params, function的上一条消息必须带function_call `
> > I will fix it later.
> 
> Thanks! Can you submit a new PR for the issue you mentioned?

Yeah, I will submit a new PR to fix it as soon as possible

**Comment by takatost** [comment]
thx!

**Comment by jianchaozhuang** [comment]
> > > > @Weaxs After applying your patch, abab6.5 chat model still reports error when some tool is invoked:
> > > > ```
> > > > 2024-05-07 02:20:19.562 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:1053] - Starting new HTTPS connection (1): api.minimax.chat:443                   
> > > > 2024-05-07 02:20:20.695 DEBUG [Thread-20 (_generate_worker)] [connectionpool.py:547] - https://api.minimax.chat:443 "POST /v1/text/chatcompletion_pro?GroupId=1781
> > > > 943183245054127 HTTP/1.1" 200 None                                                                                                                                
> > > > 2024-05-07 02:20:20.698 ERROR [Thread-20 (_generate_worker)] [app_generator.py:203] - Error when generating                                                       
> > > > Traceback (most recent call last):                                                                                                                                
> > > >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 394, in _invoke_result_generator                                        
> > > >     for chunk in result:                                                                                                                                          
> > > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/llm.py", line 172, in _handle_chat_generate_stream_response                                       
> > > >     for message in response:                                                                                                                                      
> > > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 159, in _handle_stream_chat_generate_response                       
> > > >     self._handle_error(code, msg)                                                                                                                                 
> > > >   File "/app/api/core/model_runtime/model_providers/minimax/llm/chat_completion_pro.py", line 117, in _handle_error                                               
> > > >     raise BadRequestError(msg)                                                                                                                                    
> > > > core.model_runtime.model_providers.minimax.llm.errors.BadRequestError: invalid params, function的上一条消息必须带function_call                                    
> > > >                                                                                                                                                                   
> > > > During handling of the above exception, another exception occurred:                                                                                               
> > > >                                                                                                                                                                   
> > > > Traceback (most recent call last):                                                                                                                                
> > > >   File "/app/api/core/app/apps/agent_chat/app_generator.py", line 185, in _generate_worker                                                                        
> > > >     runner.run(                                                                                                                                                   
> > > >   File "/app/api/core/app/apps/agent_chat/app_runner.py", line 247, in run                                                                                        
> > > >     self._handle_invoke_result(                                                                                                                                   
> > > >   File "/app/api/core/app/apps/base_app_runner.py", line 265, in _handle_invoke_result                                                                            
> > > >     self._handle_invoke_result_stream(                                                                                                                            
> > > >   File "/app/api/core/app/apps/base_app_runner.py", line 299, in _handle_invoke_result_stream                                                                     
> > > >     for result in invoke_result:                                                                                                                                  
> > > >   File "/app/api/core/agent/fc_agent_runner.py", line 109, in run                                                                                                 
> > > >     for chunk in chunks:                                                                                                                                          
> > > >   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 418, in _invoke_result_generator                                        
> > > >     raise self._transform_invoke_error(e)                                                                                                                         
> > > > core.model_runtime.errors.invoke.InvokeBadRequestError: [minimax] Bad Request Error, invalid params, function的上一条消息必须带function_call                      
> > > > 2024-05-07 02:20:20.701 DEBUG [Thread-19 (process_request_thread)] [based_generate_task_pipeline.py:60] - error: [minimax] Bad Request Error, invalid params, func
> > > > tion的上一条消息必须带function_call 
> > > > ```
> > > 
> > > 
> > > abab6-chat and abab5.5-chat also reported error like this. I thought this bug is historical ? image image
> > > I debug `api/core/model_runtime/model_providers/minimax/llm/llm.py` and I find when try to use these minimax model with tools, api will returns two chunks which both contain the function_call, this will cause the tool to be called several times I guess. image for example, this response will cause dify to execute `duckduckgo_search` twice, and messges will update like this: image
> > > Finally, will report error like `Bad Request Error, invalid params, function的上一条消息必须带function_call `
> > > I will fix it later.
> > 
> > 
> > Thanks! Can you submit a new PR for the issue you mentioned?
> 
> Yeah, I will submit a new PR to fix it as soon as possible

I just talk with miniMax technique support guys, and they knew this issue and will report to the dev department. So I think your fix should handle both one response and duplicate responses.

**Comment by backearth1** [comment]
still have this issue

**Comment by backearth1** [comment]
still same issue in dify [v0.6.7]

**Pull request merged**
