### PR TITLE
feat(Tools): :sparkles: add YouTube Video transcript fetching

### PR DESCRIPTION
**Pull request by patryk20120**
# Description

Adding a tool for fetching transcript of a YouTube video.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested locally

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by takatost** [comment]
Hey @Yeuoly, do you think it's better to put this under the YouTube provider or have it as a separate provider `youtubetranscript`?

**Comment by patryk20120** [comment]
> Hey @Yeuoly, do you think it's better to put this under the YouTube provider or have it as a separate provider `youtubetranscript`?

I think it is impossible to put this under YouTube provider, as YouTube provider needs an authorization but this tool does not need it.

**Comment by takatost** [comment]
> > Hey @Yeuoly, do you think it's better to put this under the YouTube provider or have it as a separate provider `youtubetranscript`?
> 
> 
> 
> I think it is impossible to put this under YouTube provider, as YouTube provider needs an authorization but this tool does not need it.

This is indeed a problem. 🤔

**Comment by patryk20120** [comment]
> > > Hey @Yeuoly, do you think it's better to put this under the YouTube provider or have it as a separate provider `youtubetranscript`?
> > 
> > 
> > I think it is impossible to put this under YouTube provider, as YouTube provider needs an authorization but this tool does not need it.
> 
> This is indeed a problem. 🤔

Also wanted to do that but until I find this out

**Comment by Yeuoly** [comment]
Yes, this is what I mentioned before. We might need a provider group to aggregate all brand-related providers, such as Google, SerpAPI, and Google Mail, together.

**Comment by patryk20120** [comment]
> Yes, this is what I mentioned before. We might need a provider group to aggregate all brand-related providers, such as Google, SerpAPI, and Google Mail, together.

Would be pleasure to collaborate in this field

**Comment by Yeuoly** [comment]
> > Yes, this is what I mentioned before. We might need a provider group to aggregate all brand-related providers, such as Google, SerpAPI, and Google Mail, together.
> 
> Would be pleasure to collaborate in this field

It looks like we need some UI design work on the frontend. On the backend, we just need to add a `brand` field to the YAML file. Can you help with that?

**Comment by patryk20120** [comment]
> > > Yes, this is what I mentioned before. We might need a provider group to aggregate all brand-related providers, such as Google, SerpAPI, and Google Mail, together.
> > 
> > 
> > Would be pleasure to collaborate in this field
> 
> It looks like we need some UI design work on the frontend. On the backend, we just need to add a `brand` field to the YAML file. Can you help with that?

Do you mean backend or both? I notice that you have a very good UI developer or principals, I would like to not destroy that :) If you send me the UX project I can implement it both on front and back ends

**Comment by laipz8200** [comment]
> > > > Yes, this is what I mentioned before. We might need a provider group to aggregate all brand-related providers, such as Google, SerpAPI, and Google Mail, together.
> > > 
> > > 
> > > Would be pleasure to collaborate in this field
> > 
> > 
> > It looks like we need some UI design work on the frontend. On the backend, we just need to add a `brand` field to the YAML file. Can you help with that?
> 
> Do you mean backend or both? I notice that you have a very good UI developer or principals, I would like to not destroy that :) If you send me the UX project I can implement it both on front and back ends

I think she's talking about the backend. If our API includes a 'brand' field, we can start designing and completing the frontend work.

**Pull request closed without merging**
