### PR TITLE
fix: some typos using typos

### PR DESCRIPTION
**Pull request by yihong0618**
# Summary

This patch fix a lot of typos in api/ which is backend, and also found a typo bug caused bug in `tools/wolframalpha`

```diff
- if "souces" in response_data["queryresult"]:
+ if "sources" in response_data["queryresult"]:
```

using https://github.com/crate-ci/typos .

command:
```cli
cd api
typos --exclude '*.txt' --exclude '*.json' --exclude '*.svg' --exclude '*.js'
```
nit: some of the typos not fixed because that may cause problems I think I should careful leave them for now

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

<table>
  <tr>
  <td>Before: </td>
  <td>After: </td>
  </tr>
  <tr>
  <td>...</td>
  <td>...</td>
  </tr>
</table>

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Review by crazywoola — COMMENTED** [review]
Please do not include changes in `tools/provider/builtin` for now. :)

**Comment by yihong0618** [comment]
> ols/prov

copy will checkout them? just leave the bug fix diff is that OK?

**Comment by yihong0618** [comment]
> > ols/prov
> 
> copy will checkout them, just leave the bug fix diff is that OK?

**Comment by crazywoola** [comment]
> > ols/prov
> 
> copy will checkout them? just leave the bug fix diff is that OK?

Because we are migrating tools to another repo so we can not touch it for now.

**Comment by yihong0618** [comment]
> > > ols/prov
> > 
> > 
> > copy will checkout them? just leave the bug fix diff is that OK?
> 
> Because we are migrating tools to another repo so we can not touch it for now.

thanks only fix the bug in them, and drop others

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
