### PR TITLE
chore(pyproject.toml): Add Ruff formatter config.

### PR DESCRIPTION
**Pull request by laipz8200**
# Description

This change is in preparation for the future introduction of the Ruff formatter. For now, we will not require the use of any formatter.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement

# How Has This Been Tested?

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by bowenliang123** [comment]
Note:
And the change in this PR is not effective at the moment, which surely will cause many changes in future.

**Comment by laipz8200** [comment]
> Note: And the change in this PR is not effective at the moment, which surely will cause many changes in future.

Sure, it's currently for internal use only.

**Comment by bowenliang123** [comment]
And be careful when use Ruff's formatter and linter together. Some rules may be conflict.

**Comment by laipz8200** [comment]
> And be careful when use Ruff's formatter and linter together. Some rules may be conflict.

Thanks for the reminder! We’ll introduce the formatter only when we’re ready, or would you be willing to help us check the rules?

**Comment by bowenliang123** [comment]
I would prefer apply E and W rules of Ruff linters first ( https://docs.astral.sh/ruff/rules/#pycodestyle-e-w), if you guys are ready to brace a big change in multiple files for one time. Many of them are auto-fixable and help code formatting.

**Comment by laipz8200** [comment]
@bowenliang123 Great idea! We also want to apply some currently ignored rules (like F812 and F841). Maybe we will create a list and process them one by one.

**Comment by bowenliang123** [comment]
No problem~ SGTM.

**Pull request merged**
