### PR TITLE
fix: add missing vikingdb param in docker .env.example

### PR DESCRIPTION
**Pull request by yaoice**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Add missing vikingdb param in docker .env.example

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by crazywoola — DISMISSED** [review]

**Comment by crazywoola** [comment]
Still something wrong with the lint.

**Comment by yaoice** [comment]
> Still something wrong with the lint.

@crazywoola Has our CI upgraded any configurations? I did a test. I only made the following change. As a result, the style check also cannot pass.
image

**Comment by yaoice** [comment]
It seems to be a problem with actions-poetry itself. The issue reference: https://github.com/abatilo/actions-poetry/issues/76

**Comment by crazywoola** [comment]
Can you try to checkout from main and pick these commit.

**Comment by yaoice** [comment]
> Can you try to checkout from main and pick these commit.

Sorry I only saw it now. Thanks a lot.

**Pull request merged**
