### PR TITLE
fix: add gevent monkey patch to celery.

### LINKED ISSUE #7573: Celery maybe not working
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Here is the worker log: 
```
[2024-08-23 06:54:15,840: INFO/MainProcess] Connected to redis://:**@redis:6379/1
[2024-08-23 06:54:15,843: INFO/MainProcess] mingle: searching for neighbors
[2024-08-23 06:54:16,856: INFO/MainProcess] mingle: all alone
[2024-08-23 06:54:16,888: INFO/MainProcess] celery@67b80c9f1274 ready.
[2024-08-23 06:54:17,677: INFO/MainProcess] pidbox: Connected to redis://:**@redis:6379/1.
[2024-08-23 06:54:18,106: INFO/MainProcess] Task tasks.batch_create_segment_to_index_task.batch_create_segment_to_index_task[4824e735-7356-4c16-87ab-778b1582b72a] received
[2024-08-23 06:54:18,477: INFO/MainProcess] Start batch create segment jobId: 03a3613a-38a0-4d27-a540-3b6fdac76ce5

```
no more logs print out.
and the dataset still Queuing.

### ✔️ Expected Behavior

more logs and debug info.

### ❌ Actual Behavior

no more logs, dataset status: Queuing

### PR DESCRIPTION
**Pull request by erigo**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Fix #7573 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by bowenliang123 — CHANGES_REQUESTED** [review]
Have you tried to set `DEBUG` system env to `true`?
The app.py has been applied in api/app.py when DEBUG=ture.

And even if we want to have event monkey patch, we should not have this in celery extension.

**Comment by erigo** [comment]
> Have you tried to set `DEBUG` system env to `true`? The app.py has been applied in api/app.py when DEBUG=ture.
Yes, I have set DEBUG=true in .env file.

> 
> And even if we want to have event monkey patch, we should not have this in celery extension.
Sorry, could you please tell me where the monkey patch should be applied?

**Comment by erigo** [comment]
> @erigo At the line 6 of `api.app.py`.
> 
> ```
> monkey.patch_all()
> ```
> 
> If DEBUG set to true, the line 6 pathes gevent monkey, before the celery app was initialized at Line 156.

Do you mean that if DEBUG is set to true, the monkey patch won't be applied? Could you please clarify? Thanks! 🙏

**Comment by bowenliang123** [comment]
What's your main goal in this PR? And how it fix the issue?
Do you want to apply event monky patch anyway, in both cases with DEBUG enabled or disabled?

**Comment by erigo** [comment]
> Thanks for your correction. And the existed code seems only apply the monkey patch when DEBEUG disabled.
> 
> What's your main goal in this PR? And how it fix the issue? Do you want to apply event monky patch anyway, in both cases with DEBUG enabled or disabled?

Yes, when I started the Dify application in the testing environment with DEBUG mode enabled, I noticed that Celery tasks were getting stuck because they couldn't acquire resources. I tried running Celery from the command line, and even pressing Ctrl+C couldn't stop the process. However, the tasks ran correctly when using the prefork mode. After testing, it seems that the issue was caused by Celery not being monkey-patched.

see #7573

**Comment by bowenliang123** [comment]
> Do you want to apply event monky patch anyway

If this is what you're asking for, these changes I'm suggested.
- leave celery extension `ext_celery` unchanged, the current committed changes is applying to the whole process anyway. the locality change with global impact should not be isolatedly placed.
- change the code in `api/app.py`, applying Gevent's monkey patch in all cases.

And for the proper use of Gevent, we should have a discussion with key committers. cc @takatost @laipz8200

**Comment by erigo** [comment]
> > Do you want to apply event monky patch anyway
> 
> If this is what you're asking for, these changes I'm suggested.
> 
> * leave celery extension `ext_celery` unchanged, the current committed changes is applying to the whole process anyway. the locality change with global impact should not be isolatedly placed.
> * change the code in `api/app.py`, applying Gevent's monkey patch in all cases.
> 
> And for the proper use of Gevent, we should have a discussion with key committers. cc @takatost @laipz8200

Got it, I know where the monkey patch should be applied [Thanks]. I'll wait for the discussion to conclude on whether we should apply the monkey patch in all scenarios before submitting a PR.

**Comment by bowenliang123** [comment]
Have you joined the Wechat group of contributors?

**Comment by erigo** [comment]
> Have you joined the Wechat group of contributors?

Not yet, I haven't found the 'organization' 😂.

**Comment by bowenliang123** [comment]
cc @crazywoola 

> > Have you joined the Wechat group of contributors?
> 
> Not yet, I haven't found the 'organization' 😂.

**Comment by laipz8200** [comment]
> > Thanks for your correction. And the existed code seems only apply the monkey patch when DEBEUG disabled.
> > What's your main goal in this PR? And how it fix the issue? Do you want to apply event monky patch anyway, in both cases with DEBUG enabled or disabled?
> 
> Yes, when I started the Dify application in the testing environment with DEBUG mode enabled, I noticed that Celery tasks were getting stuck because they couldn't acquire resources. I tried running Celery from the command line, and even pressing Ctrl+C couldn't stop the process. However, the tasks ran correctly when using the prefork mode. After testing, it seems that the issue was caused by Celery not being monkey-patched.
> 
> see #7573

Hello, could you provide the command you use to start the Celery worker? It runs well in my environment.

BTW you can check the command in `api/.vscode/launch.json.example`.

**Comment by laipz8200** [comment]
Hi @erigo,

I believe this issue is unlikely to be caused by `gevent`. Since the pool deals with concurrency, and in the debug mode, the concurrency is typically set to 1.

**Pull request closed without merging**
