### PR TITLE
FR: #4048 - Add color customization to the chatbot 

### LINKED ISSUE #4048: [FR] Frontend - Customize theme color of chatbot app.
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

The colors of the chatbot app are static. For example, in the Header component, the class that sets the background color is `bg-gradient-to-r from-blue-600 to-sky-500`. This distinctively blue color,  doesn't blend well with some website's styles or doesn't adhere to the design requirements of the website.

### 2. Describe the feature you'd like to see

It would be ideal, without having to fork the chat app and manually change the code, to configure the colors in a way that the embedded frame blends better with the website's style without making the customization too complex. I was thinking of adding an extra field in the `SettingsModal` component, such as "Chat Color Theme".

SettingsModal

### 3. How will this feature improve your workflow or experience?

It will improve the experience of developers and designers that want to include the iframe into a website that have clear or strict design requirements.

### 4. Additional context or comments

Examples using free templates of astro:

Before_Tailcast

After_Tailcast

Inverted style:

Inverted_Tailcast

Before_Pinwheel
After_Pinwheel

Inverted Style:

Inverted_Pinwheel

@iamjoel Wanted to know what you guys think or what the community, in general, thinks.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by dromerolovo**
# Description

FR: Close #4048 - Add color customization to the chatbot

The scope of this PR is to apply customization only to the chatbot.

1. Add `chatbot_color_theme` and `chatbot_color_theme_inverted` to the `SiteInfo`
2. Create an input on `SettingsModal` to set `chatbot_color_theme` and `chatbot_color_theme_inverted`
3. Create the db migration to support those properties
4. Create a context and a Theme builder
5. Apply dynamic styles to components that are part of the chatbot embedded such as: Header, Welcome, Question, etc.
6. Override and add default values in case that the theme is not built, because many components are used in contexts outside the chatbot
7. Override the style of the button.

Because Tailwind doesn't support dynamic classes because of its JIT functionality I had to include styles
directly https://v2.tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support It would've been nice to keep it with classes, but I think that It can't be done that way.

LIMITATIONS:

1. Colors with high luminance or those close to white may not be visually distinct due to a lack of contrast.
2. When setting a new color in the Settings Modal, it is necessary to refresh the app to update the embedded script.
3. The color of the "#dify-chatbot-bubble-button" is controlled by a script, so each change requires adding a new script to the website.

Fixes # (issue)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [X] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods (Kind of)
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

I considered this change useful as stated in the Issue made previously:

How will this feature improve your workflow or experience?
It will improve the experience of developers and designers that want to include the embedded chatbot into a website that have clear or strict design requirements.

If you guys feel that this is not the way that you want to go, you can always let it fade into oblivion.

### CODE REVIEW

**Review by crazywoola — CHANGES_REQUESTED** [review]
Thanks for your contribution. I've test it's functionality. LGTM, Although I have several comments:

- This configuration should limited to chatbot, chatflow, and agent, but it appears in the setting modal in workflow and text generation as well. I think it should be hidden for these two types from the frontend.
- The checkbox, since it's not a standard UI widget in our application, but it's ok, I will ask our UI to check it out, maybe open a follow up PR for this later.

image

image


image

**Comment by dromerolovo** [comment]
Hi, @crazywoola. I agree. I'll check that out as soon as I'm free.

**Comment by dromerolovo** [comment]
@crazywoola I've pushed the changes:
1.  I copied the classes of the checkbox inside `StepTwo` to the 'inverted' checkbox
2. Add a conditional rendering for the theme input, excluding the apps that are not 'chat'
3. Updated the migration because, in the meantime, there was a new migration.
4. Added a fix: it is now unnecessary to refresh the site to update the primary color on the embedded script.

**Comment by crazywoola** [comment]
Hello, sorry for the late response, I have fixed the CI based on several changes in our code base. :)
I tested this today, it seems the color theme is not working. Could you take a look at this.

**Comment by dromerolovo** [comment]
Hi @crazywoola. I took a look and the theme is not working because of the following reason:

The commit `Chore: refactor embedded chatbot` 4289f17
Made a refactor changing in
`web/app/(shareLayout)/chatbot/[token]/page.tsx`

The following:
```
- import Main from '@/app/components/share/chatbot'
+ import EmbeddedChatbot from '@/app/components/base/chat/embedded-chatbot'
```
the Main component use the following relevant components:
```	
Header from '@/app/components/share/header'
Chat from '@/app/components/app/chat'
ConfigScene from '@/app/components/share/chatbot/config-scence'
```

The EmbeddedChatbot use a different set of components:
```
Header from '@/app/components/base/chat/embedded-chatbot/header'
ConfigPanel from '@/app/components/base/chat/embedded-chatbot/config-panel'
ChatWrapper from '@/app/components/base/chat/embedded-chatbot/chat-wrapper'
```
Apparently the Main component and its children are obsolete. 
The theme implementation was made on Main and its child components from '@/app/components/share/chatbot'

So the solution would be to implement the style logic on the new `embedded-chatbot` components.

**Comment by crazywoola** [comment]
@dromerolovo Yes please mark those with a `@deprecated` decorator. 
@JzoNgKVO Could you take a look at this as well.

**Comment by JzoNgKVO** [comment]
This PR #5125  is  intended for all chat components to use the components under the `@/app/components/base/chat` folder. The old components under `@/app/components/app/chat` will be deprecated in the near future. 

This PR #4379 also refactored the `Button` component.

So @dromerolovo you can implement the style logic in the new components to achieve this functionality when you are free. Thanks for your contribution.

By the way, there is a major update being planned regarding theme colors, which will support dark mode and make it easier to support more theme colors in this release, expected in August.

**Comment by dromerolovo** [comment]
@JzoNgKVO @crazywoola I've applied the theme to the new components. Hopefully is working

**Review by crazywoola — DISMISSED** [review]
LGTM

**Review by JzoNgKVO — DISMISSED** [review]

**Comment by crazywoola** [comment]
FYI, as we are working on some new components such as checkboxes.
I will remove inverted checkbox for now. I will open another PR to add it back once we have that widget ready. :)

**Review by crazywoola — DISMISSED** [review]

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
