### PR TITLE
feat: support vision models from xinference

### PR DESCRIPTION
**Pull request by Minamiyama**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- launch a vision model on xinference like qwen-vl-chat
- add a model as a provider
- in workflow mode, select the vision model in LLM node, an eye vison mark will be shown

image
image

### CODE REVIEW

**Review by Yeuoly — APPROVED** [review]
LGTM

**Comment by sunhaha123** [comment]
Great job! How to triggle it? Git pull haved.
image
image

**Comment by Yeuoly** [comment]
> Great job! How to triggle it? Git pull haved. image image

just setup qwen-chat-vl again in Dify, you will reach it :).

**Comment by sunhaha123** [comment]
@Minamiyama  https://github.com/xorbitsai/inference/pull/1425 Should I update xinference first? Only update dify, I still can't see the "eye" in "qwen-chat-vl". If using openai api comaptiblie, it showing that not support stream.

**Comment by Minamiyama** [comment]
> @Minamiyama [xorbitsai/inference#1425](https://github.com/xorbitsai/inference/pull/1425) Should I update xinference first? Only update dify, I still can't see the "eye" in "qwen-chat-vl". If using openai api comaptiblie, it showing that not support stream.
> 
> Updating xinference from source code seem not smoothly because of some new changes.

remove the old qwen-chat-vl from xinference provider, and add it as a totally new one, you should see the eye mark. And try to create a new workflow, just in case

**Comment by sunhaha123** [comment]
I have find out, the docker image is out of date.

**Pull request merged**
