### PR TITLE
feat:add 'name' field return

### PR DESCRIPTION
**Pull request by leslie2046**
# Description

Add a new /info API ,name of app returning  for api-user recognize that  if the correct app has been using
图片

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by takatost** [comment]
Why do we still need to return the name parameter if the API Key is deeply bound with the App?

**Review by crazywoola — DISMISSED** [review]

**Comment by leslie2046** [comment]
> Why do we still need to return the name parameter if the API Key is deeply bound with the App?

On our robot management platform, we will set the apikey of a dify app to some robots, and  the apikey of another app to other robots. It is also possible that a robot may need to switch to a different apikey to demonstrate different apps after a period of time. We need to confirm the success and correctness of the app name by echoing it after setting

**Comment by takatost** [comment]
I think we should provide a separate `/info` API to fetch app details.

**Comment by leslie2046** [comment]
could i add a new info  api?return name ,description?

**Comment by takatost** [comment]
> could i add a new info api?return name ,description?

Sure, feel free.

**Review by takatost — APPROVED** [review]
LGTM

**Pull request merged**
