### PR TITLE
feat: add Novita AI image generation tool, implemented model search, text-to-image and create tile functionalities

### PR DESCRIPTION
**Pull request by XiaoLey**
# Description

This PR adds the Novita AI image generation tool. It currently implements model query, text-to-image functionalities, and create tile functionality. This enhancement will allow users to generate images based on text input, search for specific models within the tool, and create tiles.

image

image

image

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Fix

**Comment by crazywoola** [comment]
Please fix the lint errors in the CI.

**Comment by XiaoLey** [comment]
> Please fix the lint errors in the CI.

Lint errors fixed. Please review. Thanks!

**Review by crazywoola — APPROVED** [review]

**Comment by Melody199888** [comment]
Hi, I'm Alisa from Novita AI team. I'm so happy to see you help us to build an image generation tool at Dify. Can I get your discord ID or you can email me(alisa@novita.ai) so that I can offer you a voucher at Novita AI. Also, I'd like to know your thoughts about Novita AI. Thank you for promoting.

**Comment by XiaoLey** [comment]
> Hi, I'm Alisa from Novita AI team. I'm so happy to see you help us to build an image generation tool at Dify. Can I get your Novita AI account and discord ID or you can email me([alisa@novita.ai](mailto:alisa@novita.ai)) so that I can offer you a voucher at Novita AI. Also, I'd like to know your thoughts about Novita AI. Thank you for promoting.

Hi Alisa, thank you so much for your appreciation and invitation! I'm thrilled to see the positive response to the image generation tool I built using Novita AI in Dify. I really love Novita AI for its simplicity and efficiency.

Currently, I'm developing a tool related to image generation and processing, and I'm looking to integrate Novita AI's functionality to enhance its applications and user experience. While I might not be able to reply to the email immediately due to my busy schedule, I assure you that I will get back to you as soon as possible. I also plan to continue maintaining the Novita AI-based tool in Dify.

Thanks again! 😄

**Pull request merged**
