### PR TITLE
feat(embed): enhance config and add custom styling support

### LINKED ISSUE #5409: Customizable Button Style and Movable Assistant for Embedded iFrame
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

图片

When embedding the application into a website, the Dify button is introduced via an iframe, which prevents me from modifying its style. This results in the button overlapping with the website’s own functional buttons. Could it be possible to customize the style of this button so that I can manually specify its position? Additionally, it would be even better if users could freely move the assistant's position.

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

### LINKED ISSUE #5554: CSS Customization Issue with Dify Embedded AI Application
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hello Dify Team,

I wanted to share my excitement about Dify - this product is absolutely amazing and the best knowledge base project I have ever used!

What surprised me the most is the ability to embed AI applications into business websites by simply copying the script code into the <head> or <body> tag.

However, I encountered an issue with the no-code configuration. By default, Dify positions itself at the bottom right of the website with a 1rem margin. This position covers the buttons on my website. Regardless of whether I use the script or iframe method to embed Dify, I cannot modify its CSS.

I have previously reported this issue as well, see #5409

I have thought of 3 possible solutions, any of which should meet the requirements:

1. Passing styles via URL parameters, for example:
```
<script>
  window.difyChatbotConfig = {
    token: 'wCXbSRqy3FKmmzqU',
    baseUrl: 'http://10.8.2.70',
    customCssUrl: 'http://xxx.css' 
  }
</script>
<script
  src="http://10.8.2.70/embed.min.js"
  id="wCXbSRqyz3FKm1mqU"
  defer>
</script>
```
2. Allow users to customize the DOM and write their own CSS.

3. Allow developers to completely overwrite the entire page.

Thank you very much for looking into my issue. I have also raised another issue previously, please take a look when you have some time: #5410.

Thanks again!

### 2. Additional context or comments

_No response_

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by Tian-Hun**
# Description

- Introduce 'draggable' configuration option for chatbot button
- Add 'containerProps' to allow custom properties for the chatbot container
- Implement support for overriding default styles
- Refactor embed code to accommodate new customization options

Fixes #5554
Fixes #5409

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

To verify the changes introduced in feat(embed): enhance config and add custom styling support, the following tests were conducted:

+ Environment:
   + Browser: Chrome
   + Operating System: macOS

+ Test Cases:
    + Basic Embed: Embedded the chatbot bubble button with default configuration to ensure core functionality remains intact.
    + Draggability:
       + Enabled draggable: true and tested dragging the button along both axes (dragAxis: 'both').
       + Enabled draggable: true and tested dragging the button along the x-axis only (dragAxis: 'x').
       + Enabled draggable: true and tested dragging the button along the y-axis only (dragAxis: 'y').
       + Verified that dragging does not occur when draggable: false.

    + Custom Styling (CSS Variables):
       + Overrode each supported CSS variable individually to confirm their effect on the button's appearance.
       + Tested combinations of CSS variable overrides to ensure compatibility and correct cascading.
    
    + Custom Styling (containerProps):
       + Applied various inline styles (containerProps.style) to override default styles.
       + Tested applying a CSS class (containerProps.className) to the button.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [x] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ZimaBlueee** [comment]
请问这个pr为啥一直没人合并呀？

**Comment by crazywoola** [comment]
Link https://github.com/langgenius/dify/issues/4815

**Comment by crazywoola** [comment]
Example

```
<script>
 window.difyChatbotConfig = {
    token: 'YOUR KEY',
    draggable: true,
    containerProps: {
        style: {
            backgroundColor: '#ABC000',
            width: '80px',
            borderRadius: '10px',
        },
      className: 'my-custom-class',
    }
 }
</script>

<style>
  #dify-chatbot-bubble-button {
    --dify-chatbot-bubble-button-bg-color: #ABCDEF;
  }
  .my-custom-class {
    height: 50px;
  }
</style>

<script>
  !function(){const e="difyChatbotConfig",t="dify-chatbot-bubble-button",n="dify-chatbot-bubble-window",o={open:'<svg id="openIcon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n      <path fill-rule="evenodd" clip-rule="evenodd" d="M7.7586 2L16.2412 2C17.0462 1.99999 17.7105 1.99998 18.2517 2.04419C18.8138 2.09012 19.3305 2.18868 19.8159 2.43598C20.5685 2.81947 21.1804 3.43139 21.5639 4.18404C21.8112 4.66937 21.9098 5.18608 21.9557 5.74818C21.9999 6.28937 21.9999 6.95373 21.9999 7.7587L22 14.1376C22.0004 14.933 22.0007 15.5236 21.8636 16.0353C21.4937 17.4156 20.4155 18.4938 19.0352 18.8637C18.7277 18.9461 18.3917 18.9789 17.9999 18.9918L17.9999 20.371C18 20.6062 18 20.846 17.9822 21.0425C17.9651 21.2305 17.9199 21.5852 17.6722 21.8955C17.3872 22.2525 16.9551 22.4602 16.4983 22.4597C16.1013 22.4593 15.7961 22.273 15.6386 22.1689C15.474 22.06 15.2868 21.9102 15.1031 21.7632L12.69 19.8327C12.1714 19.4178 12.0174 19.3007 11.8575 19.219C11.697 19.137 11.5262 19.0771 11.3496 19.0408C11.1737 19.0047 10.9803 19 10.3162 19H7.75858C6.95362 19 6.28927 19 5.74808 18.9558C5.18598 18.9099 4.66928 18.8113 4.18394 18.564C3.43129 18.1805 2.81937 17.5686 2.43588 16.816C2.18859 16.3306 2.09002 15.8139 2.0441 15.2518C1.99988 14.7106 1.99989 14.0463 1.9999 13.2413V7.75868C1.99989 6.95372 1.99988 6.28936 2.0441 5.74818C2.09002 5.18608 2.18859 4.66937 2.43588 4.18404C2.81937 3.43139 3.43129 2.81947 4.18394 2.43598C4.66928 2.18868 5.18598 2.09012 5.74808 2.04419C6.28927 1.99998 6.95364 1.99999 7.7586 2ZM10.5073 7.5C10.5073 6.67157 9.83575 6 9.00732 6C8.1789 6 7.50732 6.67157 7.50732 7.5C7.50732 8.32843 8.1789 9 9.00732 9C9.83575 9 10.5073 8.32843 10.5073 7.5ZM16.6073 11.7001C16.1669 11.3697 15.5426 11.4577 15.2105 11.8959C15.1488 11.9746 15.081 12.0486 15.0119 12.1207C14.8646 12.2744 14.6432 12.4829 14.3566 12.6913C13.7796 13.111 12.9818 13.5001 12.0073 13.5001C11.0328 13.5001 10.235 13.111 9.65799 12.6913C9.37138 12.4829 9.15004 12.2744 9.00274 12.1207C8.93366 12.0486 8.86581 11.9745 8.80418 11.8959C8.472 11.4577 7.84775 11.3697 7.40732 11.7001C6.96549 12.0314 6.87595 12.6582 7.20732 13.1001C7.20479 13.0968 7.21072 13.1043 7.22094 13.1171C7.24532 13.1478 7.29407 13.2091 7.31068 13.2289C7.36932 13.2987 7.45232 13.3934 7.55877 13.5045C7.77084 13.7258 8.08075 14.0172 8.48165 14.3088C9.27958 14.8891 10.4818 15.5001 12.0073 15.5001C13.5328 15.5001 14.735 14.8891 15.533 14.3088C15.9339 14.0172 16.2438 13.7258 16.4559 13.5045C16.5623 13.3934 16.6453 13.2987 16.704 13.2289C16.7333 13.1939 16.7567 13.165 16.7739 13.1432C17.1193 12.6969 17.0729 12.0493 16.6073 11.7001ZM15.0073 6C15.8358 6 16.5073 6.67157 16.5073 7.5C16.5073 8.32843 15.8358 9 15.0073 9C14.1789 9 13.5073 8.32843 13.5073 7.5C13.5073 6.67157 14.1789 6 15.0073 6Z" fill="white"/>\n    </svg>',close:'<svg id="closeIcon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n      <path d="M18 18L6 6M6 18L18 6" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n    </svg>'};document.body.onload=function(){const i=window[e];if(!i||!i.token)return void console.error(`${e} is empty or token is not provided`);const d=i.baseUrl||`https://${i.isDev?"dev.":""}udify.app`;function r(){const e=document.getElementById(n),o=document.getElementById(t);if(e&&o){const t=o.getBoundingClientRect(),n=window.innerHeight-t.bottom,i=window.innerWidth-t.right,d=t.left;e.style.bottom=`${n+t.height+5+e.clientHeight>window.innerHeight?n-e.clientHeight-5:n+t.height+5}px`,e.style.right=`${i+e.clientWidth>window.innerWidth?window.innerWidth-d-e.clientWidth:i}px`}}document.getElementById(t)||function(){const e=document.createElement("div");Object.entries(i.containerProps||{}).forEach(([t,n])=>{"className"===t?e.classList.add(...n.split(" ")):"style"===t?"object"==typeof n?Object.assign(e.style,n):e.style.cssText=n:"function"==typeof n?e.addEventListener(t.replace(/^on/,"").toLowerCase(),n):e[t]=n}),e.id=t;const s=document.createElement("style");document.head.appendChild(s),s.sheet.insertRule(`\n        #${e.id} {\n          position: fixed; \n          bottom: var(--${e.id}-bottom, 1rem);\n          right: var(--${e.id}-right, 1rem);\n          left: var(--${e.id}-left, unset);\n          top: var(--${e.id}-top, unset);\n          width: var(--${e.id}-width, 50px);\n          height: var(--${e.id}-height, 50px);\n          border-radius: var(--${e.id}-border-radius, 25px); \n          background-color: var(--${e.id}-bg-color, #155EEF);\n          box-shadow: var(--${e.id}-box-shadow, rgba(0, 0, 0, 0.2) 0px 4px 8px 0px);\n          cursor: pointer;\n          z-index: 2147483647; \n          transition: all 0.2s ease-in-out 0s; \n        }\n      `),s.sheet.insertRule(`\n        #${e.id}:hover {\n          transform: var(--${e.id}-hover-transform, scale(1.1));\n        }\n      `);const l=document.createElement("div");l.style.cssText="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%; z-index: 2147483647;",l.innerHTML=o.open,e.appendChild(l),document.body.appendChild(e),e.addEventListener("click",function(){const e=document.getElementById(n);if(!e)return function(){const e=document.createElement("iframe");e.allow="fullscreen;microphone",e.title="dify chatbot bubble window",e.id=n,e.src=`${d}/chatbot/${i.token}`,e.style.cssText="\n        border: none; position: fixed; flex-direction: column; justify-content: space-between; \n        box-shadow: rgba(150, 150, 150, 0.2) 0px 10px 30px 0px, rgba(150, 150, 150, 0.2) 0px 0px 0px 1px; \n        bottom: 5rem; right: 1rem; width: 24rem; max-width: calc(100vw - 2rem); height: 40rem; \n        max-height: calc(100vh - 6rem); border-radius: 0.75rem; display: flex; z-index: 2147483647; \n        overflow: hidden; left: unset; background-color: #F3F4F6;\n      ",document.body.appendChild(e)}(),r(),void(l.innerHTML=o.close);e.style.display="none"===e.style.display?"block":"none",l.innerHTML="none"===e.style.display?o.open:o.close,r()}),i.draggable&&function(e,i){let d,r,s=!1;e.addEventListener("mousedown",function(t){s=!0,d=t.clientX-e.offsetLeft,r=t.clientY-e.offsetTop}),document.addEventListener("mousemove",function(l){if(!s)return;e.style.transition="none",e.style.cursor="grabbing";const c=document.getElementById(n);c&&(c.style.display="none",e.querySelector("div").innerHTML=o.open);const a=l.clientX-d,h=window.innerHeight-l.clientY-r,p=e.getBoundingClientRect(),u=window.innerWidth-p.width,C=window.innerHeight-p.height;"x"!==i&&"both"!==i||e.style.setProperty(`--${t}-left`,`${Math.max(0,Math.min(a,u))}px`),"y"!==i&&"both"!==i||e.style.setProperty(`--${t}-bottom`,`${Math.max(0,Math.min(h,C))}px`)}),document.addEventListener("mouseup",function(){s=!1,e.style.transition="",e.style.cursor="pointer"})}(e,i.dragAxis||"both")}()}}();
</script>

```

**Review by crazywoola — APPROVED** [review]

**Comment by charli117** [comment]
The experience is quite good, with support for adjusting styles and adaptive window positions 👍🏻👍🏻👍🏻👍🏻

**Pull request merged**
