### PR TITLE
Add Devcontainer Support for Remote Development

### PR DESCRIPTION
**Pull request by guangtouwangba**
This pull request introduces devcontainer support for both local and remote development scenarios, aiming to provide a consistent and reproducible development environment for all contributors.

Changes include:

**Creation of a basic devcontainer configuration file**: A new devcontainer configuration file has been added, enabling VS Code's Remote-Containers feature for this project. This will standardize the development environment, mitigating the issue of inconsistencies between different developers' environments.

**Initialization of Frontend and Backend Development Environments within Devcontainer**: The devcontainer now automatically sets up both the frontend and backend development environments upon initialization. This streamlines the setup process, allowing developers to jump straight into the code.

**Integration of Docker-in-Docker (DinD) setting**: With the Docker-in-Docker setting, developers can now build, run and test Docker containers directly inside the devcontainer. This is particularly useful for developers that work on features involving Docker itself.

**Support for remote usage with github Copilot**: The devcontainer now supports github Copilot for remote development, enabling developers to easily deploy and manage their applications in github environments.

These enhancements greatly simplify the development setup process, promote environment consistency across multiple developers, and cater to a wide range of local and remote development use cases.

Please review these changes. Looking forward to your valuable feedback!

### CODE REVIEW

**Review by takatost — DISMISSED** [review]
Awesome! But I haven't tried this method before, can you confirm if it works properly?

**Comment by guangtouwangba** [comment]
i ve already use this in my forked repo now, it works fine for me

**Comment by takatost** [comment]
> there is one trick thing is, if you want to open this repo directly from codespace, the endpoint `/signin` is conflicted with codespace see this https://github.com/orgs/community/discussions/5204, a workaround way is temporarily change **signin** endpoint into another one.有一个技巧是，如果您想直接从代码空间打开此存储库，端点 `/signin` 与代码空间冲突，请参阅此 https://github.com/orgs/community/discussions/5204，解决方法是暂时将登录端点更改为另一个端点。 after doing this, all things should work fine. 完成此操作后，一切都应该正常进行。 this frontend:  这个前端： image this is the backend: 这是后端： image and dockers:  和码头工人： image

This seems like it could cause some issues. "signin" is a very common login route address, so making changes to this route would be troublesome for us. I suggest adding a note in the README to avoid this problem.

**Comment by guangtouwangba** [comment]
sure, I will add a troubleshooting part in the readme, and I am looking for the solution to solve this problem too

**Pull request merged**
