### PR TITLE
feat: support Chroma vector store

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

- chroma is one of popular vector db for storing embeddings: https://docs.trychroma.com/
- using `chromadb` library to connect chroma db : https://pypi.org/project/chromadb/
  - `chromadb-client` is not used, which is a lighter HTTP client-only library. it seems does not have stable version release, as all the released version has a `dev*` appendix. (https://pypi.org/project/chromadb-client/#description)
- add tests for ChromaVector
- removed `tenacity` dependency, for two main reasons, 1. `tenacity` is never directly used, 2. `chromadb` library requires `tenacity>=8.2.3` as transparent dependency

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

- [x] add `ChromaVectorTest` integration tests with dockerfile

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JohnJyong** [comment]
conflicted by your pr: https://github.com/langgenius/dify/pull/5033

**Comment by bowenliang123** [comment]
Thanks, have fixed the conflicts.

Btw, this PR brings initial support for Chorma db , without authentication support (which will be covered in future PR), as there are currently still some trouble enabling basic or token-based authentication with Chroma on docker-compose.

**Comment by bowenliang123** [comment]
Hold on this pr.

**Comment by bowenliang123** [comment]
Hi, I have fixed the conflicts. It should be good to go.

And I also brings the authentication support into vdb adaptors and integration tests, which supports both Chroma's basic and token-based authentication.

**Review by crazywoola — DISMISSED** [review]

**Review by crazywoola — APPROVED** [review]

**Pull request merged**
