### PR TITLE
feat: add volcengine maas model provider

### PR DESCRIPTION
**Pull request by sinomoe**
# Description

add volcengine maas models provider

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] self-host environment test
image
image
image

 

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sinomoe** [comment]
> Can you please add some integrate or unit tests?

sure

**Comment by sinomoe** [comment]
> Can you please add some integrate or unit tests?

@takatost Integration test cases have been added

**Comment by takatost** [comment]
> > Can you please add some integrate or unit tests?
> 
> 
> 
> @takatost Integration test cases have been added

Thanks! We will review and test ASAP.

**Review by takatost — APPROVED** [review]
I haven't applied for the maas permission of Volcengine yet, but I have reviewed the code and found no issues. Thank you very much!

**Comment by crazywoola** [comment]
Hello please add my wechat crazyphage, I will invite you to our contributors' group.

**Comment by crazywoola** [comment]
@sinomoe Hello can you add my wechat crazyphage, @Yeuoly and @takatost is looking for you.

**Comment by sinomoe** [comment]
@crazywoola Sorry to reply to you so late, I've already sent out an add request

**Pull request merged**
