### PR TITLE
fix: tongyi json output

### LINKED ISSUE #5397: Json format got no response with tongyi models
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

turn on response_format in tongyi models and select json

image

### ✔️ Expected Behavior

output json

### ❌ Actual Behavior

nothing output, even no log button

### PR DESCRIPTION
**Pull request by lxm**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes https://github.com/langgenius/dify/issues/5397

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## api change
Accroding to [tongyi api docs](!https://help.aliyun.com/document_detail/2712576.html). There's no different between chat models and completaion models. 

original code: in `api/core/model_runtime/model_providers/tongyi/llm/llm.py` line 245, 249 will cause prompt missing when using json response format
```
        else:
            if mode == LLMMode.CHAT:
                params['messages'] = self._convert_prompt_messages_to_tongyi_messages(prompt_messages)
            else:
                params['prompt'] = prompt_messages[0].content.rstrip()
```

## json parse change
as comment in file `api/core/model_runtime/model_providers/__base/large_language_model.py`, some LLM with directly output json data without markdown block 

## test result with same prompt

```
请按以下格式输出json数据 `{"data": "test", "code": 200, "msg": "success"}`
```

### before change

image

### after change

image

- [ ] TODO raise a error when json output did not satisfy 

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by laipz8200** [comment]
Thanks for your contribution, please open an issue first, then link it to this PR. It will helpful for us to manage our community. 😇

**Comment by laipz8200** [comment]
The `_code_block_mode_stream_processor_with_backtick` method in `LargeLanguageModel` is designed to parse markdown code block content.

If the model doesn't return the expected format, we shouldn't parse it. Alternatively, you can implement it within the Tongyi LLM.

**Comment by lxm** [comment]
But no markdown requires in any system prompt, maybe we should change system prompt?

**Comment by laipz8200** [comment]
> But no markdown requires in any system prompt, maybe we should change system prompt?

Yeah, maybe we should rewrite the system prompt and test it on more models. Let's discuss this in the related issue.

**Comment by lxm** [comment]
So, I change the block_prompts in tongyi model and add test cases for json ouput.
Tests that check response_format should be add to more models.

**Review by laipz8200 — APPROVED** [review]
Thanks a lot for doing that. We'll evaluate the default system prompt later.

**Pull request merged**
