### PR TITLE
feat:support azure tts

### PR DESCRIPTION
**Pull request by leslie2046**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by takatost — APPROVED** [review]
LGTM

**Comment by huanmengmie** [comment]
Hello, when I was configuring Azure openAI's TTS, I encountered a 404 resource not found error. I checked my model deployment information and found no problem. Then, when I checked the logs, I noticed that the API version it's accessing is **2023-12-01-preview**, while Azure's documentation version is **2024-02-15-preview**. Can you add an input box for the API version on the page for easier version switching for testing purposes?

Environment information: docker image **main version**, image ID is 4a6f2dc25985
       
image
image
image

**Comment by leslie2046** [comment]
> Hello, when I was configuring Azure openAI's TTS, I encountered a 404 resource not found error. I checked my model deployment information and found no problem. Then, when I checked the logs, I noticed that the API version it's accessing is **2023-12-01-preview**, while Azure's documentation version is **2024-02-15-preview**. Can you add an input box for the API version on the page for easier version switching for testing purposes?
> 
> Environment information: docker image **main version**, image ID is 4a6f2dc25985
> 
> image image image

OK，i will check it

**Comment by huanmengmie** [comment]
If there is any progress, please let me know, thank you

**Comment by leslie2046** [comment]
@huanmengmie you can update now
#2821

**Pull request merged**
