### PR TITLE
feat: add alist tool

### LINKED ISSUE #7706: Add a new tool that can connect to cloud storage or network disk
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

When using the Dify workflow, a module that retrieves content from the Internet is used. After retrieval, it needs to be saved to a file for subsequent use. In this case, it is very suitable to be saved on object storage or other cloud storage. Although it can also be handled by using Python code modules, it is inconvenient to use and the threshold for use needs to be lowered.

### 2. Additional context or comments

like coze，it has OSS file operation tool.
image

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by yaoice**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

Fixes #7706 

[AList](https://github.com/alist-org/alist) is the popular github project that has 41.6k star. AList is a file listing program that supports multiple storage providers including Dropbox, Alibaba Cloud Disk, OneDrive, Google Drive, etc., and is easy to expand. 
image

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
1. Install alist and configure alist storage
image
image

2. setup dify workflow with alist tool
image
image

3. run the workflow and verify the result
image
image
image

### CODE REVIEW

**Comment by crazywoola** [comment]
Hello, we are working on refine the core of tools part, so we will postpone the PR until we have finished those works.

**Comment by yaoice** [comment]
> Hello, we are working on refine the core of tools part, so we will postpone the PR until we have finished those works.

Understood. Looking forward to seeing the refined core of the tools part.

**Comment by crazywoola** [comment]
Sorry, we do not accept new tools for now, we plan to have a tool market place int he future. :)

**Comment by yaoice** [comment]
> Sorry, we do not accept new tools for now, we plan to have a tool market place int he future. :)

Thank you for your response. I understand your decision and look forward to the tool marketplace in the future.

**Comment by lzqoscar** [comment]
Sorry to border you. When I try to add my tools just like what you do, I have failed to find my tools in web. Did I miss any steps during modification? What should I do to make the changes take effect after modifying the code? Thanks a lot for your help.

**Pull request closed without merging**
