### PR TITLE
feat: add moonshot support

### LINKED ISSUE #2397: support moonshot
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### 1. Is this request related to a challenge you're experiencing?

Moonshot has launched its open platform, which performs better and has faster access speed in China compared to many other models

### 2. Describe the feature you'd like to see

support moonshot apiAPI

### 3. How will this feature improve your workflow or experience?

Improve model inference performance

### 4. Additional context or comments

_No response_

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by jialeicui**
Closes #2397

### CODE REVIEW

**Review by Yeuoly — CHANGES_REQUESTED** [review]
missing pricing config, you can see https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/openai/llm/gpt-3.5-turbo-0125.yaml and https://github.com/langgenius/dify/blob/main/api/core/model_runtime/docs/en_US/provider_scale_out.md#AddModel to get more detailed information.

**Comment by Yeuoly** [comment]
moonlight provides an API to get nums of tokens
```bash
POST https://api.moonshot.cn/v1/tokenizers/estimate-token-count
```

the get_num_tokens method should be implemented, instead of using parent's method.

**Comment by Yeuoly** [comment]
have you checked that moonlight supports function calling? It seems not, but `multi-tool-call` and `stream-tool-call` are declared in moonshot-v1-8k.yaml which would lead Agent Assistant App to use function calling runner.

**Comment by jialeicui** [comment]
> moonlight provides an API to get nums of tokens
> 
> ```shell
> POST https://api.moonshot.cn/v1/tokenizers/estimate-token-count
> ```
> 
> the get_num_tokens method should be implemented, instead of using parent's method.

What scenario the `get_num_tokens` function is designed for, will there a risk of frontend page lag when calls are frequent and with moonshot API? 
@Yeuoly

**Comment by Yeuoly** [comment]
> > moonlight provides an API to get nums of tokens
> > ```shell
> > POST https://api.moonshot.cn/v1/tokenizers/estimate-token-count
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the get_num_tokens method should be implemented, instead of using parent's method.
> 
> What scenario the `get_num_tokens` function is designed for, will there a risk of frontend page lag when calls are frequent and with moonshot API? @Yeuoly

Dify use `get_num_tokens` to predict how many tokens one requests would cost, and reject a request if the message is too long, by default, `gpt2-tokenizer` will be used to calculate the tokens, but it calculates more tokens than real typically.

**Comment by jialeicui** [comment]
> > > > moonlight provides an API to get nums of tokens
> > > > ```shell
> > > > POST https://api.moonshot.cn/v1/tokenizers/estimate-token-count
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the get_num_tokens method should be implemented, instead of using parent's method.
> > > 
> > > 
> > > What scenario the `get_num_tokens` function is designed for, will there a risk of frontend page lag when calls are frequent and with moonshot API? @Yeuoly
> > 
> > 
> > Dify use `get_num_tokens` to predict how many tokens one requests would cost, and reject a request if the message is too long, by default, `gpt2-tokenizer` will be used to calculate the tokens, but it calculates more tokens than real typically.
> 
> okay, `gpt-2` is fine, one http request brings a long latency, which is a bad experience.

ok, I'll revert the last commit

**Review by Yeuoly — APPROVED** [review]

**Comment by crazywoola** [comment]
Hello can you add my wechat crazyphage I will invite you to our group chat.

**Pull request merged**
