### PR TITLE
feat: add Typewriter tool for converting Markdown text into HTML, PDF and DOCX files

### PR DESCRIPTION
**Pull request by bowenliang123**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

- Introducing a new tool `Typewriter` for generating binary file
  - convert Markdown text to HTML file
     - using `markdown` library to convert markdown text into HTML file
  - convert Markdown text to PDF file
     - firstly using `markdown` library to convert markdown text into HTML file , then convert HTML into PDF by `xhtml2pdf` library
     - for the generated PDF file:
        - limitation in fonts: the font support varies in different PDF viewers(Adobe Acrobat Reader, Chrome, MacOS Preview and etc.), since each PDF viewer embeds different font families
        - the suggested font list according to `xhtml2pdf`: https://xhtml2pdf.readthedocs.io/en/latest/reference.html#font     
   - convert Markdown text to HTML file
        - only text paragraph with limited style support

Workflow with the introduced Typewriter tool:
image

Raw markdown text before converting:
```
# English
The Moon is a celestial body that orbits the Earth, with a diameter of about 3,474 kilometers.

# 月球
月球是一个围绕地球运行的星球，直径约为3474公里。

# 繁体中文
月球是一個圍繞地球運行的星球，直徑約為3474公里。

# 日本語
月は地球の周りを回る天体で、直径は約3474キロメートルです。

# Português
A Lua é um corpo celeste que orbita a Terra, com um diâmetro de cerca de 3.474 quilômetros.
```

Conversations for saved HTML:
image

Saved HTML file viewed in Google Chrome:
image

Conversation for saving PDF:
image

Saved PDF file viewed in Adobe Acrobat Reader 2024:
image

Saved DOCX file viewed in Microsoft Office for Mac 2024 16.89.1 (24091630):
image

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bowenliang123** [comment]
Hi @laipz8200 , would you like to have a quick look at this PR? It might be interesting to consider be merged as part of v0.10.0, if you like. This tool helps to generate a solid single HTML / PDF file which enlarges many application scenarios. It requires more polishment to avoid hacking in callbacks of handling generation of URL generation for viewing and downloading the file, while v0.10.0-beta may help in this case bring more support in tools files. Welcome to ping me to have further discussion or improvement any time.

**Comment by bowenliang123** [comment]
It's now ready for review. cc @laipz8200 @takatost

**Comment by bowenliang123** [comment]
Any better name for the tool ? Possible candidates:
- Typewriter ( quite vivid, but hard to understand )
- FileGenerator (plain as it is)
- MarkdownConverter (would not like to be limited with markdown style input, however)
- other...

 @laipz8200 @crazywoola

**Comment by crazywoola** [comment]
Sorry, we do not accept new tools for now, we plan to have a tool market place int he future. :)

**Pull request closed without merging**
