### PR TITLE
feat: support fish audio TTS

### LINKED ISSUE #7984: Support Fish Audio TTS
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Fish Audio introduces customized voice capability with low latency. This new functionality allows users to personalize audio output while maintaining quick response times.

### 2. Additional context or comments

[Fish Speech](fishaudio/fish-speech), an open-source project by Fish Audio, plans to release version 1.4 around September 10. The team aims to add support for both their PaaS and open-source API to Dify, enhancing integration options for users.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

### PR DESCRIPTION
**Pull request by leng-yue**
# Checklist:

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [x] Please open an issue before creating a PR or link to an existing issue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

# Description

This PR add Fish Audio TTS support to dify Close #7984.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement, including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# Testing Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test TTS with public English Voice, Normal Latency
- [x] Test TTS with private English Voice, Low Latency

### CODE REVIEW

**Review by crazywoola — APPROVED** [review]

**Comment by leslie2046** [comment]
Cannot list my private models?

**Comment by leng-yue** [comment]
> Cannot list my private models? BTW ,i find that the API will return the private voice list if self=false, and not passing the language param. @leng-yue

Let me take a look

**Comment by leng-yue** [comment]
> Cannot list my private models? BTW ,i find that the API will return the private voice list if self=false, and not passing the language param. @leng-yue

I fixed the filtering behavior for language—it now filters based on the model language only, without the title language. I double-checked with `self=false` and without the language parameter on the [API Playground](https://docs.fish.audio/api-reference/endpoint/model/list-models) and couldn't reproduce the issue.

**Comment by leslie2046** [comment]
@leng-yue OK,thank you

**Comment by leslie2046** [comment]
@leng-yue what's the difference between GPT-SoVITS and fish?which is better?

**Comment by cubxxw** [comment]
@leng-yue Do you currently support it? Do you consider supporting it.Do you currently support it? Do you consider supporting it?

```
    "voice_preferences": {                  // 语音回复的偏好设置 (可选)
        "gender": "female",                 // 声音性别 (female, male)
        "voice_speed": "normal",            // 语速 (slow, normal, fast)
        "emotion": ["neutral"]              // 情绪选择 (neutral, happy, sad, etc.)
    },
```

**Comment by momomobinx** [comment]
这个好像不兼容本地部署的fish-speech 的api
[](https://speech.fish.audio/inference/#3-generate-vocals-from-semantic-tokens)

python -m tools.api_server \
    --listen 0.0.0.0:8080 \
    --llama-checkpoint-path "checkpoints/fish-speech-1.5" \
    --decoder-checkpoint-path "checkpoints/fish-speech-1.5/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" \
    --decoder-config-name firefly_gan_vq

**Comment by chunxiao369** [comment]
how to use local fish-speech? python -m tools.api_server --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.5" --decoder-checkpoint-path "checkpoints/fish-speech-1.5/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" --decoder-config-name firefly_gan_vq 

error msg: GET /model?self=true&page_size=100 HTTP/1.1" 404 Not Found

Thank you!

**Pull request merged**
