### PR TITLE
generalize helper for parsing string to boolean

### PR DESCRIPTION
**Pull request by bowenliang123**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [ ] Improvement，including but not limited to code refactoring, performance optimization, and UI/UX improvement
- [ ] Dependency upgrade

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] TODO

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods
- [ ] `optional` I have made corresponding changes to the documentation 
- [ ] `optional` I have added tests that prove my fix is effective or that my feature works
- [ ] `optional` New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by LeoQuote** [comment]
IMHO this can be done with pydantic settings https://docs.pydantic.dev/1.10/usage/settings/

```
class DifySettings(BaseSettings):
    DEBUG: bool = False

dify_settings = DifySettings()

assert dify_settings.DEBUG == False
```

It just works.

Read more: https://docs.pydantic.dev/1.10/usage/types/#booleans

**Comment by bowenliang123** [comment]
This PR is not targeted to refactor the configs for the API / worker app. It provides a general helper for parsing boolean only.

I do feel the dify has to refactor configs in the future,  for managing、 configuring、 system environment 、 desciption、and default values for config entries. This requires a better and complete redesign to that,

**Comment by LeoQuote** [comment]
This could be helpful https://pydantic-argparse.supimdos.com/

**Comment by bowenliang123** [comment]
That's way too heavy to import a dedicated lib for this. Forget about Pydantic, it's main purpose is for guarding value checks for model's fields.

**Comment by crazywoola** [comment]
> This could be helpful https://pydantic-argparse.supimdos.com/

I agree with @LeoQuote since we've just update the deps days ago.

**Comment by bowenliang123** [comment]
OK. Closing this PR. Reopen if we have further consensus.

**Pull request closed without merging**
